import test from 'node:test'
import assert from 'node:assert/strict'
import { webcrypto } from 'node:crypto'

const values=new Map<string,string>()
Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)}})
Object.defineProperty(globalThis,'crypto',{value:webcrypto})
const store=await import('./accountStore.ts')

test('two registrations share one public flow but remain separate accounts',async()=>{values.clear();const a=await store.registerAccount({email:'a@example.com',displayName:'Alex',password:'password-a'});store.signOutAccount();const b=await store.registerAccount({email:'b@example.com',displayName:'Blair',password:'password-b'});assert.notEqual(a.id,b.id);assert.equal(a.displayName,'Alex');assert.equal(b.displayName,'Blair');assert.equal((await store.signInAccount('a@example.com','password-a')).id,a.id)})
test('program entitlement protects Femmes and rider cannot self-grant',async()=>{values.clear();const rider=await store.registerAccount({email:'rider@example.com',displayName:'Rider',password:'password-r'});assert.equal(store.hasProgramAccess(rider,'rtr-femmes'),false);assert.throws(()=>store.grantProgram(rider,rider.id,'rtr-femmes'),/Owner/);assert.equal(store.hasProgramAccess(rider,'intro-cycling'),true)})
test('enrollment can assign Standard RtR without granting protected Femmes',async()=>{values.clear();const rider=await store.registerAccount({email:'standard@example.com',displayName:'Standard',password:'password-s'}),enrolled=store.assignEnrollmentProgram(rider.id,'rtr-standard');assert.equal(store.hasProgramAccess(enrolled,'rtr-standard'),true);assert.equal(store.hasProgramAccess(enrolled,'rtr-femmes'),false)})
test('local owner deterministically approves a requested program',async()=>{values.clear();const rider=await store.registerAccount({email:'request@example.com',displayName:'Requestor',password:'password-q'});store.requestProgram(rider.id,'rtr-femmes');localStorage.setItem('ride-the-races-v2-career',JSON.stringify({rider:{name:'Owner'}}));const owner=store.migrateLegacyOwner('Owner')!;assert.equal(store.listAccounts(owner).find(item=>item.id===rider.id)?.requestedPrograms[0],'rtr-femmes');const approved=store.grantProgram(owner,rider.id,'rtr-femmes');assert.equal(store.hasProgramAccess(approved,'rtr-femmes'),true);assert.deepEqual(approved.requestedPrograms,[])})
test('legacy owner migration works beside accounts and is idempotent',async()=>{values.clear();await store.registerAccount({email:'existing@example.com',displayName:'Existing',password:'password-e'});localStorage.setItem('ride-the-races-v2-career',JSON.stringify({rider:{name:'Legacy'},rideHistory:[{id:'ride-1'}],equipment:{instances:[{id:'bike'}]},settings:{theme:'light'},races:{tour:{completedStages:[1]}},alpha4022:{rainbowTitles:['title']}}));const first=store.migrateLegacyOwner('Legacy')!,second=store.migrateLegacyOwner('Legacy')!;assert.equal(first.id,'legacy-owner');assert.equal(second.id,first.id);assert.equal(store.listAccounts(first).filter(item=>item.id==='legacy-owner').length,1);assert.match(localStorage.getItem('ride-the-races-v2-career')!,/ride-1/)})
