import test from 'node:test'
import assert from 'node:assert/strict'
import type { RiderAccount } from './accountStore.ts'

const values=new Map<string,string>();Object.defineProperty(globalThis,'localStorage',{value:{getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>values.set(key,value),removeItem:(key:string)=>values.delete(key)}});Object.defineProperty(globalThis,'crypto',{value:{randomUUID:()=>`id-${values.size}`,subtle:{}}})
const accounts=await import('./accountStore.ts'),transfer=await import('./previewTransfer.ts'),persistence=await import('../state/careerPersistence.ts')
const owner:RiderAccount={id:'preview-owner',email:'preview@example.com',displayName:'Preview Hal',role:'owner',passwordHash:'destination-verifier',salt:'destination-salt',entitlements:['intro-cycling'],requestedPrograms:[],createdAt:'2026-09-19T00:00:00Z'}
const other:RiderAccount={...owner,id:'other',email:'other@example.com',displayName:'Other',passwordHash:'other-verifier',salt:'other-salt'}
const seedAccounts=()=>values.set('ride-the-races-accounts-v1',JSON.stringify([owner,other]))
const hal=()=>{const career=persistence.createInitialCareer();return {...career,season:{...career.season,active:true,currentRace:'La Vuelta',completedStages:[1,2,3]},rider:{...career.rider,name:'Hal Kronenberg',number:15,ftp:206,ftpKnown:true,ftpProvenance:'RIDER_ENTERED' as const},rideHistory:[{id:'vuelta-1',date:'2026-09-01',source:'Manual' as const,durationMinutes:60,distanceKm:40,activityType:'RACE_STAGE' as const}],alpha4025:{...career.alpha4025,outdoorActivities:[{id:'outside',date:'2026-09-19',source:'WHOOP manual entry',activity:'Outdoor cycling' as const,durationSeconds:5499,distanceMiles:20.57,elevationFeet:721,elevationSource:'WHOOP-reported',averageSpeedMph:13.5,interpretation:[]}],strengthActivities:[{assignmentId:'strength-a',exercises:[]}]},compatibleUnknown:{kept:true}} as typeof career&{compatibleUnknown:{kept:boolean}}}

test('owner export contains one account-scoped career and no credentials or session data',()=>{seedAccounts();const payload=transfer.buildCareerExport(owner,hal(),null,'4.0.25','2026-09-19T12:00:00Z'),json=transfer.serializeCareerExport(payload);assert.equal(payload.format,transfer.RTR_EXPORT_FORMAT);assert.equal(payload.formatVersion,1);assert.equal(payload.sourceSchemaVersion,6);assert.equal(payload.riderSummary.number,15);assert.match(json,/vuelta-1/);assert.match(json,/compatibleUnknown/);for(const secret of ['destination-verifier','destination-salt','other-verifier','other@example.com','passwordHash','session'])assert.doesNotMatch(json,new RegExp(secret,'i'))})
test('signed-in riders may export and running rides block transfer',()=>{assert.equal(transfer.buildCareerExport({...owner,role:'rider'},hal(),null,'4.0.25').riderSummary.number,15);assert.throws(()=>transfer.buildCareerExport(owner,hal(),{runningSince:123} as never,'4.0.25'),/Pause or end/)})
test('parser rejects malformed, missing and future exports without writing destination',()=>{seedAccounts();const before=JSON.stringify(persistence.createInitialCareer());values.set('destination',before);for(const invalid of ['{',JSON.stringify({format:'wrong'}),JSON.stringify({format:transfer.RTR_EXPORT_FORMAT,formatVersion:1,sourceSchemaVersion:7,career:{}})])assert.throws(()=>transfer.parseCareerExport(invalid,persistence.createInitialCareer()));assert.equal(values.get('destination'),before)})
test('schema 5 imports to schema 6 and replacement is idempotent with destination credentials',()=>{seedAccounts();const destination={...persistence.createInitialCareer(),rider:{...persistence.createInitialCareer().rider,name:'Hal',number:1}},source={...hal(),schemaVersion:5} as never,payload=transfer.buildCareerExport(owner,source,null,'4.0.24','2026-09-19T12:00:00Z'),preview=transfer.parseCareerExport(JSON.stringify(payload),destination);assert.equal(preview.migrated.schemaVersion,6);assert.equal(preview.summary.identityDiffers,true);assert.throws(()=>transfer.commitCareerImport(owner,destination,null,preview,false),/confirmation/);transfer.commitCareerImport(owner,destination,null,preview,true,'2026-09-19T13:00:00Z');const first=values.get(accounts.careerStorageKey(owner.id));transfer.commitCareerImport(owner,destination,null,preview,true,'2026-09-19T14:00:00Z');assert.equal(values.get(accounts.careerStorageKey(owner.id)),first);const saved=JSON.parse(first!);assert.equal(saved.rider.number,15);assert.equal(saved.rider.ftp,229);assert.deepEqual(saved.season.completedStages,[1,2,3]);assert.equal(saved.alpha4025.outdoorActivities.length,1);assert.equal(saved.alpha4025.strengthActivities.length,1);const storedAccounts=JSON.parse(values.get('ride-the-races-accounts-v1')!);assert.equal(storedAccounts.find((x:RiderAccount)=>x.id===owner.id).passwordHash,'destination-verifier');assert.equal(storedAccounts.find((x:RiderAccount)=>x.id===other.id).passwordHash,'other-verifier')})
test('pre-import backup restores Rider 1 atomically',()=>{seedAccounts();const destination={...persistence.createInitialCareer(),rider:{...persistence.createInitialCareer().rider,name:'Preview Hal',number:1}},preview=transfer.parseCareerExport(transfer.serializeCareerExport(transfer.buildCareerExport(owner,hal(),null,'4.0.25')),destination);transfer.commitCareerImport(owner,destination,null,preview,true,'2026-09-19T13:00:00Z');const backup=transfer.readRecoveryBackup(owner)!;assert.equal(backup.rider.number,1);assert.throws(()=>transfer.restoreRecoveryBackup(owner,false),/confirmation/);transfer.restoreRecoveryBackup(owner,true);assert.equal(JSON.parse(values.get(accounts.careerStorageKey(owner.id))!).rider.number,1)})
test('safe filename is identifiable and traversal-safe',()=>{assert.equal(transfer.safeExportFilename('../../Hal Kronenberg','2026-09-19'),'rtr-career-hal-kronenberg-2026-09-19.json')})
