import { useState } from 'react'
import { useAuth } from '../state/AuthContext.tsx'
import { ACCOUNT_BACKEND_MODE, MULTI_DEVICE_ENROLLMENT_AVAILABLE, accountById } from '../services/accountStore.ts'

export default function AuthScreen(){
 const {register,signIn,resumeLegacyOwner}=useAuth(),[mode,setMode]=useState<'register'|'sign-in'>(()=>location.hash==='#sign-in'?'sign-in':'register'),[displayName,setDisplayName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{if(mode==='register')await register({displayName,email,password});else await signIn(email,password)}catch(reason){setError(reason instanceof Error?reason.message:'Unable to authenticate.')}finally{setBusy(false)}}
 return <section className="auth-screen"><form className="auth-card" onSubmit={submit}><p className="eyebrow">RIDE THE RACES</p><small role="status">{ACCOUNT_BACKEND_MODE.replace('_',' ')} ACCOUNT MODE · MULTI-DEVICE ENROLLMENT {MULTI_DEVICE_ENROLLMENT_AVAILABLE?'AVAILABLE':'UNAVAILABLE'}</small><h1>{mode==='register'?'Create a local rider account':'Welcome back on this device'}</h1><p>This development account keeps data in this browser only. It is not a production or cross-device account.</p>{mode==='register'&&<label>Preferred display name<input autoComplete="name" required value={displayName} onChange={event=>setDisplayName(event.target.value)}/></label>}<label>Email<input type="email" autoComplete="email" required value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Password<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} minLength={8} required value={password} onChange={event=>setPassword(event.target.value)}/></label>{error&&<p role="alert" className="auth-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'Please wait…':mode==='register'?'Register locally':'Sign in locally'}</button><a href={mode==='register'?'#sign-in':'#register'} className="text-button" onClick={()=>{setMode(mode==='register'?'sign-in':'register');setError('')}}>{mode==='register'?'Already registered on this device? Sign in':'New to this device? Register locally'}</a>{accountById('legacy-owner')&&<button type="button" onClick={resumeLegacyOwner}>Resume migrated owner career on this device</button>}</form></section>
}
