import { useEffect, useMemo, useState } from 'react'
import { useCareer } from '../state/CareerContext.tsx'
import { useAuth } from '../state/AuthContext.tsx'
import { createDevelopmentProfile, ensureHalOffSeasonPlan, generatePlan, HAL_GOALS, isHalOffSeasonCareer, projectReadiness, recommendCamps, type GoalsQuestionnaire, type PersonalizationInput, type ReadinessEntry } from '../engine/alpha4025.ts'
import { assignmentWorkout, buildZoneDevelopment, evaluateDifficulty, fourWeekPreview, halInitialZoneDevelopment, hydrateAdaptive, jeanAdaptiveExplanation, replaceWithAlternative, selectCandidate, workoutById } from '../engine/adaptiveTraining40251.ts'

export default function OffSeasonScreen({onBack,onStartWorkout}:{onBack:()=>void;onStartWorkout:(workoutId:string,assignmentId:string)=>void}){
 const {career,updateAlpha4025}=useCareer(),state=career.alpha4025
 const {account,isAuthenticated}=useAuth(),hasAccess=isAuthenticated
 const halCareer=isHalOffSeasonCareer({role:account?.role,riderName:career.rider.name,riderNumber:career.rider.number,ftp:career.rider.ftp})
 useEffect(()=>{if(isAuthenticated&&halCareer&&(!state.trainingPlan||state.trainingPlan.weeks.some(w=>w.assignments.some(a=>(a.type==='CYCLING'||a.type==='ASSESSMENT')&&!a.workoutId))))updateAlpha4025(ensureHalOffSeasonPlan)},[halCareer,isAuthenticated,state.trainingPlan,updateAlpha4025])
 const adaptive=hydrateAdaptive(state),zoneDevelopment=adaptive.zoneDevelopment,todayAssignment=state.trainingPlan?.weeks.flatMap(w=>w.assignments).find(a=>a.status==='PLANNED'&&(a.type==='CYCLING'||a.type==='ASSESSMENT')&&a.demandingCycling)??state.trainingPlan?.weeks.flatMap(w=>w.assignments).find(a=>a.status==='PLANNED'&&(a.type==='CYCLING'||a.type==='ASSESSMENT'))??null,todayWorkout=todayAssignment?assignmentWorkout(todayAssignment):null
 useEffect(()=>{if(state.trainingPlan&&zoneDevelopment.length===0){const recorded=buildZoneDevelopment(career.trainingHistory.filter(x=>x.completed).map(x=>({workoutId:x.workoutId,date:x.completedAt.slice(0,10),status:'SUCCESS' as const,source:'Completed account-scoped RtR workout'}))),hal=halInitialZoneDevelopment(),initialZoneDevelopment=halCareer?recorded.map(z=>z.level?z:hal.find(h=>h.zone===z.zone)!):recorded,fourWeek=fourWeekPreview(state.trainingPlan);updateAlpha4025(old=>({...old,adaptive:{...hydrateAdaptive(old),zoneDevelopment:initialZoneDevelopment,fourWeekPreview:fourWeek}}))}},[zoneDevelopment.length,career.trainingHistory,halCareer,state.trainingPlan,updateAlpha4025])
 const defaults:PersonalizationInput=state.intake??{category:state.riderCategory??'Prefer not to answer',seriesPreference:state.seriesPreference??'Help me choose',experience:career.rider.experience,ftp:career.rider.ftp,weeklyDays:4,weeklyMinutes:300,longRideDays:['Saturday'],preferredRestDay:'Monday',comfortableMinutes:60,indoorExperience:'Some',outdoorExperience:'Some',equipment:career.rider.devices,outdoorPowerMeter:false,heartRateAvailable:true,cadenceResistanceConfidence:'Growing',shiftingConfidence:'Growing',brakingConfidence:'Growing',outdoorConfidence:'Growing',accommodations:'',painConcerns:'',primaryGoal:'Improve fitness',secondaryGoal:'Ride longer',targetEvent:'',progression:'Balanced',recoveryDays:2,strengthDays:2,role:career.rider.archetype}
 const [input,setInput]=useState(defaults),[goals,setGoals]=useState<GoalsQuestionnaire>(state.questionnaire??{...HAL_GOALS,nextSeasonObjective:'Build toward the next season',targetEvent:'',targetDate:undefined,primaryGoal:'Improve fitness',secondaryGoal:'Ride longer',ftpGoal:undefined,climbingGoal:'Controlled climbing',enduranceGoal:'Longer comfortable rides',bodyCompositionGoal:'Sustainable change without underfueling',outdoorGoal:'Confidence and comfort',weeklyDays:input.weeklyDays,weeklyMinutes:input.weeklyMinutes,longRideDays:input.longRideDays,strengthDays:input.strengthDays,equipment:input.equipment,outdoorPowerAvailable:input.outdoorPowerMeter,accommodations:input.accommodations,currentFatigue:'Low',currentMotivation:'High',desiredStartDate:new Date().toISOString().slice(0,10)})
 const latest=state.readinessEntries.at(0),today=new Date(),localDate=[today.getFullYear(),String(today.getMonth()+1).padStart(2,'0'),String(today.getDate()).padStart(2,'0')].join('-'),ready=useMemo(()=>projectReadiness(latest,localDate,'OFF_SEASON'),[latest,localDate])
 const adaptiveWorkout=todayAssignment&&todayWorkout?evaluateDifficulty(todayAssignment.id,todayWorkout,zoneDevelopment.find(z=>z.zone===todayWorkout.primaryZone),localDate):null
 useEffect(()=>{if(!state.trainingPlan||zoneDevelopment.length===0)return;const assignment=state.trainingPlan.weeks.flatMap(w=>w.assignments).find(a=>a.status==='PLANNED'&&(a.type==='CYCLING'||a.type==='ASSESSMENT')),workout=assignment?assignmentWorkout(assignment):null,difficultyEvaluations=assignment&&workout?[evaluateDifficulty(assignment.id,workout,zoneDevelopment.find(z=>z.zone===workout.primaryZone),localDate)]:[],candidateSelection=workout?selectCandidate({purpose:workout.purpose,goal:state.developmentProfile?.developmentPriorities[0]??'Endurance',development:zoneDevelopment,availableMinutes:assignment!.durationMinutes,environment:assignment!.environment==='FLEXIBLE'?'EITHER':assignment!.environment,equipment:state.intake?.equipment??[],recoveryWeek:state.trainingPlan.weeks[0].recoveryWeek,readiness:ready,previousHighIntensity:false}):null;updateAlpha4025(old=>({...old,adaptive:{...hydrateAdaptive(old),difficultyEvaluations,candidateSelection,fourWeekPreview:fourWeekPreview(old.trainingPlan!)}}))},[zoneDevelopment,latest?.updatedAt,localDate,state.developmentProfile?.developmentPriorities,state.intake?.equipment,state.trainingPlan,ready,updateAlpha4025])
 const previewReview=isAuthenticated&&!state.seasonReview?{availableMetrics:{FTP:career.rider.ftp??'Unavailable','Recorded rides':career.rideHistory.length,'Completed Vuelta stages':career.races.vuelta.completedStages.length},unavailableMetrics:['Final season classification','Archived season totals'],offSeasonEmphasis:['Sustained climbing','FTP development','Recovery','Multi-day endurance']}:null
 const review=state.seasonReview??previewReview
 const difficulty=adaptiveWorkout
 const selectAlternative=(replacementId:string)=>{if(!state.trainingPlan||!todayAssignment||!todayWorkout)return;const replacement=workoutById(replacementId);if(!replacement)return;const id=`${todayAssignment.id}:${replacement.id}:${localDate}`;updateAlpha4025(old=>{if(old.adaptive.adaptations.some(x=>x.id===id))return old;const explanation=jeanAdaptiveExplanation(todayWorkout,replacement,[difficulty?.explanation??'No zone evidence'],[latest?'None':'Current readiness entry'],`The assignment is replaced in place; no bonus workload is added.`),record={id,date:localDate,assignmentId:todayAssignment.id,originalWorkoutId:todayWorkout.id,replacementWorkoutId:replacement.id,trigger:'Rider selected curated alternative',evidence:[difficulty?.explanation??'Insufficient evidence'],explanation,decision:'ACCEPTED' as const},changed=replaceWithAlternative(old.trainingPlan!,todayAssignment.id,replacement,record),next={...hydrateAdaptive(old),adaptations:[...old.adaptive.adaptations,record],selectedAlternatives:{...old.adaptive.selectedAlternatives,[todayAssignment.id]:replacement.id},fourWeekPreview:fourWeekPreview(changed.plan)};return {...old,trainingPlan:changed.plan,adaptive:next}})}
 const build=()=>{const developmentProfile=createDevelopmentProfile(input),campRecommendations=recommendCamps(input,goals),trainingPlan=generatePlan(input,goals,state.trainingPlan);updateAlpha4025(old=>({...old,intake:input,riderCategory:input.category,seriesPreference:input.seriesPreference,seriesConfirmed:input.seriesPreference!=='Help me choose',seriesEntitlements:input.seriesPreference==='Help me choose'?old.seriesEntitlements:Array.from(new Set([...old.seriesEntitlements,input.seriesPreference])),developmentProfile,questionnaire:goals,campRecommendations,trainingPlan}))}
 const readiness=()=>{const entry:ReadinessEntry={date:new Date().toISOString().slice(0,10),updatedAt:new Date().toISOString(),source:'Rider manual entry',fatigue:goals.currentFatigue,soreness:'None',motivation:goals.currentMotivation,hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:'Proceed with the planned session; continue monitoring recovery.'};updateAlpha4025(old=>({...old,readinessEntries:[entry,...old.readinessEntries]}))}
 return <section className="offseason-screen"><button type="button" onClick={onBack}>← Team Bus</button><header className="compact-page-header"><p className="eyebrow">RIDER DEVELOPMENT</p><h1>Off-Season Training</h1><p>SEASON → REVIEW → GOALS → PROFILE → CAMPS → PLAN → CALENDAR → RECOVERY</p></header>
 {isAuthenticated&&<article className="dashboard-card owner-preview-banner" role="status"><p className="eyebrow">PREVIEW ACCESS</p><h2>The current season remains active</h2><p>You are previewing the off-season experience before formally ending the current season. This access does not end or archive the season, alter results, complete remaining stages, or change replay history.</p></article>}
 {!hasAccess&&<article className="dashboard-card locked-note"><h2>Complete End Season first</h2><p>Off-season access remains locked for rider accounts until the official season handoff.</p></article>}
 {hasAccess&&<>

  {todayAssignment&&todayWorkout&&<section className="dashboard-card adaptive-today"><p className="eyebrow">TODAY’S TRAINING · EVIDENCE-BASED RECOMMENDATION</p><h2>{todayWorkout.title}</h2><p><strong>Purpose:</strong> {todayWorkout.purpose}</p><p><strong>Duration:</strong> {todayWorkout.durationMinutes} minutes · <strong>Individual difficulty:</strong> {difficulty?.label}</p><p>{difficulty?.explanation}</p><p><strong>Jean:</strong> {jeanAdaptiveExplanation(todayWorkout,todayWorkout,[difficulty?.explanation??'Insufficient workout evidence'],[latest?'Outdoor power comparability':'Current readiness entry and outdoor power comparability'],'The remainder of the week stays as planned; no bonus work is added.')}</p><button type="button" className="primary-cta" onClick={()=>onStartWorkout(todayWorkout.id,todayAssignment.id)}>Start Ride — Open Workout Briefing</button><details><summary>Curated alternatives</summary><div className="adaptive-alternatives">{Array.from(new Set([...todayWorkout.alternatives.easier,...todayWorkout.alternatives.shorter,...todayWorkout.alternatives.recovery])).map(id=>{const w=workoutById(id);return w&&<button type="button" key={id} onClick={()=>selectAlternative(id)}><strong>{w.title}</strong><small>Preserves {w.discipline.toLowerCase()} purpose · {w.durationMinutes} min · projected schedule recalculates without duplication</small></button>})}</div></details><dl className="workout-structure"><div><dt>Structure</dt><dd>{todayWorkout.repetitions} × {todayWorkout.workIntervalMinutes} min work / {todayWorkout.recoveryIntervalMinutes} min recovery</dd></div><div><dt>Targets</dt><dd>{career.rider.ftp&&todayWorkout.ftpRange?`${Math.round(career.rider.ftp*todayWorkout.ftpRange[0])}–${Math.round(career.rider.ftp*todayWorkout.ftpRange[1])} W indoors`:`${todayWorkout.unknownFtpEffort}`}; {todayWorkout.cadence[0]}–{todayWorkout.cadence[1]} rpm</dd></div><div><dt>Demand / recovery cost</dt><dd>{todayWorkout.demand}/5 · {todayWorkout.recoveryCost}/5</dd></div><div><dt>Fueling</dt><dd>{todayWorkout.fueling}</dd></div></dl></section>}
  <section><h2>Development Profile</h2><p>Levels are bounded 1.0–10.0 RtR workout-progression measures, not physiological or fitness scores.</p><div className="camp-grid">{adaptive.zoneDevelopment.map(z=><article className="dashboard-card" key={z.zone}><h3>{z.zone}</h3><p><strong>{z.level?.toFixed(1)??'Insufficient evidence'}</strong> · {z.confidence} confidence · {z.direction}</p><p>{z.evidenceSource}</p><small>Last evidence: {z.lastEvidenceDate??'Unavailable'} · Successful: {z.successfulWorkoutIds.length} · Struggled/incomplete: {z.struggledWorkoutIds.length}</small></article>)}</div></section>
  {adaptive.fourWeekPreview&&<section className="dashboard-card"><p className="eyebrow">FOUR-WEEK PREVIEW · PROJECTED SCHEDULE EFFECT</p><h2>No fitness or FTP forecast</h2><div className="metric-grid">{Object.entries({'Ride minutes':adaptive.fourWeekPreview.totalRideMinutes,'Strength':adaptive.fourWeekPreview.strengthSessions,'Quality':adaptive.fourWeekPreview.qualitySessions,'Endurance':adaptive.fourWeekPreview.enduranceSessions,'Outdoor':adaptive.fourWeekPreview.outdoorSessions,'Recovery days':adaptive.fourWeekPreview.recoveryDays,'High demand':adaptive.fourWeekPreview.highDemandDays}).map(([k,v])=><span key={k}><small>{k}</small><strong>{v}</strong></span>)}</div><p><strong>Conflicts:</strong> {adaptive.fourWeekPreview.conflicts.join(' · ')||'No material schedule conflicts detected.'}</p></section>}
  <section className="dashboard-card"><p className="eyebrow">ADAPTATION HISTORY</p><h2>Original assignments remain reviewable</h2>{adaptive.adaptations.length?adaptive.adaptations.map(a=><article key={a.id}><strong>{a.date}: {workoutById(a.originalWorkoutId)?.title} → {workoutById(a.replacementWorkoutId)?.title}</strong><p>{a.explanation}</p><small>{a.trigger} · {a.decision}</small></article>):<p>No adaptations recorded.</p>}</section>
  <article className="dashboard-card"><p className="eyebrow">JEAN’S SEASON REVIEW</p><h2>Available evidence only</h2>{review&&<><div className="metric-grid">{Object.entries(review.availableMetrics).map(([k,v])=><span key={k}><small>{k}</small><strong>{v}</strong></span>)}</div><p><strong>Unavailable:</strong> {review.unavailableMetrics.join(', ')||'None'}</p><p>Our emphasis: {review.offSeasonEmphasis.join(' · ')}</p>{previewReview&&<small>Preview summary only. The formal season review is generated by End Season.</small>}</>}</article>
  <article className="dashboard-card form-stack"><p className="eyebrow">RIDER INTAKE & SERIES</p><h2>Transparent development profile</h2><div className="responsive-form"><label>Rider category<select value={input.category} onChange={e=>setInput({...input,category:e.target.value as PersonalizationInput['category']})}><option>Male</option><option>Female</option><option>Prefer not to answer</option></select></label><label>Series pathway<select value={input.seriesPreference} onChange={e=>setInput({...input,seriesPreference:e.target.value as PersonalizationInput['seriesPreference']})}><option>Standard RtR</option><option>RtR Femmes</option><option>Intro to Cycling</option><option>Help me choose</option></select></label><label>Weekly days<input type="number" min="1" max="7" value={input.weeklyDays} onChange={e=>setInput({...input,weeklyDays:Number(e.target.value)})}/></label><label>Weekly minutes<input type="number" min="90" value={input.weeklyMinutes} onChange={e=>setInput({...input,weeklyMinutes:Number(e.target.value)})}/></label><label>Primary goal<input value={input.primaryGoal} onChange={e=>setInput({...input,primaryGoal:e.target.value})}/></label><label>Secondary goal<input value={input.secondaryGoal} onChange={e=>setInput({...input,secondaryGoal:e.target.value})}/></label></div><p><strong>Recommended series:</strong> {input.category==='Male'?'Standard RtR':input.category==='Female'?'RtR Femmes':'Choose a pathway explicitly'}<br/><small>Based on your rider profile and selected category. You may continue or choose another available pathway.</small></p></article>
  <article className="dashboard-card form-stack"><p className="eyebrow">OFF-SEASON GOALS</p><h2>Questionnaire</h2><div className="responsive-form"><label>Next-season objective<input value={goals.nextSeasonObjective} onChange={e=>setGoals({...goals,nextSeasonObjective:e.target.value})}/></label><label>Target event<input value={goals.targetEvent} onChange={e=>setGoals({...goals,targetEvent:e.target.value})}/></label><label>Desired start date<input type="date" value={goals.desiredStartDate} onChange={e=>setGoals({...goals,desiredStartDate:e.target.value})}/></label><label>Progression<select value={goals.progression} onChange={e=>setGoals({...goals,progression:e.target.value as GoalsQuestionnaire['progression']})}><option>Conservative</option><option>Balanced</option><option>Ambitious</option></select></label><label>Current fatigue<select value={goals.currentFatigue} onChange={e=>setGoals({...goals,currentFatigue:e.target.value as GoalsQuestionnaire['currentFatigue']})}><option>Low</option><option>Moderate</option><option>High</option></select></label><label>Indoor/outdoor preference<select value={goals.indoorOutdoorPreference} onChange={e=>setGoals({...goals,indoorOutdoorPreference:e.target.value as GoalsQuestionnaire['indoorOutdoorPreference']})}><option>Indoor</option><option>Outdoor</option><option>Balanced</option></select></label></div><button type="button" onClick={build}>Approve profile and generate one plan</button></article>
  {state.developmentProfile&&<article className="dashboard-card"><p className="eyebrow">RIDER-DEVELOPMENT PROFILE</p><h2>{career.rider.name}</h2><h3>{state.developmentProfile.archetype}</h3><p>FTP: {career.rider.ftp===null?'Unavailable — effort targets only':`${career.rider.ftp} W`}</p><p><strong>Priorities:</strong> {state.developmentProfile.developmentPriorities.join(' · ')}</p><p>{state.developmentProfile.explanation}</p></article>}
  {state.campRecommendations.length>0&&<section><h2>Recommended training camps</h2><div className="camp-grid">{state.campRecommendations.map(c=><article className="dashboard-card" key={c.id}><p className="eyebrow">{c.durationWeeks} WEEK BLOCK</p><h3>{c.name}</h3><p>{c.why}</p><p><strong>Develops:</strong> {c.develops.join(', ')}</p><p><strong>Entry:</strong> {c.entryRequirements.join(', ')}</p><p><strong>Complete when:</strong> {c.completionCriteria.join(', ')}</p></article>)}</div></section>}
  {state.trainingPlan&&<section><h2>Personalized 12-week calendar</h2><p>{state.trainingPlan.explanation}</p><div className="plan-weeks">{state.trainingPlan.weeks.map(w=><details className="dashboard-card" open={w.number===1} key={w.number}><summary><strong>Week {w.number}</strong> · {w.camp}{w.recoveryWeek?' · REDUCED':''}</summary><p>{w.focus}</p>{w.assignments.map(a=><article className="plan-day" key={a.id}><header><strong>{a.day} · {a.title}</strong><small>{a.durationMinutes} min · {a.environment} · {a.effort}</small></header><p>{a.purpose}</p><p>{a.primary}{a.powerTarget&&` · ${a.powerTarget.minimum}–${a.powerTarget.maximum} W`}</p><details><summary>Alternatives & fueling</summary><p><b>Short:</b> {a.shortened}</p><p><b>Indoor:</b> {a.indoorAlternative}</p><p><b>Outdoor:</b> {a.outdoorAlternative}</p><p><b>Recovery:</b> {a.recoveryAlternative}</p><p><b>Fuel:</b> {a.fueling.carbsPerHour===null?'No hourly carbohydrate target required.':`${a.fueling.carbsPerHour} g carbohydrate/hour`} {a.fueling.recoveryPriority}</p></details></article>)}</details>)}</div></section>}
  <article className="dashboard-card readiness-card authoritative-readiness"><p className="eyebrow">READINESS</p><h2>{ready.status}</h2><p role="status">{ready.adjustment}</p>{latest&&<><p><strong>Source:</strong> {latest.source} · <strong>Data date:</strong> {latest.date} · <strong>Updated:</strong> {new Date(latest.updatedAt).toLocaleString()}</p><div className="mini-metrics"><span><strong>{latest.sleepHours??'Unavailable'}</strong> Sleep hours</span><span><strong>{latest.externalRecoveryScore??'Unavailable'}</strong> External recovery</span><span><strong>{latest.recentStrain??'Unavailable'}</strong> Recent strain</span><span><strong>{latest.fatigue}</strong> Fatigue</span><span><strong>{latest.soreness}</strong> Soreness</span><span><strong>{latest.motivation}</strong> Motivation</span></div></>}<small>No composite physiological score is calculated.</small><button type="button" onClick={readiness}>Update today’s health</button></article>
  {state.outdoorActivities.map(a=><article className="dashboard-card" key={a.id}><p className="eyebrow">OUTDOOR ACTIVITY · {a.source}</p><h2>{a.date} baseline</h2><div className="metric-grid"><span><small>DISTANCE</small><strong>{a.distanceMiles} mi</strong></span><span><small>DURATION</small><strong>1:31:39</strong></span><span><small>AVG SPEED</small><strong>{a.averageSpeedMph} mph</strong></span><span><small>ELEVATION</small><strong>{a.elevationFeet} ft</strong></span><span><small>POWER</small><strong>Unavailable</strong></span></div><p>{a.elevationSource}. Outdoor watts were not estimated.</p></article>)}
 </>}</section>
}
