import { useCareer } from '../state/CareerContext'
import { raceStages } from '../data/raceStages'
import { vuelta2026 } from '../data/professionalRaces'

const dateLabel=(value:string)=>new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'))
export default function RaceOverviewScreen({library,actionable,onBack,onOpenStage}:{library:string;actionable:number;onBack:()=>void;onOpenStage:(stage:number)=>void}){
 const {career}=useCareer(); const isVuelta=library==='vuelta-2026'; const completed=isVuelta?career.races.vuelta.completedStages:career.races.tour.completedStages
 const race=isVuelta?vuelta2026:{id:'tour-2026',name:'Tour de France',shortName:'Le Tour',season:2026,startDate:'2026-07-04',endDate:'2026-07-26',identity:{raceAccentColor:'#f2d13d'},routeMap:{alt:'Simplified Tour de France route overview',points:[{x:15,y:75},{x:35,y:42},{x:60,y:62},{x:83,y:25}]},restDays:[{afterStage:9,label:'Rest Day 1'},{afterStage:15,label:'Rest Day 2'}],stages:raceStages.map((s,i)=>({number:s.number,date:`2026-07-${String(3+i).padStart(2,'0')}`,start:s.route.split('→')[0].trim(),finish:s.route.split('→')[1]?.trim()??'',classification:s.theme,officialDistanceKm:s.distanceKm,officialAscentM:s.elevationM,workoutReady:true}))}
 return <section className="race-overview" style={{'--race-accent':race.identity.raceAccentColor} as React.CSSProperties}>
  <button onClick={onBack}>← Back to Season</button><header className="race-hub-header"><p className="eyebrow">TEAM LORIOT • {race.season}</p><h1>{race.name}</h1><p>{dateLabel(race.startDate)} – {dateLabel(race.endDate)} • {race.stages.length} stages</p><strong>{completed.length} / {race.stages.length} COMPLETE</strong></header>
  <section className="dashboard-card route-map-card" aria-label={race.routeMap.alt}><p className="eyebrow">RACE ROUTE</p><svg viewBox="0 0 100 100" role="img" aria-label={race.routeMap.alt}><polyline points={race.routeMap.points?.map(p=>`${p.x},${p.y}`).join(' ')} /><circle cx={race.routeMap.points?.[0].x} cy={race.routeMap.points?.[0].y} r="3"/><circle cx={race.routeMap.points?.at(-1)?.x} cy={race.routeMap.points?.at(-1)?.y} r="3"/></svg><small>Offline simplified route representation</small></section>
  <section className="dashboard-card stage-index"><div className="section-title-row"><div><p className="eyebrow">ROADBOOK</p><h2>Stage index</h2></div><small>Profiles live in each dossier</small></div>{race.stages.map(stage=><div key={stage.number}><button className={`stage-index-row${stage.number===actionable?' actionable':''}`} onClick={()=>onOpenStage(stage.number)} aria-label={`Open ${race.name} 2026 Stage ${stage.number}: ${stage.start} to ${stage.finish}, ${stage.officialDistanceKm} kilometres, ${stage.classification} stage`}><span className="stage-number">STAGE {stage.number}</span><span className="stage-route"><strong>{stage.start} → {stage.finish}</strong><small>{dateLabel(stage.date)} • {stage.classification}</small></span><span className="stage-distance"><strong>{stage.officialDistanceKm} km</strong><small>{stage.officialAscentM.toLocaleString()} m D+</small></span><span className="stage-status">{completed.includes(stage.number)?'COMPLETED':stage.number===actionable?'CURRENT':stage.workoutReady?'UP NEXT':'PROFILE VERIFIED'}<small>STAGE DETAILS →</small></span></button>{race.restDays.find(day=>day.afterStage===stage.number)&&<div className="rest-day-row">🛌 {race.restDays.find(day=>day.afterStage===stage.number)?.label}</div>}</div>)}</section>
 </section>
}
