import { useCareer } from '../state/CareerContext'
import { tour2026, vuelta2026 } from '../data/professionalRaces'

const dateLabel=(value:string)=>new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(value+'T00:00:00Z'))
export default function RaceOverviewScreen({library,actionable,onBack,onOpenStage}:{library:string;actionable:number;onBack:()=>void;onOpenStage:(stage:number)=>void}){
 const {career}=useCareer(); const isVuelta=library==='vuelta-2026'; const completed=isVuelta?career.races.vuelta.completedStages:career.races.tour.completedStages
 const race=isVuelta?vuelta2026:tour2026
 return <section className="race-overview" style={{'--race-accent':race.identity.raceAccentColor} as React.CSSProperties}>
  <button onClick={onBack}>← Back to Season</button><header className="race-hub-header race-hero-title"><p className="eyebrow">TEAM LORIOT • {race.season}</p><h1>{race.name}</h1><p>{dateLabel(race.startDate)} – {dateLabel(race.endDate)} • {race.stages.length} stages</p><strong>{completed.length} / {race.stages.length} COMPLETE</strong></header>
  <section className="dashboard-card route-map-card" aria-label={race.routeMap.alt}><p className="eyebrow">{race.routeMap.verified?'RACE ROUTE':'ROUTE SCHEMATIC'}</p><svg viewBox="0 0 100 100" role="img" aria-label={race.routeMap.alt}><polyline points={race.routeMap.points?.map(p=>`${p.x},${p.y}`).join(' ')} /><circle cx={race.routeMap.points?.[0].x} cy={race.routeMap.points?.[0].y} r="3"/><circle cx={race.routeMap.points?.at(-1)?.x} cy={race.routeMap.points?.at(-1)?.y} r="3"/></svg>{!race.routeMap.verified&&<small>Simplified course representation</small>}</section>
  <section className="dashboard-card stage-index"><div className="section-title-row"><div><p className="eyebrow">ROADBOOK</p><h2>Stage index</h2></div><small>Profiles live in each dossier</small></div>{race.stages.map(stage=>{const rest=race.restDays.find(day=>day.afterStage===stage.number);return <div className="stage-index-entry" key={stage.number}><button className={`stage-index-row${stage.number===actionable?' actionable':''}`} onClick={()=>onOpenStage(stage.number)} aria-label={`Open ${race.name} 2026 Stage ${stage.number}: ${stage.start} to ${stage.finish}, ${stage.officialDistanceKm} kilometres, ${stage.classification} stage`}><span className="stage-number">STAGE {stage.number}</span><span className="stage-route"><strong>{stage.start} → {stage.finish}</strong><small>{dateLabel(stage.date)} • {stage.classification}</small></span><span className="stage-distance"><strong>{stage.officialDistanceKm} km</strong><small>{stage.officialAscentM.toLocaleString()} m D+</small></span><span className="stage-status"><strong>{completed.includes(stage.number)?'COMPLETED':stage.number===actionable?'CURRENT':stage.workoutReady?'UP NEXT':'OFFICIAL PROFILE'}</strong><small>STAGE DETAILS →</small></span></button>{rest&&<article className="rest-day-row" aria-label={rest.label}><strong>{rest.label.split(' · ')[0]}</strong>{rest.label.includes(' · ')&&<span>{rest.label.split(' · ')[1]}</span>}<small>{dateLabel(rest.date)}</small></article>}</div>})}</section>
 </section>
}
