import { createRoadModel } from '../engine/roadModel'
import { raceIdentities } from '../data/raceLibrary'
import { raceStages } from '../data/raceStages'
import { vuelta2026, toRaceStage } from '../data/professionalRaces'
export default function StageDetailScreen({library,stageNumber,onBack,onBriefing}:{library:string;stageNumber:number;onBack:()=>void;onBriefing:()=>void}){
 const isVuelta=library==='vuelta-2026'; const professional=isVuelta?vuelta2026.stages.find(s=>s.number===stageNumber):undefined; const stage=professional?toRaceStage(vuelta2026,professional):raceStages.find(s=>s.number===stageNumber)??raceStages[0]
 const [start,finish]=stage.route.split('→').map(v=>v.trim()); const model=createRoadModel(stage.number,stage.segments.length?stage.segments:[{name:'Course',type:'Course',zone:'-',power:'-',cadence:'-',resistance:'-',routeKm:0,icon:'🚴',sec:1800,description:'Course',objective:'Course',secondaryObjective:'Course',terrainLabel:'Course'}],stage.distanceKm,raceIdentities[isVuelta?'vuelta-2026':'tour-2026'],stage.profilePoints,stage.courseMarkers)
 const date=professional?.date; const map=professional?.stageMap
 return <section className="stage-detail" style={{'--race-accent':isVuelta?'#d62f38':'#f2d13d'} as React.CSSProperties}><button onClick={onBack}>← Back to Race</button><header className="race-hub-header"><p className="eyebrow">TEAM LORIOT • {isVuelta?'LA VUELTA':'TOUR DE FRANCE'}</p><h1>Stage {stage.number}</h1><h2>{start} → {finish}</h2></header>
 <section className="stage-facts dashboard-card"><span><small>DATE</small><strong>{date??'2026 Tour'}</strong></span><span><small>TYPE</small><strong>{stage.theme}</strong></span><span><small>DISTANCE</small><strong>{stage.distanceKm} km</strong></span><span><small>ASCENT</small><strong>{stage.elevationM.toLocaleString()} m</strong></span><span><small>INDOOR</small><strong>{professional?.indoorDurationMinutes?`${professional.indoorDurationMinutes} min`:'In preparation'}</strong></span></section>
 <section className="dashboard-card"><p className="eyebrow">TODAY’S MISSION</p><p>{stage.objective}</p></section>
 <section className="dashboard-card route-map-card" aria-label={map?.alt??`Stage ${stage.number} route map`}><p className="eyebrow">ROUTE MAP</p>{map?<svg viewBox="0 0 100 100" role="img" aria-label={map.alt}><polyline points={map.points?.map(p=>`${p.x},${p.y}`).join(' ')}/></svg>:<div className="map-unavailable">Route map audit in progress</div>}</section>
 <section className="dashboard-card dossier-profile"><div className="section-title-row"><div><p className="eyebrow">VERIFIED COURSE</p><h2>Elevation profile</h2></div><strong>{stage.profileVerified?'PROFILE VERIFIED':'AUDIT PENDING'}</strong></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Elevation profile for Stage ${stage.number}`}><polygon points={`0,100 ${model.profilePoints.join(' ')} 100,100`}/><polyline points={model.profilePoints.join(' ')}/></svg><div className="marker-summary" aria-label="Course markers"><span>START</span>{stage.courseMarkers?.map((m,i)=><span key={i}>{m.label??'TT'}</span>)}<span>FINISH</span></div></section>
 <section className="dashboard-card"><p className="eyebrow">COURSE NOTES</p><p>{stage.theme} • Official profile geometry is shared with the authoritative cockpit road model.</p><small>Source: {stage.profileSource}. Updated {stage.profileUpdatedAt}.</small></section>
 <button className="primary-cta stage-detail-cta" disabled={!stage.workoutReady&&isVuelta} onClick={onBriefing} aria-label={`Open Race Briefing for Stage ${stage.number}`}>{stage.workoutReady||!isVuelta?'OPEN RACE BRIEFING →':'WORKOUT IN PREPARATION'}</button>
 </section>
}
