import { createRoadModel } from '../engine/roadModel'
import { raceIdentities } from '../data/raceLibrary'
import { raceStages } from '../data/raceStages'
import { tour2026, vuelta2026, toRaceStage } from '../data/professionalRaces'
const humanDate=(date:string)=>new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T00:00:00Z`)).toUpperCase()
export default function StageDetailScreen({library,stageNumber,onBack,onBriefing}:{library:string;stageNumber:number;onBack:()=>void;onBriefing:()=>void}){
 const isVuelta=library==='vuelta-2026'; const race=isVuelta?vuelta2026:tour2026; const professional=race.stages.find(s=>s.number===stageNumber); const stage=professional?toRaceStage(race,professional):raceStages.find(s=>s.number===stageNumber)??raceStages[0]
 const [start,finish]=stage.route.split('→').map(v=>v.trim()); const model=createRoadModel(stage.number,stage.segments.length?stage.segments:[{name:'Course',type:'Course',zone:'-',power:'-',cadence:'-',resistance:'-',routeKm:0,icon:'🚴',sec:1800,description:'Course',objective:'Course',secondaryObjective:'Course',terrainLabel:'Course'}],stage.distanceKm,raceIdentities[isVuelta?'vuelta-2026':'tour-2026'],stage.profilePoints,stage.officialCourseMarkers,stage.raceId)
 const date=professional?.date; const map=professional?.stageMap
 return <section className="stage-detail" style={{'--race-accent':isVuelta?'#d62f38':'#f2d13d'} as React.CSSProperties}><button onClick={onBack}>← Back to Race</button><header className="race-hub-header race-hero-title"><p className="eyebrow">TEAM LORIOT • {isVuelta?'LA VUELTA':'TOUR DE FRANCE'}</p><h1>Stage {stage.number}</h1><h2>{start} → {finish}</h2></header>
 <section className="stage-facts dashboard-card">{date&&<span><small>DATE</small><strong>{humanDate(date)}</strong></span>}<span><small>TYPE</small><strong>{stage.theme}</strong></span><span><small>DISTANCE</small><strong>{stage.distanceKm} km</strong></span>{stage.verification?.ascent&&<span><small>ASCENT</small><strong>{stage.elevationM.toLocaleString()} m</strong></span>}<span><small>AUTHORED BASE</small><strong>{professional?.indoorDurationMinutes?`${professional.indoorDurationMinutes} min`:'In preparation'}</strong></span></section>
 <section className="dashboard-card mission-card"><p className="eyebrow">TODAY’S MISSION</p><p>{stage.objective}</p></section>
 <section className="dashboard-card route-map-card" aria-label={map?.alt??`Stage ${stage.number} route map`}><p className="eyebrow">{map?.verified?'ROUTE MAP':'ROUTE SCHEMATIC'}</p>{map?<><svg viewBox="0 0 100 100" role="img" aria-label={map.alt}><polyline points={map.points?.map(p=>`${p.x},${p.y}`).join(' ')}/></svg>{!map.verified&&<small>Simplified course representation</small>}</>:<div className="map-unavailable">Route map audit in progress</div>}</section>
 <section className="dashboard-card dossier-profile"><div className="section-title-row"><div><span className="official-profile-badge">{stage.profileVerified?'OFFICIAL COURSE PROFILE':'COURSE AUDIT PENDING'}</span><h2>Elevation profile</h2></div></div><svg viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label={`Elevation profile for Stage ${stage.number}`}><polygon points={`0,100 ${model.profilePoints.join(' ')} 100,100`}/><polyline points={model.profilePoints.join(' ')}/></svg><div className="marker-summary" aria-label="Course markers"><span>START</span>{model.markers.map(marker=><span key={marker.key}>{marker.label}</span>)}</div></section>
 <details className="dashboard-card course-details"><summary>Course details</summary><dl><dt>Profile</dt><dd>{stage.profileVerified?'Verified official course profile':'Verification pending'}</dd><dt>Source</dt><dd>{stage.profileSource}</dd><dt>Stage type</dt><dd>{stage.theme}</dd><dt>Course distance</dt><dd>{stage.distanceKm} km</dd><dt>Official course markers</dt><dd>{model.markers.length} verified</dd>{stage.verification?.ascent&&<><dt>Verified ascent</dt><dd>{stage.elevationM.toLocaleString()} m</dd></>}<dt>Route schematic</dt><dd>{map?.verified?map.source:'Simplified course representation; not verified route geometry'}</dd></dl></details>
 <button className="primary-cta stage-detail-cta" disabled={!stage.workoutReady&&isVuelta} onClick={onBriefing} aria-label={`Open Race Briefing for Stage ${stage.number}`}>{stage.workoutReady||!isVuelta?'OPEN RACE BRIEFING →':'WORKOUT IN PREPARATION'}</button>
 </section>
}
