import { useMemo } from 'react'
import { getRaceStage } from '../data/raceStages'
import { createCoachBriefing } from '../services/coachEngine'
import { useCareer } from '../state/CareerContext'
import { useAuth } from '../state/AuthContext.tsx'
import { introReadiness, OUTDOOR_READINESS_ITEMS } from '../engine/introCycling.ts'
import { authoritativeReadinessEntry, currentLocalDate, projectReadiness, type ReadinessPhase } from '../engine/alpha4025.ts'

type Props = { onContinue: () => void; onStartIntro:(workoutId:string)=>void; onOpenFemmes:()=>void; onOpenOffSeason:()=>void; onOpenHealth: () => void; onOpenProfile: () => void; onOpenSettings: () => void }

export default function TeamHQScreen({ onContinue,onStartIntro,onOpenFemmes,onOpenOffSeason, onOpenHealth, onOpenProfile, onOpenSettings }: Props) {
  const { career, restartOnboarding, requestNextProgram,toggleOutdoorChecklist } = useCareer()
  const {account,isAuthenticated,signOut,canAccess,requestAccess,pendingAccounts,approve}=useAuth()
  const isOwner=account?.role==='owner',approvals=isOwner?pendingAccounts():[]
  const showFemmes=career.alpha4025.seriesPreference==='RtR Femmes'||(!isOwner&&canAccess('rtr-femmes'))
  const introOnly=career.introCycling.selected&&!canAccess('rtr-standard')
  const coach = useMemo(() => createCoachBriefing(career, getRaceStage(career.season.currentStage)), [career])
  const readinessPhase:ReadinessPhase=career.alpha4025.offSeasonUnlocked?'OFF_SEASON':introOnly?'INTRO':career.season.active&&career.season.closure.status==='ACTIVE'?'RACING':'TRAINING'
  const readinessEntry=authoritativeReadinessEntry(career.alpha4025.readinessEntries,career.health)
  const localDate=currentLocalDate()
  const readiness=projectReadiness(readinessEntry,localDate,readinessPhase)
  return <section className={`hq-screen hq-${coach.phase}`}>
    <header className="hq-topbar"><div><p className="eyebrow">TEAM LORIOT • RIDER #{career.rider.number}</p><h1>{coach.greeting}, {career.rider.name.split(' ')[0]}</h1><p className="subtitle">{career.rider.archetype} • {career.rider.team}</p></div>
      <div className="rider-badge"><span>{career.rider.archetype}</span><strong>{career.rider.ftp===null?'FTP NOT SET':`FTP ${career.rider.ftp} W`}</strong><button type="button" onClick={onOpenProfile}>Edit rider</button><button type="button" className="text-button" onClick={onOpenSettings}>Settings</button><button type="button" className="text-button" onClick={restartOnboarding}>Replay intake</button><button type="button" className="text-button" onClick={signOut}>Sign out {account?.displayName}</button></div>
    </header>
    {career.introCycling.selected&&career.introCycling.plan&&(()=>{const plan=career.introCycling.plan,completed=career.introCycling.completedRideIds.length,nextIndex=plan.rides.findIndex(ride=>!career.introCycling.completedRideIds.includes(ride.id)),next=nextIndex>=0?plan.rides[nextIndex]:undefined,readiness=introReadiness(completed,plan.rides.length,career.introCycling.outdoorChecklistIds.length),checklistComplete=career.introCycling.outdoorChecklistIds.length===OUTDOOR_READINESS_ITEMS.length,progress=Math.round((completed/Math.max(1,plan.rides.length))*100);return <section className="dashboard-card intro-dashboard intro-pathway" aria-label="Intro to Cycling progress">
      <header className="intro-pathway-header"><div><p className="eyebrow">INTRO TO CYCLING</p><h2>{next?`Lesson ${nextIndex+1}: ${next.title}`:'Ride foundations complete'}</h2><p>{next?next.focus:'Your indoor foundation rides are complete. Finish outdoor readiness when you are ready to progress.'}</p></div><div className="intro-progress-badge"><strong>{progress}%</strong><span>{completed}/{plan.rides.length} rides</span></div></header>
      <progress value={completed} max={plan.rides.length}/>
      <details className="intro-curriculum"><summary>View all {plan.rides.length} lessons</summary><ol className="intro-lesson-roadmap">{plan.rides.map((ride,index)=>{const done=career.introCycling.completedRideIds.includes(ride.id),active=ride.id===next?.id;return <li className={done?'is-complete':active?'is-next':'is-locked'} key={ride.id}><span>{done?'✓':index+1}</span><div><strong>{ride.title}</strong><small>{ride.durationMinutes} min · {done?'Complete':active?'Next lesson':'Upcoming'}</small></div></li>})}</ol></details>
      {next&&<article className="intro-next-lesson"><div><p className="eyebrow">NEXT RECOMMENDED</p><h3>{next.title}</h3><p>Scheduled day {next.scheduledDay} · {next.durationMinutes} minutes</p></div><button type="button" className="primary-cta" onClick={()=>onStartIntro(next.id)}>Start lesson</button></article>}
      <div className="intro-skill-strip"><span><strong>{plan.cadenceComplexity==='FOUNDATION'?'FOUNDATION':'PROGRESSIVE'}</strong>Cadence</span><span><strong>{plan.deliveryMode}</strong>Ride mode</span><span><strong>{plan.recoveryEveryRides}</strong>Rides / recovery</span><span><strong>{career.introCycling.outdoorChecklistIds.length}/{OUTDOOR_READINESS_ITEMS.length}</strong>Outdoor skills</span></div>
      {completed>=plan.outdoorChecklistStartsAfterRide&&<details className="intro-readiness-panel" open={completed>=plan.rides.length&&!checklistComplete}><summary>Outdoor Ride Readiness · {career.introCycling.outdoorChecklistIds.length}/{OUTDOOR_READINESS_ITEMS.length}</summary><fieldset className="outdoor-checklist">{OUTDOOR_READINESS_ITEMS.map(([id,label])=><label key={id}><input type="checkbox" checked={career.introCycling.outdoorChecklistIds.includes(id)} onChange={()=>toggleOutdoorChecklist(id)}/>{label}</label>)}</fieldset><small>Preparation is not certification. Practice in a safe place and use a qualified or experienced supervisor for a first outdoor ride.</small></details>}
      <details className="intro-progression"><summary>Progression and next program</summary><footer className="intro-graduation"><div><p className="eyebrow">PROGRESSION</p><strong>{readiness.advancedProgramReady?'Ready for next-program review':readiness.introComplete?'Finish outdoor readiness':'Complete the lesson pathway'}</strong><small>Standard RtR and RtR Femmes remain rider-selected pathways; outdoor group certification is not provided by RtR.</small></div><label>Next program<select value={career.introCycling.requestedNextProgram??''} onChange={event=>{if(!event.target.value)return;const request=event.target.value as 'Outdoor Ride Readiness'|'RtR Femmes'|'Standard RtR';requestNextProgram(request);requestAccess(request==='RtR Femmes'?'rtr-femmes':request==='Standard RtR'?'rtr-standard':'outdoor-readiness')}}><option value="">Choose…</option><option>Outdoor Ride Readiness</option><option>RtR Femmes</option><option>Standard RtR</option></select></label></footer></details>
      {career.introCycling.requestedNextProgram&&<small>Requested: {career.introCycling.requestedNextProgram}. Access begins after readiness review or local-development owner approval.</small>}{canAccess('rtr-femmes')&&<strong>RtR Femmes unlocked for this account.</strong>}
    </section>})()}
    {!career.introCycling.selected&&career.rider.ftp===null&&<article className="dashboard-card ftp-setup-card"><p className="eyebrow">FTP SETUP</p><h2>Establish your RtR FTP</h2><p>You can enter a known FTP in Edit Rider, or complete the RtR 20-minute FTP test and enter the test interval average afterward.</p><button type="button" className="primary-cta" onClick={()=>onStartIntro('intro-ftp-test-30')}>Take RtR FTP Test</button></article>}
    {approvals.length>0&&<section className="dashboard-card local-owner-approvals"><h2>Local-development program approvals</h2><p>These approvals apply only to accounts stored in this browser.</p>{approvals.map(rider=><div key={rider.id}><strong>{rider.displayName}</strong>{rider.requestedPrograms.map(program=><button type="button" key={program} onClick={()=>approve(rider.id,program)}>Approve {program}</button>)}</div>)}</section>}
    {showFemmes&&<button type="button" className="secondary-action" onClick={onOpenFemmes}>Open RtR Femmes</button>}
    {isAuthenticated&&<article className="dashboard-card owner-preview-home"><p className="eyebrow">PREVIEW ACCESS</p><h2>Off-Season Training</h2><p>Preview the off-season experience while the current season remains unchanged.</p><button type="button" onClick={onOpenOffSeason}>Open Off-Season Training</button></article>}
    <section className="hq-dashboard-grid home-dashboard"><article className="dashboard-card readiness-dashboard authoritative-readiness"><div className="dashboard-card-header"><span>Readiness</span><small>{readinessEntry.date} · {readinessEntry.source}</small></div><h2>{readiness.status}</h2><p role="status">{readiness.adjustment}</p><div className="mini-metrics"><span><strong>{readinessEntry.sleepHours??'Unavailable'}{readinessEntry.sleepHours?'h':''}</strong> Sleep</span><span><strong>{readinessEntry.externalRecoveryScore===undefined?'Unavailable':`${readinessEntry.externalRecoveryScore}%`}</strong> External recovery</span><span><strong>{readinessEntry.recentStrain??'Unavailable'}</strong> Recent strain</span><span><strong>{readinessEntry.fatigue}</strong> Fatigue</span><span><strong>{readinessEntry.soreness}</strong> Soreness</span><span><strong>{readinessEntry.motivation}</strong> Motivation</span><span><strong>{readinessEntry.hydrationConcern?'Concern':'No concern entered'}</strong> Hydration</span></div><small>Last updated {new Date(readinessEntry.updatedAt).toLocaleString()} · No composite physiological score is calculated.</small><button type="button" className="secondary-action" onClick={onOpenHealth}>Update Health</button></article></section>
    <button type="button" className="primary-cta enter-team-bus" onClick={onContinue}>ENTER TEAM BUS →</button>
  </section>
}
