import { useMemo } from 'react'
import { getRaceStage } from '../data/raceStages'
import { createCoachBriefing } from '../services/coachEngine'
import { useCareer } from '../state/CareerContext'
import { useAuth } from '../state/AuthContext.tsx'
import { introReadiness, OUTDOOR_READINESS_ITEMS } from '../engine/introCycling.ts'

type Props = { onContinue: () => void; onStartIntro:(workoutId:string)=>void; onOpenFemmes:()=>void; onOpenHealth: () => void; onOpenProfile: () => void; onOpenSettings: () => void }

export default function TeamHQScreen({ onContinue,onStartIntro,onOpenFemmes, onOpenHealth, onOpenProfile, onOpenSettings }: Props) {
  const { career, restartOnboarding, requestNextProgram,toggleOutdoorChecklist } = useCareer()
  const {account,signOut,canAccess,requestAccess,pendingAccounts,approve}=useAuth()
  const introOnly=career.introCycling.selected&&!canAccess('rtr-standard')
  const coach = useMemo(() => createCoachBriefing(career, getRaceStage(career.season.currentStage)), [career])
  return <section className={`hq-screen hq-${coach.phase}`}>
    <header className="hq-topbar"><div><p className="eyebrow">TEAM LORIOT • RIDER #{career.rider.number}</p><h1>{coach.greeting}, {career.rider.name.split(' ')[0]}</h1><p className="subtitle">{career.rider.archetype} • {career.rider.team}</p></div>
      <div className="rider-badge"><span>{career.rider.archetype}</span><strong>{career.rider.ftp===null?'FTP NOT SET':`FTP ${career.rider.ftp} W`}</strong><button type="button" onClick={onOpenProfile}>Edit rider</button><button type="button" className="text-button" onClick={onOpenSettings}>Settings</button><button type="button" className="text-button" onClick={restartOnboarding}>Replay intake</button><button type="button" className="text-button" onClick={signOut}>Sign out {account?.displayName}</button></div>
    </header>
    {career.introCycling.selected&&career.introCycling.plan&&(()=>{const plan=career.introCycling.plan,completed=career.introCycling.completedRideIds.length,next=plan.rides.find(ride=>!career.introCycling.completedRideIds.includes(ride.id)),readiness=introReadiness(completed,plan.rides.length,career.introCycling.outdoorChecklistIds.length);return <section className="dashboard-card intro-dashboard" aria-label="Intro to Cycling progress"><div className="dashboard-card-header"><span>Intro to Cycling</span><small>{completed} of {plan.rides.length} rides complete</small></div><progress value={completed} max={plan.rides.length}/><p><strong>Next recommended action:</strong> {next?`${next.title} · ${next.durationMinutes} min`:'Complete Outdoor Ride Readiness checklist'}</p>{next&&<article><h2>{next.title}</h2><p>Scheduled day {next.scheduledDay}. {next.focus}</p><button type="button" onClick={()=>onStartIntro(next.id)}>Start assigned ride</button></article>}<div className="rider-summary"><span>{career.rider.ftp===null?'RPE-BASED TARGETS':`${plan.powerCeilingPercent}% FTP ceiling`}</span><span>{plan.cadenceComplexity} cadence</span><span>{plan.weeklyDays} days/week</span><span>{plan.deliveryMode}</span><span>Recovery every {plan.recoveryEveryRides} rides</span></div>{completed>=plan.outdoorChecklistStartsAfterRide&&<fieldset className="outdoor-checklist"><legend>Outdoor Ride Readiness</legend>{OUTDOOR_READINESS_ITEMS.map(([id,label])=><label key={id}><input type="checkbox" checked={career.introCycling.outdoorChecklistIds.includes(id)} onChange={()=>toggleOutdoorChecklist(id)}/>{label}</label>)}<p>Preparation is not certification. Practice in a safe place and use a qualified or experienced supervisor for a first outdoor ride.</p></fieldset>}<p><strong>Readiness:</strong> Intro to Cycling {readiness.introComplete?'complete':'in progress'} · Indoor program {readiness.indoorProgramReady?'ready':'not ready'} · Outdoor preparation {readiness.outdoorPreparationComplete?'complete':'in progress'} · Advanced program {readiness.advancedProgramReady?'ready for review':'not ready'} · Outdoor group certification: not provided by RtR.</p><label>Request next program<select value={career.introCycling.requestedNextProgram??''} onChange={event=>{if(!event.target.value)return;const request=event.target.value as 'Outdoor Ride Readiness'|'RtR Femmes'|'Standard RtR';requestNextProgram(request);requestAccess(request==='RtR Femmes'?'rtr-femmes':request==='Standard RtR'?'rtr-standard':'outdoor-readiness')}}><option value="">Choose…</option><option>Outdoor Ride Readiness</option><option>RtR Femmes</option><option>Standard RtR</option></select></label>{career.introCycling.requestedNextProgram&&<small>Requested: {career.introCycling.requestedNextProgram}. Access begins after readiness review or local-development owner approval.</small>}{canAccess('rtr-femmes')&&<strong>RtR Femmes unlocked for this account.</strong>}</section>})()}
    {account?.role==='owner'&&<section className="dashboard-card local-owner-approvals"><h2>Local-development program approvals</h2><p>These approvals apply only to accounts stored in this browser.</p>{pendingAccounts().map(rider=><div key={rider.id}><strong>{rider.displayName}</strong>{rider.requestedPrograms.map(program=><button type="button" key={program} onClick={()=>approve(rider.id,program)}>Approve {program}</button>)}</div>)}</section>}
    {canAccess('rtr-femmes')&&<button type="button" className="secondary-action" onClick={onOpenFemmes}>Open RtR Femmes</button>}
    <section className="hq-dashboard-grid home-dashboard"><article className="dashboard-card readiness-dashboard"><div className="dashboard-card-header"><span>Recovery</span><small>{career.health.date}</small></div><div className="readiness-ring" style={{ '--readiness': `${coach.readiness * 3.6}deg` } as React.CSSProperties}><div><strong>{coach.readiness}%</strong><span>{introOnly?(coach.readiness>=65?'Ready for an easy session':'Recovery supports progression'):coach.readinessLabel}</span></div></div><div className="mini-metrics"><span><strong>{career.health.sleepHours}h</strong> Sleep</span><span><strong>{career.health.recoveryScore}%</strong> Recovery</span><span><strong>{career.health.fatigue}%</strong> Fatigue</span></div><button type="button" className="secondary-action" onClick={onOpenHealth}>Update Health</button></article></section>
    <button type="button" className="primary-cta enter-team-bus" onClick={onContinue}>ENTER TEAM BUS →</button>
  </section>
}
