import test from 'node:test'
import assert from 'node:assert/strict'
import { CURATED_OFFSEASON_WORKOUTS, SELECTION_WEIGHTS, assignmentWorkout, buildZoneDevelopment, evaluateDifficulty, fourWeekPreview, halInitialZoneDevelopment, jeanAdaptiveExplanation, outdoorEvidence, readinessSafeguard, replaceWithAlternative, selectCandidate, workoutById } from './adaptiveTraining40251.ts'
import { generatePlan, HAL_BASELINE, HAL_GOALS, HAL_INPUT, projectReadiness } from './alpha4025.ts'
import { migrateCareer } from '../state/careerPersistence.ts'

const fresh=projectReadiness({date:'2026-09-23',updatedAt:'2026-09-23T08:00:00Z',source:'Manual',fatigue:'Low',soreness:'None',motivation:'High',hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:''},'2026-09-23','OFF_SEASON')
test('curated library has complete stable metadata and named ranking weights',()=>{assert.ok(CURATED_OFFSEASON_WORKOUTS.length>=8);assert.equal(new Set(CURATED_OFFSEASON_WORKOUTS.map(w=>w.id)).size,CURATED_OFFSEASON_WORKOUTS.length);for(const w of CURATED_OFFSEASON_WORKOUTS){assert.ok(w.title&&w.purpose&&w.durationMinutes>0&&w.cadence.length===2&&w.alternatives.recovery);assert.ok(w.difficulty>=1&&w.difficulty<=10)}assert.deepEqual(Object.keys(SELECTION_WEIGHTS),['purposeMatch','goalMatch','levelFit','durationFit','environmentFit','phaseFit','recoveryFit','workloadFit','proximityFit','outdoorReplacement'])})
test('zone levels use valid workout evidence and missing zones remain insufficient',()=>{const zones=buildZoneDevelopment([{workoutId:'threshold-4x8',date:'2026-09-22',status:'SUCCESS',source:'Completed RtR workout'},{workoutId:'unknown',date:'2026-09-23',status:'SUCCESS',source:'Unknown'}]);assert.ok(zones.find(z=>z.zone==='Threshold')?.level);assert.equal(zones.find(z=>z.zone==='VO2 Max')?.level,null);assert.equal(zones.find(z=>z.zone==='VO2 Max')?.direction,'Insufficient evidence')})
test('Hal baseline is conservative evidence and never invents outdoor power',()=>{const endurance=halInitialZoneDevelopment().find(z=>z.zone==='Endurance')!;assert.equal(endurance.level,2.5);assert.equal(endurance.confidence,'Low');assert.equal(halInitialZoneDevelopment().find(z=>z.zone==='Threshold')?.level,null);assert.equal(outdoorEvidence(HAL_BASELINE).powerWatts,null);assert.equal(HAL_BASELINE.powerWatts,undefined)})
test('individual difficulty changes deterministically relative to supported level',()=>{const w=workoutById('threshold-4x8')!,base={zone:'Threshold' as const,confidence:'Moderate' as const,lastEvidenceDate:'2026-09-20',evidenceSource:'Workout',successfulWorkoutIds:['x'],struggledWorkoutIds:[],direction:'Stable' as const};assert.equal(evaluateDifficulty('a',w,{...base,level:6},'2026-09-23').label,'On Target');assert.equal(evaluateDifficulty('a',w,{...base,level:4.5},'2026-09-23').label,'Challenging');assert.equal(evaluateDifficulty('a',w,undefined,'2026-09-23').label,'Unknown — insufficient evidence')})
test('successful evidence permits controlled progression while struggle blocks duration and intensity increase',()=>{const development=buildZoneDevelopment([{workoutId:'climbing-sustain-60',date:'2026-09-20',status:'SUCCESS',source:'Completed'}]);const allowed=selectCandidate({purpose:'sustained climbing',goal:'sustained climbing',development,availableMinutes:75,environment:'INDOOR',equipment:['Indoor bike'],recoveryWeek:false,readiness:fresh,previousHighIntensity:false});assert.ok(allowed.selected);const blocked=selectCandidate({purpose:'VO2',goal:'VO2',development,availableMinutes:75,environment:'INDOOR',equipment:['Indoor bike'],recoveryWeek:false,readiness:fresh,previousHighIntensity:false,struggledWorkoutId:'climbing-sustain-60'});assert.ok(blocked.rejected.some(x=>/simultaneous intensity and duration/.test(x.reason)))})
test('stale readiness cannot modify and current recovery safely replaces intensity',()=>{const hard=workoutById('threshold-4x8')!,stale=projectReadiness({date:'2026-09-10',updatedAt:'2026-09-10T08:00:00Z',source:'Manual',fatigue:'High',soreness:'Significant',motivation:'Low',hydrationConcern:true,illnessOrPain:false,recommendedAdjustment:''},'2026-09-23','OFF_SEASON'),current=projectReadiness({date:'2026-09-23',updatedAt:'2026-09-23T08:00:00Z',source:'Manual',fatigue:'High',soreness:'Significant',motivation:'Low',hydrationConcern:true,illnessOrPain:false,recommendedAdjustment:''},'2026-09-23','OFF_SEASON');assert.equal(readinessSafeguard(hard,stale).changed,false);assert.equal(readinessSafeguard(hard,current).workout.id,'recovery-spin-30')})
test('outdoor and curated alternatives replace assignments without bonus workload',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),assignment=plan.weeks[0].assignments[5],before=plan.weeks[0].assignments.length,replacement=workoutById('outdoor-easy-60')!,record={id:'one',date:'2026-09-23',assignmentId:assignment.id,originalWorkoutId:assignmentWorkout(assignment)!.id,replacementWorkoutId:replacement.id,trigger:'Outdoor ride',evidence:['Recorded outdoor duration'],explanation:'Replaced in place; no extra endurance.',decision:'ACCEPTED' as const},changed=replaceWithAlternative(plan,assignment.id,replacement,record);assert.equal(changed.plan.weeks[0].assignments.length,before);assert.equal(changed.plan.weeks[0].assignments[5].status,'REPLACED');assert.equal(workoutById('climbing-sustain-60')!.alternatives.easier.map(workoutById)[0]?.discipline,'Sustained climbing')})
test('moving quality immediately before long ride creates conflict and preview never rewrites history',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),completed=plan.weeks[0].assignments[2];completed.status='COMPLETED';completed.completion={completedAt:'2026-09-23',durationMinutes:45};plan.weeks[0].assignments[4]={...plan.weeks[1].assignments[3],id:'moved-friday'};const snapshot=JSON.stringify(plan),preview=fourWeekPreview(plan,1,'2026-09-23T00:00:00Z');assert.match(preview.conflicts[0],/immediately precedes/);assert.equal(JSON.stringify(plan),snapshot);assert.match(preview.historyFingerprint,/COMPLETED/)})
test('Jean explanation enumerates evidence, unavailable inputs and weekly consequence without race fiction',()=>{const recovery=workoutById('recovery-spin-30')!,text=jeanAdaptiveExplanation(recovery,recovery,['Current readiness entry'],['Outdoor power'],'No other session changes.');assert.match(text,/Originally planned/);assert.match(text,/Evidence used: Current readiness entry/);assert.match(text,/Not available: Outdoor power/);assert.match(text,/Rest of week/);assert.doesNotMatch(text,/attack|peloton|KOM|race|sprint/i)})
test('adaptive persistence migration is additive and idempotent',()=>{const source={schemaVersion:6,rider:{name:'Hal'},alpha4025:{adaptive:{adaptations:[{id:'kept'}],selectedAlternatives:{a:'b'},compatibleUnknown:true}},compatibleUnknown:{kept:true}} as never,first=migrateCareer(source),second=migrateCareer(first);assert.equal(first.alpha4025.adaptive.adaptations[0].id,'kept');assert.equal((first.alpha4025.adaptive as unknown as {compatibleUnknown:boolean}).compatibleUnknown,true);assert.deepEqual(second,first);assert.deepEqual((first as unknown as {compatibleUnknown:unknown}).compatibleUnknown,{kept:true})})
