import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { authoritativeReadinessEntry, currentLocalDate, emptyAlpha4025, ensureHalOffSeasonPlan, generatePlan, HAL_GOALS, HAL_INPUT, planProfileFingerprint, projectReadiness, validatePlanConstraints } from './alpha4025.ts'
import { fourWeekPreview, halInitialZoneDevelopment, workoutById, workoutSections } from './adaptiveTraining40251.ts'
import { getLibraryStage } from '../data/raceLibrary.ts'

test('authoritative Hal snapshot replaces stale unfinished work and preserves completed history',()=>{const stale=generatePlan(HAL_INPUT,HAL_GOALS);stale.profileFingerprint='stale-two-day-profile';stale.profileRevision='stale-two-day-profile';stale.weeks[0].assignments[2].status='COMPLETED';stale.weeks[0].assignments[2].completion={completedAt:'2026-09-23',durationMinutes:45};stale.weeks[1].assignments[2]={...stale.weeks[1].assignments[2],title:'Steady Endurance 45',workoutId:'endurance-steady-45'};const restored=ensureHalOffSeasonPlan({...emptyAlpha4025(),trainingPlan:stale});assert.equal(restored.trainingPlan?.profileFingerprint,planProfileFingerprint(HAL_INPUT,HAL_GOALS));assert.equal(restored.trainingPlan?.weeks[0].assignments[2].status,'COMPLETED');assert.equal(restored.trainingPlan?.weeks[1].assignments[2].title,'Controlled Climbing Tempo');assert.equal(validatePlanConstraints(restored.trainingPlan!,4,240).length,0)})
test('week one is four days and exactly 240 minutes with separated Sunday components',()=>{const week=generatePlan(HAL_INPUT,HAL_GOALS).weeks[0],active=week.assignments.filter(a=>a.durationMinutes>0);assert.deepEqual(active.map(a=>[a.day,a.title,a.durationMinutes]),[['Tuesday','Strength A',30],['Wednesday','Controlled Climbing Tempo',45],['Saturday','Outdoor Endurance 90',90],['Sunday','Adaptive Endurance + Strength B',75]]);assert.equal(active.reduce((n,a)=>n+a.durationMinutes,0),240);assert.deepEqual(week.assignments[6].components?.map(x=>x.minutes),[45,30])})
test('September 23 calendar, briefing and cockpit resolve one time-based prescription',()=>{const assignment=generatePlan(HAL_INPUT,HAL_GOALS).weeks[0].assignments.find(a=>a.date==='2026-09-23')!,workout=workoutById(assignment.workoutId!)!,stage=getLibraryStage('training',0,assignment.workoutId)!;assert.equal(currentLocalDate(new Date(2026,8,23,23,30)),'2026-09-23');assert.equal(assignment.title,workout.title);assert.equal(stage.id,assignment.workoutId);assert.equal(stage.trainingMode,'TIME_BASED');assert.notEqual(stage.distanceKm,45);assert.deepEqual(workoutSections(workout).map(x=>[x.title,x.durationSeconds]),[['Progressive warm-up',270],['Controlled Climbing Tempo · Work 1',480],['Recovery 1',240],['Controlled Climbing Tempo · Work 2',480],['Recovery 2',240],['Controlled Climbing Tempo · Work 3',480],['Recovery 3',240],['Cooldown',270]]);assert.equal(stage.segments.reduce((n,s)=>n+s.sec,0),2700)})
test('four-week totals equal the authoritative calendar including Sunday cycling',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),preview=fourWeekPreview(plan),weeks=plan.weeks.slice(0,4),expected=weeks.flatMap(w=>w.assignments).reduce((n,a)=>n+(a.type==='CYCLING'||a.type==='ASSESSMENT'?a.durationMinutes:0)+(a.components??[]).filter(x=>x.kind==='CYCLING').reduce((m,x)=>m+x.minutes,0),0);assert.equal(preview.totalRideMinutes,expected)})
test('Team HQ and off-season share readiness and missing evidence remains honest',()=>{const entry={date:'2026-09-23',updatedAt:'2026-09-23T08:00:00',source:'Rider manual entry',fatigue:'Low' as const,soreness:'None' as const,motivation:'High' as const,hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:''},health={date:'2026-09-22',sleepHours:7,recoveryScore:70,fatigue:20,mood:'Good'};const selected=authoritativeReadinessEntry([entry],health);assert.equal(projectReadiness(selected,'2026-09-23','OFF_SEASON').status,'Ready');assert.equal(projectReadiness(selected,'2026-09-23','TRAINING').status,'Ready');const off=readFileSync(new URL('../screens/OffSeasonScreen.tsx',import.meta.url),'utf8'),hq=readFileSync(new URL('../screens/TeamHQScreen.tsx',import.meta.url),'utf8');assert.match(off,/authoritativeReadinessEntry/);assert.match(hq,/authoritativeReadinessEntry/);assert.match(off,/Unavailable until season review/);assert.equal(halInitialZoneDevelopment()[0].confidence,'Low')})
test('mobile collapsed calendar and dark headings are explicit',()=>{const css=readFileSync(new URL('../App.css',import.meta.url),'utf8');assert.match(css,/plan-weeks details\.dashboard-card:not\(\[open\]\).*min-height:0/);assert.match(css,/offseason-screen h1.*offseason-screen h2.*offseason-screen h3\{color:#fff/);for(const width of [320,375,390,430])assert.ok(width<=430)})
