import test from 'node:test'
import assert from 'node:assert/strict'
import { adaptSunday, applyAssignmentAction, createDevelopmentProfile, emptyAlpha4025, ensureHalOffSeasonPlan, ftpCompanion, generatePlan, HAL_BASELINE, HAL_GOALS, HAL_INPUT, offSeasonJeanMessageAllowed, readinessStatus, recommendCamps, recommendSeries, recordPowerMeterInstallation, STRENGTH_A, STRENGTH_B, validFemmesProductionStage } from './alpha4025.ts'
import { migrateCareer } from '../state/careerPersistence.ts'

test('series recommendation remains separate, explicit and non-administrative',()=>{assert.equal(recommendSeries('Male'),'Standard RtR');assert.equal(recommendSeries('Female'),'RtR Femmes');assert.equal(recommendSeries('Prefer not to answer'),null);const profile=createDevelopmentProfile({...HAL_INPUT,category:'Female',seriesPreference:'Intro to Cycling',experience:'Beginner'});assert.equal(profile.seriesPathway,'Intro to Cycling');assert.equal(profile.instructionDensity,'HIGH')})
test('different intake produces transparent different profiles and unknown FTP never gets watts',()=>{const a=createDevelopmentProfile(HAL_INPUT),unknown={...HAL_INPUT,ftp:null,experience:'Beginner' as const,weeklyMinutes:180,primaryGoal:'Build confidence'},b=createDevelopmentProfile(unknown);assert.notDeepEqual(a,b);assert.equal(b.workoutTargetScaling,'EFFORT_ONLY');const plan=generatePlan(unknown,{...HAL_GOALS,weeklyMinutes:180,weeklyDays:3});assert.ok(plan.weeks.flatMap(w=>w.assignments).every(x=>x.powerTarget===undefined))})
test('Hal profile, baseline and balanced 12-week structure are exact',()=>{const profile=createDevelopmentProfile(HAL_INPUT),plan=generatePlan(HAL_INPUT,HAL_GOALS);assert.equal(HAL_INPUT.ftp,206);assert.match(profile.archetype,/Sustained-Power Climber/);assert.equal(plan.startDate,'2026-09-21');assert.equal(plan.weeks.length,12);assert.equal(plan.weeks[0].focus,'Transition and recovery');assert.deepEqual(plan.weeks.filter(w=>w.recoveryWeek).map(w=>w.number),[4,8,12]);assert.ok(plan.weeks[3].assignments.some(a=>/FTP/.test(a.title)));assert.ok(plan.weeks[11].assignments.some(a=>/FTP/.test(a.title)));assert.doesNotMatch(plan.weeks[0].assignments[3].title,/VO2/);assert.equal(HAL_BASELINE.distanceMiles,20.57);assert.equal(HAL_BASELINE.durationSeconds,5499);assert.equal(HAL_BASELINE.elevationFeet,721);assert.equal(HAL_BASELINE.powerWatts,undefined);assert.match(HAL_BASELINE.elevationSource,/WHOOP-reported/)})
test('plan obeys weekly placement, recovery, intensity and fueling contracts',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS);for(const w of plan.weeks){assert.equal(w.assignments[1].title,'Strength A');assert.equal(w.assignments[3].day,'Thursday');assert.equal(w.assignments[5].day,'Saturday');assert.match(w.assignments[6].title,/Strength B/);assert.ok(w.assignments.filter(a=>a.demandingCycling).length<=2)}assert.ok(plan.weeks[0].assignments[5].fueling.carbsPerHour);assert.notEqual(plan.weeks[0].assignments[0].fueling.carbsPerHour,plan.weeks[0].assignments[5].fueling.carbsPerHour)})
test('questionnaire changes camps and plans while completed history survives regeneration',()=>{const base=recommendCamps(HAL_INPUT,HAL_GOALS),otherGoals={...HAL_GOALS,primaryGoal:'Recovery',secondaryGoal:'Consistency',climbingGoal:'',enduranceGoal:'',vo2Goal:false,weeklyDays:3,weeklyMinutes:180},other=recommendCamps({...HAL_INPUT,role:'Sprinter'},otherGoals);assert.notDeepEqual(base.map(x=>x.id),other.map(x=>x.id));let old=generatePlan(HAL_INPUT,HAL_GOALS);old=applyAssignmentAction(old,'w1-d3',{kind:'SHORTEN',reason:'Available time'},{completedAt:'2026-09-23',durationMinutes:30});const regenerated=generatePlan(HAL_INPUT,{...HAL_GOALS,weeklyMinutes:300},old);assert.equal(regenerated.weeks[0].assignments[2].status,'PARTIAL')})
test('substitution satisfies one assignment and skipped work is not stacked',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),changed=applyAssignmentAction(plan,'w2-d4',{kind:'RTR_STAGE',reason:'Equivalent demanding stage',replacementId:'tour-stage'});assert.equal(changed.weeks[1].assignments.length,7);assert.equal(changed.weeks[1].assignments[3].status,'REPLACED');assert.equal(changed.weeks[2].assignments.length,7)})
test('Sunday adapts only to current readiness and stale readiness is explicit',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),sat=plan.weeks[8].assignments[5],fresh={date:'2026-11-21',updatedAt:'2026-11-21T08:00:00Z',source:'Manual',fatigue:'Moderate' as const,soreness:'Mild' as const,motivation:'High' as const,hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:'Reduce'};assert.equal(adaptSunday(sat,fresh,'2026-11-21T12:00:00Z').level,'REDUCE');assert.equal(readinessStatus(fresh,'2026-11-24T12:00:00Z').stale,true);assert.match(readinessStatus(fresh,'2026-11-24T12:00:00Z').message,/3 days old/)})
test('strength templates are distinct and Sunday has lower leg volume',()=>{assert.ok(STRENGTH_A.includes('Romanian deadlift'));assert.ok(STRENGTH_B.includes('Single-leg glute bridge'));assert.ok(!STRENGTH_B.includes('Romanian deadlift'))})
test('FTP companion calculates from each rider and never fabricates unknown targets',()=>{assert.deepEqual(ftpCompanion(null),{currentFtp:null,targetAverageWatts:null,zonesUnavailable:true});assert.equal(ftpCompanion(206).targetAverageWatts,217);assert.equal(ftpCompanion(250).targetAverageWatts,263)})
test('power meter installation begins calibration rather than equivalence',()=>{assert.equal(recordPowerMeterInstallation(emptyAlpha4025(),'2026-10-01').outdoorPowerCalibrationStatus,'COLLECTING')})
test('Femmes development fixtures cannot masquerade as verified production races',()=>{assert.equal(validFemmesProductionStage({id:'fixture',order:1,profileVerified:false}),false);assert.equal(validFemmesProductionStage({id:'verified',order:1,profileVerified:true,source:'Official',sourceReference:'https://example.test',verifiedAt:'2026-09-19',start:'A',finish:'B',distanceKm:100,routeProfile:[0,1]}),true)})
test('Jean excludes unauthored race calls from training but retains race and explicit climb coaching',()=>{assert.equal(offSeasonJeanMessageAllowed('TRAINING','Attack before the summit'),false);assert.equal(offSeasonJeanMessageAllowed('TRAINING','Fuel now and keep it easy'),true);assert.equal(offSeasonJeanMessageAllowed('CLIMBING_WORKOUT','Hold this climb smoothly'),true);assert.equal(offSeasonJeanMessageAllowed('RACE_STAGE','Attack before the summit'),true)})
test('schema 6 migration is additive, idempotent and seeds only matching Hal evidence',()=>{const source={schemaVersion:5,rider:{name:'Hal Kronenberg',ftp:206,devices:[]},rideHistory:[{id:'kept'}],season:{completedStages:[1]},alpha4025:undefined} as never,first=migrateCareer(source),second=migrateCareer(first);assert.equal(first.schemaVersion,6);assert.equal(first.rideHistory[0].id,'kept');assert.equal(first.alpha4025.outdoorActivities[0].id,HAL_BASELINE.id);assert.deepEqual(second.alpha4025,first.alpha4025)})

test('Hal plan restoration is idempotent and contains no lifecycle mutation',()=>{const source=emptyAlpha4025(),first=ensureHalOffSeasonPlan(source),second=ensureHalOffSeasonPlan(first);assert.equal(first.trainingPlan?.weeks.length,12);assert.equal(first.trainingPlan?.startDate,'2026-09-21');assert.equal(first.offSeasonUnlocked,false);assert.deepEqual(second,first);assert.equal(first.outdoorActivities.filter(item=>item.id===HAL_BASELINE.id).length,1)})
