import type { RiderArchetype } from '../types/career.ts'
import { CURATED_OFFSEASON_WORKOUTS, emptyAdaptiveTraining, recordExternalOffSeasonCompletion, workoutById, type AdaptiveTrainingState, type CuratedWorkout } from './adaptiveTraining40251.ts'

export type RiderCategory='Male'|'Female'|'Prefer not to answer'
export type SeriesPathway='Standard RtR'|'RtR Femmes'|'Intro to Cycling'|'Help me choose'
export type Progression='Conservative'|'Balanced'|'Ambitious'
export type EffortLanguage='Very easy'|'Easy'|'Comfortable'|'Hard but controlled'|'Very hard'|'Maximal'
export const OFF_SEASON_PLAN_WEEKS=24
export type ActivityStatus='PLANNED'|'COMPLETED'|'PARTIAL'|'SKIPPED'|'REPLACED'

export type PersonalizationInput={age?:number;category:RiderCategory;seriesPreference:SeriesPathway;experience:'Beginner'|'Recreational'|'Intermediate'|'Advanced'|'Competitive';ftp:number|null;weeklyDays:number;weeklyMinutes:number;longRideDays:string[];preferredRestDay:string;comfortableMinutes:number;indoorExperience:'None'|'Some'|'Regular';outdoorExperience:'None'|'Some'|'Regular';equipment:string[];outdoorPowerMeter:boolean;heartRateAvailable:boolean;cadenceResistanceConfidence:'Low'|'Growing'|'Confident';shiftingConfidence:'Low'|'Growing'|'Confident';brakingConfidence:'Low'|'Growing'|'Confident';outdoorConfidence:'Low'|'Growing'|'Confident';accommodations:string;painConcerns:string;primaryGoal:string;secondaryGoal:string;targetEvent:string;targetDate?:string;progression:Progression;recoveryDays:number;strengthDays:number;role:RiderArchetype}
export type RiderDevelopmentProfile={archetype:string;seriesPathway:Exclude<SeriesPathway,'Help me choose'>|null;developmentPriorities:string[];trainingVolumeRange:{minimumMinutes:number;maximumMinutes:number};workoutTargetScaling:'EFFORT_ONLY'|'FTP_SCALED';recoveryFrequency:string;cadenceComplexity:'FOUNDATION'|'PROGRESSIVE'|'ADVANCED';instructionDensity:'HIGH'|'STANDARD'|'CONCISE';climbingProgression:string;outdoorProgression:string;readinessAssessments:string[];recommendedCampIds:string[];jeanCoachingProfile:string;explanation:string}
export type GoalsQuestionnaire={nextSeasonObjective:string;targetEvent:string;targetDate?:string;primaryGoal:string;secondaryGoal:string;ftpGoal?:number;vo2Goal:boolean;climbingGoal:string;enduranceGoal:string;bodyCompositionGoal:string;outdoorGoal:string;weeklyDays:number;weeklyMinutes:number;longRideDays:string[];preferredRestDay:string;strengthDays:number;indoorOutdoorPreference:'Indoor'|'Outdoor'|'Balanced';equipment:string[];outdoorPowerAvailable:boolean;accommodations:string;currentFatigue:'Low'|'Moderate'|'High';currentMotivation:'Low'|'Moderate'|'High';desiredStartDate:string;progression:Progression}
export type CampRecommendation={id:string;name:string;why:string;develops:string[];durationWeeks:number;weeklyWorkload:string;entryRequirements:string[];sessionTypes:string[];completionCriteria:string[];nextCamp:string}
export type FuelingTarget={classification:'Rest/recovery'|'Easy Zone 2'|'Quality interval'|'Strength'|'Long ride'|'Back-to-back ride';carbohydrateDemand:'Low'|'Moderate'|'High';preRide:string;carbsPerHour:number|null;fluidMlPerHour:number|null;electrolytes:string;recoveryPriority:string;nextDayWorkload:string}
export type CalendarAssignment={id:string;workoutId?:string;components?:Array<{label:string;minutes:number;kind:'CYCLING'|'STRENGTH'}>;date:string;day:string;type:'REST'|'MOBILITY'|'CYCLING'|'STRENGTH'|'ASSESSMENT';title:string;purpose:string;camp:string;durationMinutes:number;intensity:'RECOVERY'|'EASY'|'MODERATE'|'HARD';demandingCycling:boolean;environment:'INDOOR'|'OUTDOOR'|'FLEXIBLE';primary:string;shortened:string;indoorAlternative:string;outdoorAlternative:string;recoveryAlternative:string;powerTarget?:{minimum:number;maximum:number};effort:EffortLanguage;fueling:FuelingTarget;status:ActivityStatus;completion?:{completedAt:string;durationMinutes:number;notes?:string};substitution?:{kind:'MOVE'|'SHORTEN'|'REPLACE'|'RTR_STAGE'|'INDOOR'|'SKIP';reason:string;replacementId?:string}}
export type PlanWeek={number:number;startsOn:string;camp:string;focus:string;recoveryWeek:boolean;assignments:CalendarAssignment[]}
export type TrainingPlan={id:string;profileRevision:string;profileFingerprint:string;generatedAt:string;startDate:string;progression:Progression;primary:true;weeks:PlanWeek[];explanation:string}
export type OutdoorActivity={id:string;assignmentId?:string;date:string;source:string;activity:'Outdoor cycling';durationSeconds:number;notes?:string;distanceMiles?:number;elevationFeet?:number;elevationSource?:string;averageSpeedMph?:number;strain?:number;calories?:number;averageHeartRate?:number;maximumHeartRate?:number;averageCadenceRpm?:number;averagePowerWatts?:number;rpe?:number;heartRateDistribution?:Array<{zone:string;range:string;seconds:number;percent:number}>;powerWatts?:number;weather?:string;wind?:string;fuelGrams?:number;fluidMl?:number;handlingConfidence?:string;shiftingConfidence?:string;brakingConfidence?:string;saddleDiscomfort?:string;footNumbness?:string;otherDiscomfort?:string;effort?:EffortLanguage;nextDayRecovery?:string;interpretation:string[]}
export type ReadinessEntry={date:string;updatedAt:string;source:string;sleepHours?:number;externalRecoveryScore?:number;recentStrain?:number;fatigue:'Low'|'Moderate'|'High';soreness:'None'|'Mild'|'Significant';motivation:'Low'|'Moderate'|'High';hydrationConcern:boolean;illnessOrPain:boolean;recommendedAdjustment:string}
export type ReadinessPhase='RACING'|'OFF_SEASON'|'INTRO'|'TRAINING'
export type ReadinessProjection={entry:ReadinessEntry|null;stale:boolean;daysOld:number|null;status:'Ready'|'Proceed with control'|'Recovery recommended'|'Update needed';adjustment:string;canAdaptTraining:boolean;phase:ReadinessPhase}
export type StrengthActivity={assignmentId:string;completedAt?:string;exercises:Array<{name:string;substitution?:string;sets:number;repetitions:number;load?:string;difficulty?:EffortLanguage;repetitionsRemaining?:number;completed:boolean;painOrLimitation?:string;notes?:string}>}
export type FtpAssessment={date:string;testAverageWatts?:number;ftpWatts?:number;source:'Peloton 20-minute FTP test'|'Manual';recovered:boolean}
export type ExternalCyclingCompletion={id:string;assignmentId:string;workoutId:string;date:string;source:string;durationSeconds:number;averagePowerWatts?:number;peakPowerWatts?:number;averageCadenceRpm?:number;averageResistancePercent?:number;averageHeartRateBpm?:number;maximumHeartRateBpm?:number;heartRateDistribution:Array<{zone:'Z1'|'Z2'|'Z3'|'Z4'|'Z5';seconds:number;percent:number}>;totalOutputKj?:number;rpe:number;feedback:string;outcome:'ON_TARGET'|'STRUGGLED'|'INCOMPLETE';ftpAssessment:false;interpretation:string[]}
export type SeasonReview={generatedAt:string;availableMetrics:Record<string,string|number>;unavailableMetrics:string[];improvements:string[];strengths:string[];opportunities:string[];recoveryConcerns:string[];offSeasonEmphasis:string[]}
export type FemmesStage={id:string;order:number;start?:string;finish?:string;distanceKm?:number;elevationM?:number;routeProfile?:number[];terrain?:string;sprintPoints?:string[];mountainsPoints?:string[];timeTrial?:boolean;objectives?:string[];jeanBriefing?:string;tacticalMetadata?:Record<string,string>;source?:string;sourceReference?:string;verifiedAt?:string;profileVerified:boolean}
export type Alpha4025State={adaptive:AdaptiveTrainingState;riderCategory:RiderCategory|null;seriesPreference:SeriesPathway|null;seriesConfirmed:boolean;seriesEntitlements:SeriesPathway[];intake:PersonalizationInput|null;developmentProfile:RiderDevelopmentProfile|null;questionnaire:GoalsQuestionnaire|null;campRecommendations:CampRecommendation[];trainingPlan:TrainingPlan|null;outdoorActivities:OutdoorActivity[];externalCyclingCompletions:ExternalCyclingCompletion[];strengthActivities:StrengthActivity[];readinessEntries:ReadinessEntry[];ftpAssessments:FtpAssessment[];seasonReview:SeasonReview|null;replayActivityIds:string[];offSeasonUnlocked:boolean;equipmentInstallationDate?:string;outdoorPowerCalibrationStatus:'NOT_AVAILABLE'|'COLLECTING'|'COMPARABLE';femmes:{seasonType:'RTR_FEMMES';developmentFixtures:FemmesStage[]}}
export type OwnerPreviewIdentity={role?:string|null;riderName:string;riderNumber:number;ftp:number|null}
export const normalizedRiderName=(name:string)=>name.trim().replace(/\s+/g,' ').toLocaleLowerCase('en-US')
export function isHalOffSeasonCareer(identity:OwnerPreviewIdentity){const name=normalizedRiderName(identity.riderName);return (name==='hal'||name==='hal kronenberg')&&identity.riderNumber===15&&(identity.ftp===206||identity.ftp===229)}

export const emptyAlpha4025=():Alpha4025State=>({adaptive:emptyAdaptiveTraining(),riderCategory:null,seriesPreference:null,seriesConfirmed:false,seriesEntitlements:[],intake:null,developmentProfile:null,questionnaire:null,campRecommendations:[],trainingPlan:null,outdoorActivities:[],externalCyclingCompletions:[],strengthActivities:[],readinessEntries:[],ftpAssessments:[],seasonReview:null,replayActivityIds:[],offSeasonUnlocked:false,outdoorPowerCalibrationStatus:'NOT_AVAILABLE',femmes:{seasonType:'RTR_FEMMES',developmentFixtures:[]}})

export function recommendSeries(category:RiderCategory):Exclude<SeriesPathway,'Help me choose'>|null{return category==='Male'?'Standard RtR':category==='Female'?'RtR Femmes':null}
export function createDevelopmentProfile(input:PersonalizationInput):RiderDevelopmentProfile{
 const series=input.seriesPreference==='Help me choose'?recommendSeries(input.category):input.seriesPreference
 const beginner=input.experience==='Beginner';const priorities=[input.primaryGoal,input.secondaryGoal].filter(Boolean)
 if(input.outdoorConfidence!=='Confident')priorities.push('Outdoor confidence and handling');if(input.role==='GC Contender'||input.role==='Climber')priorities.push('Sustained climbing and fatigue resistance');if(input.ftp===null)priorities.push('Establish FTP before watt prescriptions')
 const minimum=input.weeklyMinutes>=600?Math.round(input.weeklyMinutes*.55):Math.max(90,input.weeklyMinutes-Math.round(input.weeklyMinutes*.15)),maximum=input.weeklyMinutes>=600?input.weeklyMinutes:input.weeklyMinutes+Math.round(input.weeklyMinutes*(input.progression==='Ambitious'?.2:.1))
 return {archetype:`${input.role} · ${input.role==='GC Contender'||input.role==='Climber'?'Sustained-Power Climber':'Development Rider'}`,seriesPathway:series,developmentPriorities:Array.from(new Set(priorities)),trainingVolumeRange:{minimumMinutes:minimum,maximumMinutes:maximum},workoutTargetScaling:input.ftp===null?'EFFORT_ONLY':'FTP_SCALED',recoveryFrequency:input.progression==='Ambitious'?'Reduced week every fourth week with readiness checks':'Reduced week every fourth week',cadenceComplexity:beginner?'FOUNDATION':input.cadenceResistanceConfidence==='Confident'?'ADVANCED':'PROGRESSIVE',instructionDensity:beginner?'HIGH':input.experience==='Advanced'||input.experience==='Competitive'?'CONCISE':'STANDARD',climbingProgression:beginner?'Foundations before controlled climbing':'Sweet spot to threshold climbing, then high-aerobic work',outdoorProgression:input.outdoorExperience==='None'?'Skills, controlled 75–100 minutes, then a two-hour benchmark':'Controlled endurance, back-to-back rides, then multi-day blocks',readinessAssessments:['Daily source/date check','Week 4 review','Week 8 adaptation review','Week 12 block review','Week 16 durability review','Week 20 back-to-back review','Week 24 goal reassessment'],recommendedCampIds:selectCamps(input.primaryGoal,input.secondaryGoal,input.role,input.ftp,'Low'),jeanCoachingProfile:`${input.progression} progression; ${beginner?'high':'standard'} instruction support`,explanation:`The ${input.progression.toLowerCase()} pathway reflects ${input.weeklyDays} available days, ${input.comfortableMinutes}-minute comfort, the ${input.role} role, and the stated goals. ${input.ftp===null?'Power is unknown, so targets use heart rate and plain effort—not invented watts.':'Known FTP permits scaled indoor targets.'}`}
}

function selectCamps(primary:string,secondary:string,role:RiderArchetype,_ftp:number|null,fatigue:string){const text=`${primary} ${secondary}`.toLowerCase(),ids=['recovery-reset','aerobic-base'];if(/climb|tour|distance|endurance/.test(text)||role==='GC Contender'||role==='Climber')ids.push('climbing','endurance-durability');if(fatigue!=='High')ids.push('vo2max');return Array.from(new Set(ids))}
const CAMP_NAMES:Record<string,string>={'recovery-reset':'Recovery & Reset Camp','aerobic-base':'Aerobic Base Camp',altitude:'Altitude Training Camp',climbing:'Climbing Camp',vo2max:'VO2max & Durability Camp','threshold-tt':'Threshold & Time Trial Camp',strength:'Strength & Torque Camp','endurance-durability':'Endurance & Durability Camp',classics:'Classics Camp','grand-tour':'Grand Tour Preparation Camp'}
export function recommendCamps(input:PersonalizationInput,goals:GoalsQuestionnaire):CampRecommendation[]{return selectCamps(goals.primaryGoal,`${goals.secondaryGoal} ${goals.climbingGoal} ${goals.enduranceGoal}`,input.role,input.ftp,goals.currentFatigue).map((id,index)=>({id,name:CAMP_NAMES[id],why:id==='recovery-reset'?'A reset protects adaptation before new load.':`Selected from the rider’s ${goals.primaryGoal.toLowerCase()} objective, ${input.role} role, availability and recovery.`,develops:id==='climbing'?['Sustained climbing','Low-cadence torque','Fatigue resistance']:id==='vo2max'?['High-aerobic capacity','Repeatability']:id==='aerobic-base'?['Aerobic consistency','Pedal efficiency']:id==='endurance-durability'?['Endurance','Durability','Fatigue resistance','Fueling']:['Recovery','Movement quality'],durationWeeks:id==='recovery-reset'?1:id==='aerobic-base'?3:id==='vo2max'?4:2,weeklyWorkload:`${goals.weeklyDays} available days · ${goals.weeklyMinutes} minutes maximum`,entryRequirements:id==='vo2max'?['Base work completed','Adequate recovery','No unresolved pain']:['Current readiness entry'],sessionTypes:id==='climbing'?['Sweet spot','Threshold climbing','Seated torque']:id==='vo2max'?['Controlled VO2 repeats','Endurance support']:['Recovery','Endurance','Strength support'],completionCriteria:['Complete key sessions or record adaptations','Review recovery and comfort'],nextCamp:CAMP_NAMES[selectCamps(goals.primaryGoal,goals.secondaryGoal,input.role,input.ftp,goals.currentFatigue)[index+1]??'grand-tour']}))}

const addDays=(iso:string,days:number)=>{const date=new Date(`${iso}T12:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
const fuel=(classification:FuelingTarget['classification'],duration:number,next:string):FuelingTarget=>{const long=classification==='Long ride'||classification==='Back-to-back ride',quality=classification==='Quality interval';return {classification,carbohydrateDemand:long||quality?'High':classification==='Strength'?'Moderate':'Low',preRide:long||quality?'Begin fueled; use a familiar carbohydrate-rich meal or snack.':'Normal meal timing; arrive hydrated.',carbsPerHour:duration>=75?(long?45:30):quality?30:null,fluidMlPerHour:duration>=45?500:null,electrolytes:duration>=75?'Use according to sweat rate and conditions.':'Optional; adjust for heat and sweat.',recoveryPriority:long?'Recover carbohydrate, protein and fluids for tomorrow.':'Support the next scheduled workload.',nextDayWorkload:next}}
function assignment(week:number,dayIndex:number,start:string,data:Omit<CalendarAssignment,'id'|'date'|'day'|'status'|'fueling'>):CalendarAssignment{const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'],classification=data.type==='STRENGTH'?'Strength':data.type==='REST'?'Rest/recovery':dayIndex===5?'Long ride':dayIndex===6?'Back-to-back ride':data.intensity==='HARD'?'Quality interval':'Easy Zone 2';return {...data,id:`w${week}-d${dayIndex+1}`,date:addDays(start,(week-1)*7+dayIndex),day:days[dayIndex],status:'PLANNED',fueling:fuel(classification,data.durationMinutes,dayIndex===5?'Adaptive Sunday endurance and lighter strength':'Follow the calendar')}}
export function planProfileFingerprint(input:PersonalizationInput,goals:GoalsQuestionnaire){return JSON.stringify({scheduleVersion:2,ftp:input.ftp,role:input.role,weeklyDays:goals.weeklyDays,weeklyMinutes:goals.weeklyMinutes,primaryGoal:goals.primaryGoal,secondaryGoal:goals.secondaryGoal,targetEvent:goals.targetEvent,start:goals.desiredStartDate,progression:goals.progression,preference:goals.indoorOutdoorPreference,strengthDays:goals.strengthDays,longRideDays:goals.longRideDays})}
export function generatePlan(input:PersonalizationInput,goals:GoalsQuestionnaire,prior?:TrainingPlan|null):TrainingPlan{
 const camps=recommendCamps(input,goals),weeks:PlanWeek[]=[],ftp=input.ftp,fingerprint=planProfileFingerprint(input,goals),power=(a:number,b:number)=>ftp===null?{}:{powerTarget:{minimum:Math.round(ftp*a),maximum:Math.round(ftp*b)}}
 for(let week=1;week<=OFF_SEASON_PLAN_WEEKS;week++){const recovery=week%4===0,camp=week===1?'Recovery & Reset Camp':week<=4?'Aerobic Base Camp':week<=6?'Climbing Camp':week<=8?'Endurance & Durability Camp':week<=12?'VO2max & Durability Camp':week<=16?'Aerobic Foundation Camp':week<=20?'Sustained Climbing Camp':'Event Durability Camp',qualityId=week===1?'tempo-climb-45':week===4||week===12||week>=17&&week<=20||week===24?'threshold-3x8-45':week>=21||week>=9&&week<=12?'vo2-4x4-45':week>=13?'tempo-climb-45':week>=5?'threshold-3x8-45':'tempo-climb-45',qualityTitle=qualityId==='tempo-climb-45'?'Controlled Climbing Tempo':qualityId==='vo2-4x4-45'?'High Aerobic 4 × 4':'Threshold Development 3 × 8',qualityPurpose=workoutById(qualityId)!.purpose,qualityPower=qualityId==='vo2-4x4-45'?power(1.06,1.16):qualityId==='threshold-3x8-45'?power(.95,1.02):power(.76,.86),focus=week===1?'Real-world endurance and controlled climbing':recovery?'Reduced demand and evidence review':week>=21?'Multi-day endurance and event preparation':week>=17?'Sustained climbing and FTP development':week>=13?'Aerobic foundation and technique':week>=9?'VO2 development and durability':week>=5?'Sustained climbing and FTP development':'Aerobic durability and technique'
 const a:CalendarAssignment[]=[
 assignment(week,0,goals.desiredStartDate,{type:'REST',title:'Rest / optional mobility',purpose:'Recovery; optional mobility does not count toward training workload.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'Rest with optional mobility.',shortened:'Rest.',indoorAlternative:'Optional mobility.',outdoorAlternative:'Optional easy walk.',recoveryAlternative:'Rest.',effort:'Very easy'}),
 assignment(week,1,goals.desiredStartDate,{type:'STRENGTH',title:'Strength A',purpose:'Unilateral strength, posterior chain and core stability.',camp,durationMinutes:30,intensity:'MODERATE',demandingCycling:false,environment:'INDOOR',primary:'Thirty minutes of controlled Strength A.',shortened:'One controlled round.',indoorAlternative:'Primary strength session.',outdoorAlternative:'Not applicable.',recoveryAlternative:'Mobility only.',effort:'Comfortable'}),
 assignment(week,2,goals.desiredStartDate,{type:week===4||week===12?'ASSESSMENT':'CYCLING',workoutId:qualityId,title:qualityTitle,purpose:qualityPurpose,camp,durationMinutes:45,intensity:recovery?'MODERATE':'HARD',demandingCycling:!recovery,environment:'INDOOR',primary:qualityTitle,shortened:'Use the curated shorter or recovery alternative.',indoorAlternative:'Primary prescription.',outdoorAlternative:'Use a safe sustained rise by RPE only when appropriate.',recoveryAlternative:'Recovery Spin 30.',effort:recovery?'Comfortable':'Hard but controlled',...qualityPower}),
 assignment(week,3,goals.desiredStartDate,{type:'REST',title:'Recovery / optional mobility',purpose:'Absorb Wednesday quality.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'Rest.',shortened:'Rest.',indoorAlternative:'Mobility.',outdoorAlternative:'Easy walk.',recoveryAlternative:'Rest.',effort:'Very easy'}),
 assignment(week,4,goals.desiredStartDate,{type:'REST',title:'Rest',purpose:'Protect Saturday outdoor endurance.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'Rest.',shortened:'Rest.',indoorAlternative:'Rest.',outdoorAlternative:'Rest.',recoveryAlternative:'Rest.',effort:'Very easy'}),
 assignment(week,5,goals.desiredStartDate,{type:'CYCLING',workoutId:'outdoor-endurance-90',title:'Outdoor Endurance 90',purpose:'Build real-world endurance, pacing, comfort and fueling.',camp,durationMinutes:90,intensity:'MODERATE',demandingCycling:false,environment:'OUTDOOR',primary:week===1?'Following Friday’s FTP test, ride aerobic outdoor endurance at RPE 3–4/10 and conversational effort. No threshold efforts or hard climbing. Take 30–45 g carbohydrate and 500–750 ml fluid per hour, adjusted for Florida heat.':'Ride 90 minutes using heart rate, talk test and comfortable effort; no outdoor watts are inferred.',shortened:'Outdoor Endurance 60.',indoorAlternative:'Steady Endurance 75.',outdoorAlternative:'Primary prescription.',recoveryAlternative:'Recovery Spin 30 or rest.',effort:'Comfortable'}),
 assignment(week,6,goals.desiredStartDate,{type:'STRENGTH',title:'Adaptive Endurance + Strength B',purpose:'Build multi-day durability with separate cycling and strength portions.',camp,durationMinutes:75,components:[{label:'Adaptive endurance',minutes:45,kind:'CYCLING'},{label:'Strength B',minutes:30,kind:'STRENGTH'}],intensity:'MODERATE',demandingCycling:false,environment:'FLEXIBLE',primary:'45 minutes adaptive endurance, then 30 minutes Strength B.',shortened:'30 minutes easy cycling plus 15 minutes reduced Strength B.',indoorAlternative:'Easy indoor endurance plus Strength B.',outdoorAlternative:'Comfortable outdoor endurance plus Strength B.',recoveryAlternative:'Rest or mobility; preserve the original assignment.',effort:'Comfortable'})]
 if(goals.weeklyMinutes>=600&&goals.weeklyDays>=6){
 const block=Math.floor((week-1)/4)
 const outdoor=(day:number,minutes:number)=>{const workout=workoutById(minutes===60?'outdoor-easy-60':`outdoor-endurance-${minutes}`)!;return assignment(week,day,goals.desiredStartDate,{type:'CYCLING',workoutId:workout.id,title:workout.title,purpose:workout.purpose,camp,durationMinutes:minutes,intensity:minutes===60?'EASY':'MODERATE',demandingCycling:false,environment:'OUTDOOR',primary:`Ride ${minutes} minutes at conversational effort. Fuel and hydrate according to duration and conditions; stop if discomfort persists.`,shortened:'Use a shorter curated outdoor ride or rest.',indoorAlternative:'Switch to an equal-duration indoor endurance ride.',outdoorAlternative:'Primary prescription.',recoveryAlternative:'Recovery spin or rest.',effort:minutes===60?'Easy':'Comfortable'})}
 const indoor=(day:number,minutes:number)=>{const workout=workoutById(minutes===30?'recovery-spin-30':minutes===45?'endurance-steady-45':minutes===60?'indoor-endurance-60':minutes===75?'endurance-steady-75':'indoor-endurance-90')!;return assignment(week,day,goals.desiredStartDate,{type:'CYCLING',workoutId:workout.id,title:workout.title,purpose:workout.purpose,camp,durationMinutes:minutes,intensity:minutes===30?'RECOVERY':'MODERATE',demandingCycling:false,environment:'INDOOR',primary:`${minutes} minutes of controlled indoor endurance.`,shortened:'Shorter easy ride or rest.',indoorAlternative:'Primary prescription.',outdoorAlternative:minutes>=60?'Switch to equal-duration outdoor endurance when available.':'Easy outdoor spin when appropriate.',recoveryAlternative:'Rest.',effort:minutes===30?'Very easy':'Comfortable'})}
 const strength=(day:number,label:'A'|'B',minutes=30)=>{const base=assignment(week,day,goals.desiredStartDate,{type:'STRENGTH',title:`Strength ${label}`,purpose:label==='A'?'Unilateral strength, posterior chain and core stability.':'Lighter durability strength, trunk stability and movement quality.',camp,durationMinutes:minutes,intensity:'MODERATE',demandingCycling:false,environment:'INDOOR',primary:`${minutes} minutes of controlled Strength ${label}.`,shortened:'Reduce sets or complete one controlled round.',indoorAlternative:'Primary strength session.',outdoorAlternative:'Not applicable.',recoveryAlternative:'Mobility only.',effort:'Comfortable'});return {...base,id:`${base.id}-strength-${label.toLowerCase()}`}}
 if(recovery){
  a[1]=outdoor(1,60);a[3]=outdoor(3,60);a[2]=assignment(week,2,goals.desiredStartDate,{type:'CYCLING',workoutId:'tempo-climb-45',title:'Controlled Climbing Tempo',purpose:'Preserve sustained-climbing purpose with reduced load.',camp,durationMinutes:45,intensity:'MODERATE',demandingCycling:false,environment:'INDOOR',primary:'Controlled tempo; skip if recovery is poor.',shortened:'Recovery Spin 30.',indoorAlternative:'Primary prescription.',outdoorAlternative:'Easy spin only.',recoveryAlternative:'Rest.',effort:'Comfortable',...power(.76,.86)});a[5]=outdoor(5,90);a[6]=outdoor(6,90)
  a.push(strength(1,'A',20),strength(4,'B',20))
 } else {
  const saturday=week===1?90:[120,150,180,210,240,270][block],sunday=[120,120,150,180,210,240][block]
  const weekdayRides=week===1?[90,120,75]:block===0?[120,75,60]:block===1?[90,75,60]:block===2?[75,60,30]:block===3?[60,45,0]:block===4?[45,0,0]:[0,0,0]
  if(block===5)a[2]=assignment(week,2,goals.desiredStartDate,{type:'CYCLING',workoutId:qualityId,title:qualityTitle,purpose:qualityPurpose,camp,durationMinutes:45,intensity:'HARD',demandingCycling:true,environment:'INDOOR',primary:qualityTitle,shortened:'Use the curated shorter or recovery alternative.',indoorAlternative:'Primary prescription.',outdoorAlternative:'Use a safe sustained rise by RPE only when appropriate.',recoveryAlternative:'Recovery Spin 30.',effort:'Hard but controlled',...qualityPower})
  if(weekdayRides[0]>0)a[1]=weekdayRides[0]>=60?outdoor(1,weekdayRides[0]):indoor(1,weekdayRides[0]);else a[1]=assignment(week,1,goals.desiredStartDate,{type:'REST',title:'Strength-day recovery',purpose:'No cycling load; complete the separate strength session only.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'No ride scheduled.',shortened:'Rest.',indoorAlternative:'Rest.',outdoorAlternative:'Easy walk.',recoveryAlternative:'Rest.',effort:'Very easy'})
  if(weekdayRides[1]>0)a[3]=weekdayRides[1]>=60?outdoor(3,weekdayRides[1]):indoor(3,weekdayRides[1]);else a[3]=assignment(week,3,goals.desiredStartDate,{type:'REST',title:'Recovery / optional mobility',purpose:'Protect the weekend durability block.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'Rest.',shortened:'Rest.',indoorAlternative:'Mobility.',outdoorAlternative:'Easy walk.',recoveryAlternative:'Rest.',effort:'Very easy'})
  if(weekdayRides[2]>0)a[4]=weekdayRides[2]>=60?indoor(4,weekdayRides[2]):indoor(4,weekdayRides[2]);else a[4]=assignment(week,4,goals.desiredStartDate,{type:'REST',title:'Rest before long rides',purpose:'Protect the weekend durability block.',camp,durationMinutes:0,intensity:'RECOVERY',demandingCycling:false,environment:'FLEXIBLE',primary:'Rest.',shortened:'Rest.',indoorAlternative:'Rest.',outdoorAlternative:'Rest.',recoveryAlternative:'Rest.',effort:'Very easy'})
  a[5]=outdoor(5,saturday);a[6]=outdoor(6,sunday)
  a.push(strength(1,'A',block===5?20:30),strength(4,'B',block===5?25:30))
 }
 }
 weeks.push({number:week,startsOn:addDays(goals.desiredStartDate,(week-1)*7),camp,focus,recoveryWeek:recovery,assignments:a})}
 if(prior){const retained=new Map(prior.weeks.flatMap(w=>w.assignments).filter(a=>prior.profileFingerprint===fingerprint||a.status==='COMPLETED'||a.status==='PARTIAL').map(a=>[a.id,a]));for(const week of weeks)week.assignments=week.assignments.map(a=>retained.get(a.id)??a)}
 const plan:TrainingPlan={id:prior?.id??`plan-${goals.desiredStartDate}`,profileRevision:fingerprint,profileFingerprint:fingerprint,generatedAt:prior?.profileFingerprint===fingerprint?prior.generatedAt:new Date().toISOString(),startDate:goals.desiredStartDate,progression:goals.progression,primary:true,weeks,explanation:`One authoritative 24-week plan targets up to ${goals.weeklyMinutes} total training minutes across ${goals.weeklyDays} training days, including two strength sessions in regular weeks (with shorter recovery weeks), with ${goals.progression.toLowerCase()} progression. It targets ${goals.primaryGoal.toLowerCase()} and ${goals.secondaryGoal.toLowerCase()} for ${goals.targetEvent}. Camp sequence: ${camps.map(c=>c.name).join(', ')}.`}
 const errors=validatePlanConstraints(plan,goals.weeklyDays,goals.weeklyMinutes);if(errors.length)throw new Error(`Invalid off-season plan: ${errors.join('; ')}`);return plan
}

export function validatePlanConstraints(plan:TrainingPlan,weeklyDays:number,weeklyMinutes:number){const errors:string[]=[];for(const week of plan.weeks){const active=week.assignments.filter(a=>a.durationMinutes>0&&a.type!=='REST'&&a.type!=='MOBILITY'),minutes=active.reduce((sum,a)=>sum+a.durationMinutes,0);if(new Set(active.map(a=>a.date)).size>weeklyDays)errors.push(`Week ${week.number} exceeds training days`);if(minutes>weeklyMinutes)errors.push(`Week ${week.number} exceeds scheduled minutes`);if(!week.recoveryWeek&&weeklyMinutes>=600){const strength=active.filter(a=>a.type==='STRENGTH');if(strength.length!==2)errors.push(`Week ${week.number} must schedule two strength sessions`)}for(const a of active.filter(a=>a.type==='CYCLING'||a.type==='ASSESSMENT')){const workout=a.workoutId?workoutById(a.workoutId):null;if(!workout)errors.push(`${a.id} has no curated workout`);else {if(workout.durationMinutes!==a.durationMinutes)errors.push(`${a.id} duration disagrees`);if(workout.title!==a.title||workout.purpose!==a.purpose)errors.push(`${a.id} prescription disagrees`);if(week.recoveryWeek&&workout.demand>4)errors.push(`${a.id} exceeds recovery-week demand`);if(a.intensity==='EASY'&&/Tempo|Sweet Spot|Threshold/.test(`${workout.primaryZone} ${workout.secondaryZone??''}`))errors.push(`${a.id} easy label conflicts with targets`)}}}return errors}

export function movePlannedRide(plan:TrainingPlan,assignmentId:string,targetDate:string):TrainingPlan{
 const week=plan.weeks.find(w=>w.assignments.some(a=>a.id===assignmentId)),ride=week?.assignments.find(a=>a.id===assignmentId),target=week?.assignments.find(a=>a.date===targetDate)
 if(!week||!ride||(ride.type!=='CYCLING'&&ride.type!=='ASSESSMENT')||ride.completion||ride.status==='COMPLETED'||ride.status==='PARTIAL')throw new Error('Only unfinished rides can be moved.')
 if(!target||target.type!=='REST'||target.status!=='PLANNED'||target.completion)throw new Error('Choose an unoccupied rest day in the same week.')
 const changed={...plan,weeks:plan.weeks.map(w=>w.number!==week.number?w:{...w,assignments:w.assignments.map(a=>a.id===ride.id?{...a,date:target.date,day:target.day,substitution:{kind:'MOVE' as const,reason:`Moved from ${ride.date} to ${target.date} by rider.`}}:a.id===target.id?{...a,date:ride.date,day:ride.day}:a)})}
 return changed
}

export function availableRideChanges(plan:TrainingPlan,assignmentId:string):CuratedWorkout[]{
 const week=plan.weeks.find(w=>w.assignments.some(a=>a.id===assignmentId)),ride=week?.assignments.find(a=>a.id===assignmentId),current=ride?.workoutId?workoutById(ride.workoutId):null
 if(!ride||!current||ride.completion||ride.status==='COMPLETED'||ride.status==='PARTIAL'||(ride.type!=='CYCLING'&&ride.type!=='ASSESSMENT'))return []
 return CURATED_OFFSEASON_WORKOUTS.filter(w=>w.id!==current.id&&w.environment!=='OUTDOOR'&&w.durationMinutes<=ride.durationMinutes&&w.demand<=current.demand&&(!week!.recoveryWeek||w.demand<=4))
}

const SETTING_PAIRS:Record<string,string>={'outdoor-easy-60':'indoor-endurance-60','indoor-endurance-60':'outdoor-easy-60','outdoor-endurance-75':'endurance-steady-75','endurance-steady-75':'outdoor-endurance-75','outdoor-endurance-90':'indoor-endurance-90','indoor-endurance-90':'outdoor-endurance-90','outdoor-endurance-120':'indoor-endurance-120','indoor-endurance-120':'outdoor-endurance-120',...Object.fromEntries([150,180,210,240,270].flatMap(minutes=>[[`outdoor-endurance-${minutes}`,`indoor-endurance-${minutes}`],[`indoor-endurance-${minutes}`,`outdoor-endurance-${minutes}`]]))}
export function switchRideSetting(plan:TrainingPlan,assignmentId:string):TrainingPlan{
 const ride=plan.weeks.flatMap(w=>w.assignments).find(a=>a.id===assignmentId),alternate=ride?.workoutId?workoutById(SETTING_PAIRS[ride.workoutId]):null
 if(!ride||!alternate||ride.type!=='CYCLING'||ride.completion||ride.status==='COMPLETED'||ride.status==='PARTIAL'||ride.durationMinutes!==alternate.durationMinutes)throw new Error('Only unfinished endurance rides with an equal-length indoor or outdoor option can change setting.')
 return {...plan,weeks:plan.weeks.map(w=>({...w,assignments:w.assignments.map(a=>a.id!==assignmentId?a:{...a,workoutId:alternate.id,title:alternate.title,purpose:alternate.purpose,environment:alternate.environment as 'INDOOR'|'OUTDOOR',powerTarget:alternate.environment==='OUTDOOR'?undefined:a.powerTarget,primary:`${alternate.durationMinutes} minutes at the original conversational effort; same duration and purpose.`,substitution:{kind:'REPLACE' as const,reason:`Changed ${ride.environment.toLowerCase()} to ${alternate.environment.toLowerCase()} with the same duration and effort.`,replacementId:alternate.id},status:'REPLACED' as const})}))}
}
export function canSwitchRideSetting(ride:CalendarAssignment){return Boolean(ride.workoutId&&SETTING_PAIRS[ride.workoutId]&&ride.type==='CYCLING'&&!ride.completion&&ride.status!=='COMPLETED'&&ride.status!=='PARTIAL')}

export function changePlannedRide(plan:TrainingPlan,assignmentId:string,workoutId:string,ftp:number|null):TrainingPlan{
 const ride=plan.weeks.flatMap(w=>w.assignments).find(a=>a.id===assignmentId),workout=availableRideChanges(plan,assignmentId).find(w=>w.id===workoutId)
 if(!ride||!workout)throw new Error('Choose a supported workout that fits the original ride duration and effort.')
 const classification=workout.demand>=4?'Quality interval':workout.demand===1?'Rest/recovery':'Easy Zone 2'
 return {...plan,weeks:plan.weeks.map(week=>({...week,assignments:week.assignments.map(a=>a.id!==assignmentId?a:{...a,type:'CYCLING' as const,workoutId:workout.id,title:workout.title,purpose:workout.purpose,primary:workout.title,durationMinutes:workout.durationMinutes,environment:'INDOOR' as const,intensity:workout.demand>=4?'HARD' as const:workout.demand===1?'RECOVERY' as const:'MODERATE' as const,demandingCycling:workout.demand>=4,powerTarget:ftp!==null&&workout.ftpRange?{minimum:Math.round(ftp*workout.ftpRange[0]),maximum:Math.round(ftp*workout.ftpRange[1])}:undefined,effort:workout.demand>=4?'Hard but controlled' as const:workout.demand===1?'Very easy' as const:'Comfortable' as const,fueling:fuel(classification,workout.durationMinutes,a.fueling.nextDayWorkload),status:'REPLACED' as const,substitution:{kind:'REPLACE' as const,reason:`Rider changed ${ride.title} to ${workout.title}; no extra ride was added.`,replacementId:workout.id}})}))}
}

export function applyAssignmentAction(plan:TrainingPlan,id:string,action:NonNullable<CalendarAssignment['substitution']>,completion?:CalendarAssignment['completion']):TrainingPlan{return {...plan,weeks:plan.weeks.map(w=>({...w,assignments:w.assignments.map(a=>a.id!==id?a:{...a,substitution:action,status:completion?(completion.durationMinutes<a.durationMinutes?'PARTIAL':'COMPLETED'):action.kind==='SKIP'?'SKIPPED':'REPLACED',completion})}))}}
export function adaptSunday(saturday:CalendarAssignment,readiness:ReadinessEntry|undefined,localDate:string){const projection=projectReadiness(readiness,localDate.slice(0,10),'OFF_SEASON');if(!projection.canAdaptTraining)return {level:'NO_CHANGE' as const,reason:'Readiness is missing or stale; update today’s health before adjusting training.'};if(projection.status==='Recovery recommended')return {level:'REST' as const,reason:'Poor recovery, illness or pain: rest or recovery spin; reduce or skip strength and steam room.'};if(projection.status==='Proceed with control'||saturday.intensity==='HARD')return {level:'REDUCE' as const,reason:'Moderate fatigue or difficult Saturday: shorten the ride and reduce Strength B leg volume.'};return {level:'PLANNED' as const,reason:'Recovery supports planned endurance and lighter Strength B.'}}
const localDayNumber=(value:string)=>{const match=value.slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);if(!match)return NaN;return Date.UTC(Number(match[1]),Number(match[2])-1,Number(match[3]))/86400000}
export function projectReadiness(entry:ReadinessEntry|undefined,localDate:string,phase:ReadinessPhase):ReadinessProjection{if(!entry)return {entry:null,stale:true,daysOld:null,status:'Update needed',adjustment:phase==='RACING'?'Update readiness before racing.':phase==='INTRO'?'Update readiness before today’s session.':'Update readiness before training.',canAdaptTraining:false,phase};const days=Math.max(0,localDayNumber(localDate)-localDayNumber(entry.date));if(!Number.isFinite(days)||days>0)return {entry,stale:true,daysOld:Number.isFinite(days)?days:null,status:'Update needed',adjustment:`Readiness data is ${Number.isFinite(days)?days:'several'} days old. Update today’s health before adjusting training.`,canAdaptTraining:false,phase};const recovery=entry.illnessOrPain||entry.fatigue==='High'||entry.soreness==='Significant',controlled=entry.fatigue==='Moderate'||entry.soreness==='Mild'||entry.hydrationConcern,status=recovery?'Recovery recommended':controlled?'Proceed with control':'Ready';const adjustment=recovery?(phase==='RACING'?'Recovery recommended before racing.':phase==='INTRO'?'Recovery recommended before today’s session.':'Recovery session recommended.') : controlled?(phase==='RACING'?'Race with control.':phase==='INTRO'?'Keep the effort comfortable.':'Keep today controlled.'):(phase==='RACING'?'Ready to race.':phase==='INTRO'?'Ready for today’s session.':'Ready for planned training.');return {entry,stale:false,daysOld:0,status,adjustment,canAdaptTraining:true,phase}}
export function readinessStatus(entry:ReadinessEntry|undefined,now:string){const localDate=now.slice(0,10),projection=projectReadiness(entry,localDate,'OFF_SEASON');return {stale:projection.stale,daysOld:projection.daysOld,message:projection.adjustment}}
export function legacyHealthReadiness(health:{date:string;sleepHours:number;recoveryScore:number;fatigue:number;mood:string}):ReadinessEntry{return {date:health.date,updatedAt:`${health.date}T12:00:00`,source:'Manual',sleepHours:health.sleepHours,externalRecoveryScore:health.recoveryScore,fatigue:health.fatigue>=67?'High':health.fatigue>=34?'Moderate':'Low',soreness:'None',motivation:health.mood==='Low'?'Low':health.mood==='Steady'?'Moderate':'High',hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:'Use the authoritative phase-aware readiness projection.'}}
export function recordPowerMeterInstallation(state:Alpha4025State,date:string):Alpha4025State{return {...state,equipmentInstallationDate:date,outdoorPowerCalibrationStatus:'COLLECTING'}}
export function validFemmesProductionStage(stage:FemmesStage){return stage.profileVerified===true&&Boolean(stage.source&&stage.sourceReference&&stage.verifiedAt&&stage.start&&stage.finish&&stage.distanceKm&&stage.routeProfile?.length)}
export const STRENGTH_A=['Squat or goblet squat','Romanian deadlift','Bulgarian split squat or step-up','Single-arm row','Single-arm press','Calf raise','Bird dog or anti-rotation press','Carry or bracing movement']
export const STRENGTH_B=['Single-leg glute bridge','Lateral lunge or controlled step-up','Standing hamstring curl','Row','Light shoulder press or lateral raise','Bird dog','Anti-rotation work','Optional calf raise']
export function ftpCompanion(currentFtp:number|null){return currentFtp===null?{currentFtp:null,targetAverageWatts:null,zonesUnavailable:true}:{currentFtp,targetAverageWatts:Math.round(currentFtp/.95),zonesUnavailable:false}}
const RACE_ONLY=/summit|descent|attack|peloton|sprint|KOM|breakaway/i
export function offSeasonJeanMessageAllowed(activity:'TRAINING'|'CLIMBING_WORKOUT'|'RACE_STAGE',message:string){return activity==='RACE_STAGE'||(activity==='CLIMBING_WORKOUT'&&!/attack|peloton|sprint|KOM|breakaway/i.test(message))||!RACE_ONLY.test(message)}

export const HAL_BASELINE:OutdoorActivity={id:'hal-outdoor-baseline-2026-09-19',date:'2026-09-19',source:'WHOOP/manual entry',activity:'Outdoor cycling',distanceMiles:20.57,durationSeconds:5499,averageSpeedMph:13.5,elevationFeet:721,elevationSource:'WHOOP-reported; not barometrically verified',strain:15.1,calories:1057,averageHeartRate:136,maximumHeartRate:162,heartRateDistribution:[{zone:'Zone 4',range:'149–166 bpm',seconds:459,percent:8},{zone:'Zone 3',range:'132–148 bpm',seconds:4049,percent:76},{zone:'Zone 2',range:'115–131 bpm',seconds:712,percent:12},{zone:'Zone 1',range:'103–114 bpm',seconds:115,percent:2},{zone:'Below Zone 1',range:'Below 103 bpm',seconds:164,percent:2}],interpretation:['Successful first outdoor baseline','More than 90 minutes outdoors','Substantial tempo/endurance cardiovascular load','Not a purely easy Zone 2 ride','Beyond a basic 45-minute outdoor introduction','Continue easier pacing, handling, comfort and fueling development']}
export const HAL_INPUT:PersonalizationInput={age:45,category:'Male',seriesPreference:'Standard RtR',experience:'Intermediate',ftp:229,weeklyDays:6,weeklyMinutes:600,longRideDays:['Saturday','Sunday'],preferredRestDay:'Monday',comfortableMinutes:90,indoorExperience:'Regular',outdoorExperience:'Some',equipment:['Peloton','Garage strength equipment'],outdoorPowerMeter:false,heartRateAvailable:true,cadenceResistanceConfidence:'Confident',shiftingConfidence:'Growing',brakingConfidence:'Growing',outdoorConfidence:'Growing',accommodations:'',painConcerns:'Monitor saddle discomfort and foot numbness',primaryGoal:'Build real-world riding endurance',secondaryGoal:'Build toward 100-plus miles on consecutive days',targetEvent:'Giro d’Italia',targetDate:'2027-07-01',progression:'Balanced',recoveryDays:2,strengthDays:2,role:'GC Contender'}
export const HAL_GOALS:GoalsQuestionnaire={nextSeasonObjective:'Build toward 100-plus-mile rides on consecutive days.',targetEvent:'Giro d’Italia',targetDate:'2027-07-01',primaryGoal:'Build real-world riding endurance',secondaryGoal:'Build toward 100-plus miles on consecutive days',ftpGoal:undefined,vo2Goal:true,climbingGoal:'Sustained threshold climbing',enduranceGoal:'Progress toward consecutive 100-plus-mile days through supported endurance milestones',bodyCompositionGoal:'Sustainable weight reduction without underfueling',outdoorGoal:'Confidence, pacing, handling and fueling',weeklyDays:6,weeklyMinutes:600,longRideDays:['Saturday','Sunday'],preferredRestDay:'Monday',strengthDays:2,indoorOutdoorPreference:'Balanced',equipment:['Peloton','Garage strength equipment'],outdoorPowerAvailable:false,accommodations:'Monitor saddle discomfort and foot numbness',currentFatigue:'Low',currentMotivation:'High',desiredStartDate:'2026-09-21',progression:'Balanced'}
export const HAL_SEPT23_PELOTON:ExternalCyclingCompletion={id:'hal-peloton-2026-09-23-tempo-climb',assignmentId:'w1-d3',workoutId:'tempo-climb-45',date:'2026-09-23',source:'Peloton manual external completion',durationSeconds:2700,averagePowerWatts:151,peakPowerWatts:222,averageCadenceRpm:80,averageResistancePercent:45,averageHeartRateBpm:129,maximumHeartRateBpm:142,heartRateDistribution:[{zone:'Z3',seconds:1301,percent:48},{zone:'Z2',seconds:1282,percent:47},{zone:'Z1',seconds:112,percent:4},{zone:'Z4',seconds:0,percent:0},{zone:'Z5',seconds:0,percent:0}],totalOutputKj:406,rpe:4,feedback:'Legs felt strong. The third climbing interval was a decent but controlled effort; the rider intentionally held back to follow the prescription.',outcome:'ON_TARGET',ftpAssessment:false,interpretation:['Completed the original Week 1 Wednesday assignment on target','The intentional warm-up spin-up explains the 222 W peak and is not failed pacing','Not an FTP assessment','No VO2 Max or Anaerobic progression evidence','No bonus workload added; the remaining Week 1 schedule is unchanged']}

/** Restores only missing authoritative plan data; season lifecycle and activity history are never touched. */
export function ensureHalOffSeasonPlan(state:Alpha4025State):Alpha4025State{const trainingPlan=generatePlan(HAL_INPUT,HAL_GOALS,state.trainingPlan),restored:Alpha4025State={...state,riderCategory:state.riderCategory??'Male',seriesPreference:state.seriesPreference??'Standard RtR',seriesConfirmed:state.seriesConfirmed||state.seriesPreference===null,seriesEntitlements:Array.from(new Set([...state.seriesEntitlements,'Standard RtR'])),intake:HAL_INPUT,developmentProfile:createDevelopmentProfile(HAL_INPUT),questionnaire:HAL_GOALS,campRecommendations:recommendCamps(HAL_INPUT,HAL_GOALS),trainingPlan,outdoorActivities:state.outdoorActivities.some(item=>item.id===HAL_BASELINE.id)?state.outdoorActivities:[...state.outdoorActivities,HAL_BASELINE]};return recordExternalOffSeasonCompletion(restored,HAL_SEPT23_PELOTON)}
export function currentLocalDate(date=new Date()){return [date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-')}
export function authoritativeReadinessEntry(entries:ReadinessEntry[],health:{date:string;sleepHours:number;recoveryScore:number;fatigue:number;mood:string}){return entries[0]??legacyHealthReadiness(health)}
