import test from 'node:test'
import assert from 'node:assert/strict'
import { PELOTON_BASELINE_EQUIPMENT, PELOTON_MANUAL_PROFILE, PowerAdjustmentGate, estimateBikePower, resolveManualBikeTarget } from './manualBike.ts'
import { raceMarkerPositions, returnMultiplier, shouldDisplayClimb, sprintTransitionCountdown, tacticalOpportunity, tacticalPrescription, trainingMarkerPositions } from './alpha4021.ts'
import { buildSprintPhases, sprintSnapshot } from './sprintPhases.ts'
import { resolvePreviewTarget } from './previewTargets.ts'
import { getRaceStage } from '../data/raceStages.ts'
import { migrateCareer } from '../state/careerPersistence.ts'

const resolve=(powerRange={min:105,max:120},cadenceRange={min:92,max:100})=>resolveManualBikeTarget({powerRange,cadenceRange,gradient:0,equipment:PELOTON_BASELINE_EQUIPMENT,profile:PELOTON_MANUAL_PROFILE})
test('low power coupled targets are feasible, narrow and internally consistent',()=>{const target=resolve();assert.ok(target.feasibleCombinations.length>=2);assert.ok(target.resolvedResistanceRange!.max-target.resolvedResistanceRange!.min<=3);for(const pair of target.feasibleCombinations){assert.ok(pair.estimatedPower>=100&&pair.estimatedPower<=125);assert.equal(Math.round(estimateBikePower(PELOTON_MANUAL_PROFILE,pair.resistance,pair.cadence)),pair.estimatedPower)}})
test('equipment interpolation is monotonic in resistance and cadence',()=>{for(const cadence of [67,76,90,100]){let prior=0;for(let resistance=20;resistance<=70;resistance++){const power=estimateBikePower(PELOTON_MANUAL_PROFILE,resistance,cadence);assert.ok(power>=prior);prior=power}}for(const resistance of [35,45,54]){let prior=0;for(let cadence=60;cadence<=115;cadence++){const power=estimateBikePower(PELOTON_MANUAL_PROFILE,resistance,cadence);assert.ok(power>=prior);prior=power}}})
test('instruction gate waits through ordinary fluctuations',()=>{const gate=new PowerAdjustmentGate(6,5);assert.equal(gate.update(90,{min:100,max:110},0),false);assert.equal(gate.update(90,{min:100,max:110},5),false);assert.equal(gate.update(90,{min:100,max:110},6),true);assert.equal(gate.update(104,{min:100,max:110},7),false)})
test('sprint phases remain proportional to canonical sector clock with deterministic warnings',()=>{const segment={name:'Final Lead-out',type:'Sprint sector',sec:120,power:'200–300 W',cadence:'95–112 rpm',resistance:'40–45%',zone:'Z5',icon:'⚡',terrainLabel:'Sprint',routeKm:10,objective:'Sprint',description:'Sprint',secondaryObjective:'Hold'};const phases=buildSprintPhases(segment);assert.deepEqual(phases.map(p=>p.name),['BUILD','POSITION','LAUNCH','SPRINT']);for(const phase of phases){assert.equal(sprintSnapshot(phases,phase.end-10)?.remaining,10);assert.equal(sprintTransitionCountdown(4.2),5);assert.equal(sprintTransitionCountdown(5.2),null)}assert.equal(phases.at(-1)!.end,segment.sec)})
test('tactics are contextual, absent from training and sprint mode',()=>{const segment={name:'Late Climb',type:'Sustained climb',sec:300};assert.equal(tacticalOpportunity(segment,true,false,40),null);assert.equal(tacticalOpportunity(segment,false,true,40),null);assert.equal(tacticalOpportunity(segment,false,false,0),null);assert.equal(tacticalOpportunity(segment,false,false,40)?.action,'ATTACK')})
test('attack changes prescription, decline identity preserves it, return reaches exact baseline',()=>{const baseline=resolvePreviewTarget(getRaceStage(8).segments[3],208,PELOTON_BASELINE_EQUIPMENT);const attack=tacticalPrescription(baseline,1.12,PELOTON_BASELINE_EQUIPMENT,PELOTON_MANUAL_PROFILE);assert.ok(attack.powerRange.min>baseline.powerRange.min);assert.equal(tacticalPrescription(baseline,1,PELOTON_BASELINE_EQUIPMENT,PELOTON_MANUAL_PROFILE),baseline);assert.equal(returnMultiplier(1.12,45),1)})
test('training time markers span profile while race markers remain geographical',()=>{assert.deepEqual(trainingMarkerPositions([{sec:300},{sec:600},{sec:600},{sec:300}]),[0,1/6,1/2,5/6,1]);assert.deepEqual(raceMarkerPositions([0,20,80]),[0,.25,1,1])})
test('rolling false climb is suppressed while genuine climb displays',()=>{assert.equal(shouldDisplayClimb({authoredClassified:false,averageGradient:.6,elevationGainM:8,distanceKm:1.3}),false);assert.equal(shouldDisplayClimb({authoredClassified:false,averageGradient:5,elevationGainM:100,distanceKm:2}),true)})
test('4.0.20 migration preserves data additively',()=>{const old={onboardingComplete:true,rider:{name:'Rider'},rideHistory:[{id:'x'}]};const migrated=migrateCareer(old as never);assert.equal(migrated.rider.name,'Rider');assert.equal(migrated.rideHistory[0].id,'x')})

test('recovery recommendation is 36 percent at approximately 88 rpm with useful nearby pairings',()=>{const target=resolve({min:95,max:115},{min:85,max:90});assert.deepEqual([target.recommendedCadence,target.recommendedResistance],[88,36]);assert.ok(target.feasibleCombinations.some(pair=>pair.cadence===85&&pair.resistance===37));assert.ok(target.feasibleCombinations.some(pair=>pair.cadence===90&&pair.resistance>=35&&pair.resistance<=36))})
test('recovery, endurance, tempo, threshold and sprint all emit coupled feasible targets',()=>{const cases=[[{min:95,max:115},{min:85,max:90}],[{min:120,max:145},{min:88,max:96}],[{min:150,max:180},{min:86,max:94}],[{min:190,max:220},{min:78,max:88}],[{min:230,max:300},{min:98,max:112}]] as const;for(const [powerRange,cadenceRange] of cases){const target=resolve(powerRange,cadenceRange);assert.ok(target.feasibleCombinations.length>=2);assert.ok(target.resolvedResistanceRange!.max-target.resolvedResistanceRange!.min<=3);for(const pair of target.feasibleCombinations)assert.ok(pair.estimatedPower>=powerRange.min-5&&pair.estimatedPower<=powerRange.max+5)}})
