import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { emptyAlpha4025, ensureHalOffSeasonPlan, generatePlan, HAL_GOALS, HAL_INPUT, HAL_SEPT23_PELOTON } from './alpha4025.ts'
import { recordExternalOffSeasonCompletion } from './adaptiveTraining40251.ts'

test('Hal September 23 Peloton ride completes the original Wednesday assignment on target',()=>{const state=ensureHalOffSeasonPlan(emptyAlpha4025()),assignment=state.trainingPlan!.weeks[0].assignments[2];assert.equal(assignment.id,'w1-d3');assert.equal(assignment.workoutId,'tempo-climb-45');assert.equal(assignment.status,'COMPLETED');assert.equal(assignment.completion?.durationMinutes,45);assert.match(assignment.completion?.notes??'',/ON_TARGET.*RPE 4\/10/);assert.equal(state.adaptive.difficultyEvaluations.find(x=>x.assignmentId==='w1-d3')?.label,'On Target');assert.equal(state.externalCyclingCompletions.length,1)})
test('recorded metrics are exact and spin-up is not FTP, VO2 or anaerobic evidence',()=>{const state=ensureHalOffSeasonPlan(emptyAlpha4025()),activity=state.externalCyclingCompletions[0];assert.deepEqual({duration:activity.durationSeconds,averagePower:activity.averagePowerWatts,peakPower:activity.peakPowerWatts,cadence:activity.averageCadenceRpm,resistance:activity.averageResistancePercent,averageHeartRate:activity.averageHeartRateBpm,maximumHeartRate:activity.maximumHeartRateBpm,output:activity.totalOutputKj,rpe:activity.rpe},{duration:2700,averagePower:151,peakPower:222,cadence:80,resistance:45,averageHeartRate:129,maximumHeartRate:142,output:406,rpe:4});assert.deepEqual(activity.heartRateDistribution.map(x=>[x.zone,x.seconds,x.percent]),[['Z3',1301,48],['Z2',1282,47],['Z1',112,4],['Z4',0,0],['Z5',0,0]]);assert.equal(activity.ftpAssessment,false);assert.equal(HAL_INPUT.ftp,206);for(const zone of ['VO2 Max','Anaerobic'])assert.equal(state.adaptive.zoneDevelopment.find(x=>x.zone===zone)?.level,null)})
test('external completion adds only low-confidence Tempo, Sustained climbing and Endurance evidence',()=>{const state=ensureHalOffSeasonPlan(emptyAlpha4025());for(const zone of ['Tempo','Sustained climbing','Endurance']){const evidence=state.adaptive.zoneDevelopment.find(x=>x.zone===zone)!;assert.equal(evidence.confidence,'Low');assert.equal(evidence.lastEvidenceDate,'2026-09-23');assert.ok(evidence.successfulWorkoutIds.includes('tempo-climb-45'))}assert.equal(state.adaptive.zoneDevelopment.filter(x=>x.level!==null).length,3)})
test('external completion is idempotent and does not change remaining Week 1 workload',()=>{const first=ensureHalOffSeasonPlan(emptyAlpha4025()),second=ensureHalOffSeasonPlan(first),expected=generatePlan(HAL_INPUT,HAL_GOALS).weeks[0].assignments.slice(3).map(x=>[x.id,x.status,x.durationMinutes]);assert.deepEqual(second,first);assert.equal(second.externalCyclingCompletions.length,1);assert.deepEqual(second.trainingPlan!.weeks[0].assignments.slice(3).map(x=>[x.id,x.status,x.durationMinutes]),expected)})
test('manual external completion path requires an existing matching assignment',()=>{const state={...emptyAlpha4025(),trainingPlan:generatePlan(HAL_INPUT,HAL_GOALS)};assert.throws(()=>recordExternalOffSeasonCompletion(state,{...HAL_SEPT23_PELOTON,assignmentId:'new-workout'}),/match an existing/);const context=readFileSync(new URL('../state/CareerContext.tsx',import.meta.url),'utf8');assert.match(context,/recordExternalOffSeasonCompletion\(activity\)/)})
