import test from 'node:test'
import assert from 'node:assert/strict'
import { createInitialCareer, restoreCareerBeforeRender } from '../state/careerPersistence.ts'
import { buildCareerExport } from '../services/previewTransfer.ts'
import type { RiderAccount } from '../services/accountStore.ts'
import { completeOutdoorRide, HAL_SATURDAY_ASSIGNMENT_ID, OUTDOOR_ACTIVITY_ID, outdoorElapsed, pauseOutdoorRide, resumeOutdoorRide, startOutdoorRide } from './outdoorRide40252.ts'

const storage=()=>{const values=new Map<string,string>();return {values,getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)}}}
const defectiveExport=()=>{const career=createInitialCareer();return {format:'ride-the-races-career-export',formatVersion:1,exportedAt:'2026-09-26T08:00:00Z',sourceApplicationVersion:'4.0.25.1',sourceSchemaVersion:6,career:{...career,schemaVersion:6,onboardingComplete:true,rider:{...career.rider,name:'Hal ',number:15,ftp:206,ftpKnown:true,archetype:'GC Contender' as const},alpha4025:{...career.alpha4025,intake:null,developmentProfile:null,questionnaire:null,trainingPlan:null,externalCyclingCompletions:[],outdoorActivities:[],adaptive:{...career.alpha4025.adaptive,zoneDevelopment:[],difficultyEvaluations:[],adaptations:[]},offSeasonUnlocked:false}}}}

test('exact incomplete schema-6 production fixture restores and persists before render',()=>{const fixture=defectiveExport(),memory=storage(),key='career:hal';memory.setItem(key,JSON.stringify(fixture.career));const restored=restoreCareerBeforeRender(memory,key);assert.equal(restored.rider.name,'Hal');assert.equal(restored.rider.number,15);assert.equal(restored.rider.ftp,206);assert.equal(restored.rider.archetype,'GC Contender');assert.equal(restored.alpha4025.intake?.weeklyDays,4);assert.equal(restored.alpha4025.intake?.weeklyMinutes,240);assert.match(restored.alpha4025.developmentProfile?.archetype??'',/GC Contender · Sustained-Power Climber/);assert.equal(restored.alpha4025.trainingPlan?.weeks.length,12);assert.equal(restored.alpha4025.outdoorActivities.filter(x=>x.date==='2026-09-19').length,1);assert.equal(restored.alpha4025.externalCyclingCompletions.filter(x=>x.assignmentId==='w1-d3').length,1);for(const zone of ['Endurance','Tempo','Sustained climbing'])assert.equal(restored.alpha4025.adaptive.zoneDevelopment.find(x=>x.zone===zone)?.confidence,'Low');assert.equal(JSON.parse(memory.values.get(key)!).rider.name,'Hal')})

test('restoration survives reload and is idempotent',()=>{const memory=storage(),key='career:hal';memory.setItem(key,JSON.stringify(defectiveExport().career));const first=restoreCareerBeforeRender(memory,key),firstStored=memory.values.get(key),second=restoreCareerBeforeRender(memory,key);assert.deepEqual(second,first);assert.equal(memory.values.get(key),firstStored);assert.equal(second.alpha4025.outdoorActivities.length,1);assert.equal(second.alpha4025.externalCyclingCompletions.length,1)})

test('identity matching normalizes whitespace and case but still requires number and FTP',()=>{for(const name of [' Hal ','hAL','  HAL   ']){const memory=storage(),career=defectiveExport().career;memory.setItem('key',JSON.stringify({...career,rider:{...career.rider,name}}));assert.equal(restoreCareerBeforeRender(memory,'key').alpha4025.trainingPlan?.weeks.length,12)}for(const patch of [{number:14},{ftp:205}]){const memory=storage(),career=defectiveExport().career;memory.setItem('key',JSON.stringify({...career,rider:{...career.rider,...patch}}));assert.equal(restoreCareerBeforeRender(memory,'key').alpha4025.trainingPlan,null)}})

test('Saturday starts, persists through timestamp reload, resumes without double counting and completes once',()=>{const memory=storage(),key='outdoor';let ride=startOutdoorRide(HAL_SATURDAY_ASSIGNMENT_ID,1_000);memory.setItem(key,JSON.stringify(ride));ride=JSON.parse(memory.getItem(key)!);assert.equal(outdoorElapsed(ride,61_000),60);ride=pauseOutdoorRide(ride,61_000);assert.equal(outdoorElapsed(pauseOutdoorRide(ride,91_000),91_000),60);ride=resumeOutdoorRide(ride,101_000);assert.deepEqual(resumeOutdoorRide(ride,111_000),ride);assert.equal(outdoorElapsed(ride,131_000),90);const career=restoreCareerBeforeRender(storage(),'missing','Hal');const seeded=restoreCareerBeforeRender({...storage(),getItem:()=>JSON.stringify(defectiveExport().career)},'key');const completed=completeOutdoorRide(seeded.alpha4025,ride,{durationSeconds:5400,rpe:4},'2026-09-26T15:00:00Z'),again=completeOutdoorRide(completed,ride,{durationSeconds:5400,rpe:4},'2026-09-26T15:01:00Z');void career;const assignments=again.trainingPlan!.weeks.flatMap(w=>w.assignments).filter(a=>a.id===HAL_SATURDAY_ASSIGNMENT_ID);assert.equal(assignments.length,1);assert.equal(assignments[0].status,'COMPLETED');assert.equal(again.outdoorActivities.filter(a=>a.id===OUTDOOR_ACTIVITY_ID).length,1);assert.equal(again.outdoorActivities.find(a=>a.id===OUTDOOR_ACTIVITY_ID)?.distanceMiles,undefined);assert.deepEqual(again,completed)})

test('safe early end remains on the original assignment and records no fabricated metrics',()=>{const memory=storage();memory.setItem('key',JSON.stringify(defectiveExport().career));const state=restoreCareerBeforeRender(memory,'key').alpha4025,ride=pauseOutdoorRide(startOutdoorRide(HAL_SATURDAY_ASSIGNMENT_ID,1_000),1_801_000),completed=completeOutdoorRide(state,ride,{},'2026-09-26T12:00:00Z',true),activity=completed.outdoorActivities.find(a=>a.id===OUTDOOR_ACTIVITY_ID)!;assert.equal(completed.trainingPlan!.weeks[0].assignments[5].status,'PARTIAL');assert.equal(activity.durationSeconds,1800);for(const field of ['distanceMiles','averageSpeedMph','elevationFeet','averagePowerWatts'])assert.equal(activity[field as keyof typeof activity],undefined)})

test('career export contains restored persisted state and does not mutate it',()=>{const memory=storage();memory.setItem('key',JSON.stringify(defectiveExport().career));const career=restoreCareerBeforeRender(memory,'key'),before=JSON.stringify(career),account={id:'owner',email:'owner@example.test',displayName:'Hal',role:'owner',passwordHash:'x',salt:'y',entitlements:['rtr-standard'],requestedPrograms:[],createdAt:'2026-01-01'} as RiderAccount,payload=buildCareerExport(account,career,null,'4.0.25.1','2026-09-26T18:00:00Z');assert.equal(payload.sourceSchemaVersion,6);assert.equal(payload.career.alpha4025.trainingPlan?.weeks.length,12);assert.equal(payload.career.alpha4025.externalCyclingCompletions.length,1);assert.equal(JSON.stringify(career),before)})
