import test from 'node:test'
import assert from 'node:assert/strict'
import { applyIntroPrescription, calculateFtpFrom20MinuteAverage, createIntroCyclingPlan, introReadiness } from './introCycling.ts'
import type { IntroCyclingAnswers } from '../types/career.ts'
import { trainingRides } from '../data/raceLibrary.ts'

const foundation:IntroCyclingAnswers={cyclingExperience:'New',indoorExperience:'None',outdoorExperience:'None',ftpKnown:false,weeklyDays:2,comfortableMinutes:30,primaryGoal:'Outdoor ride preparation',cadenceResistanceConfidence:'Low',shiftingBrakingConfidence:'Low',bikeAccess:'Both',outdoorConfidence:'Low',limitations:'Knee range requested',preferredNextProgram:'RtR Femmes'}
test('different Intro answers produce meaningfully different starting plans',()=>{const cautious=createIntroCyclingPlan(foundation),confident=createIntroCyclingPlan({...foundation,cyclingExperience:'Returning',ftpKnown:true,weeklyDays:4,comfortableMinutes:45,cadenceResistanceConfidence:'Confident',shiftingBrakingConfidence:'Confident',outdoorConfidence:'Confident',limitations:''});assert.notDeepEqual(cautious,confident);assert.equal(cautious.startingDurationMinutes,30);assert.equal(confident.startingDurationMinutes,45);assert.ok(cautious.powerCeilingPercent<confident.powerCeilingPercent);assert.equal(cautious.instructionDensity,'high');assert.equal(confident.instructionDensity,'standard');const segment={name:'Test',type:'Endurance',zone:'Z2',power:'100–180 W',cadence:'72–105 rpm',resistance:'30–40%',routeKm:0,sec:60,target:'Z2',icon:'🚴',description:'Test',objective:'Test',secondaryObjective:'Test',terrainLabel:'Flat'};assert.deepEqual(applyIntroPrescription([segment],200,cautious).map(item=>[item.power,item.cadence]),[['100–130 W','85–95 rpm']])})
test('completion separates preparation from outdoor certification',()=>{assert.deepEqual(introReadiness(5,5,10),{introComplete:true,indoorProgramReady:true,outdoorPreparationComplete:true,outdoorGroupRideCertified:false,advancedProgramReady:true})})
test('assigned Intro sequence is genuinely authored and beginner-safe',()=>{const plan=createIntroCyclingPlan(foundation);assert.deepEqual(plan.rides.map(ride=>ride.title),['Intro Calibration Ride','Bike and Rhythm Foundations','Cadence and Resistance Control','Preparing for Longer and Outdoor Rides','FTP Warm-Up','RtR 20-Minute FTP Test']);for(const assignment of plan.rides){const ride=trainingRides.find(item=>item.id===assignment.id);assert(ride);assert.equal(ride.name,assignment.title);assert.doesNotMatch(JSON.stringify(ride.stage),/attack|peloton|opener|\brace\b/i)}assert.match(JSON.stringify(trainingRides.find(ride=>ride.id==='intro-outdoor-45')),/Shifting and Braking|Hydration and Fueling|rolling terrain/i)})

test('Intro ends with a separate warm-up and standalone 20-minute FTP assessment',()=>{const plan=createIntroCyclingPlan(foundation),finalTwo=plan.rides.slice(-2);assert.deepEqual(finalTwo.map(ride=>[ride.id,ride.durationMinutes]),[['intro-ftp-warmup-10',10],['intro-ftp-test-20',20]]);const ftpRide=trainingRides.find(ride=>ride.id==='intro-ftp-test-20');assert(ftpRide);assert.equal(ftpRide.stage.segments.length,1);assert.equal(ftpRide.stage.segments[0]?.sec,1200);assert.equal(calculateFtpFrom20MinuteAverage(241),229);assert.throws(()=>calculateFtpFrom20MinuteAverage(20))})
