export type CalibrationSourceType='historical-average'|'manual-calibration'|'live-telemetry'|'imported-ride'
export type SampleConfidence='LOW'|'MEDIUM'|'HIGH'
export type CalibrationConfidence='BASELINE'|'PERSONALIZED'|'CALIBRATED'
export type CalibrationSample={resistance:number;cadence:number;power:number;sourceType:CalibrationSourceType;confidence:SampleConfidence;durationSeconds?:number;timestamp?:string;aggregate:boolean;equipmentId?:string;observedAt?:string}
export type ManualBikeProfile={id:string;manufacturer:string;model:string;resistanceScaleMin:number;resistanceScaleMax:number;calibrationMethod:string;calibrationConfidence:CalibrationConfidence;calibrationSamples:CalibrationSample[];roadLoadCurve:Array<{gradient:number;resistance:number}>}
export type CadencePreferences={comfortableFlatCadence?:number;seatedClimbingCadence?:number;safeMinimumCadence?:number;safeMaximumCadence?:number}
export type EquipmentInstance={id:string;name:string;manufacturer:string;modelFamily:string;resistanceControl:'manual'|'controllable';powerAvailable:boolean;cadenceAvailable:boolean;resistanceAvailable:boolean;calibrationProfileId?:string;calibrationConfidence:'UNAVAILABLE'|CalibrationConfidence;calibrationSamples?:CalibrationSample[]}
export type TargetFeasibility='EXACT'|'ADJUSTED'|'LIMITED'|'UNAVAILABLE'
export type FeasiblePairing={cadence:number;resistance:number;estimatedPower:number}
export type ManualBikeTarget={targetPowerRange:{min:number;max:number};resolvedCadenceRange:{min:number;max:number};resolvedExactResistance:number|null;resolvedResistanceRange:{min:number;max:number}|null;recommendedCadence:number|null;recommendedResistance:number|null;feasibleCombinations:FeasiblePairing[];instructionalToleranceWatts:number;adjustmentGuidance:string;preferredRoadResistance:number|null;predictedPowerRange:{min:number;max:number}|null;feasibility:TargetFeasibility;calibrationConfidence:'UNAVAILABLE'|CalibrationConfidence;cadenceAdjusted:boolean;resistanceAdjusted:boolean;adjustmentReason:string}
export type RoadFeelScale={id:'comfortable'|'realistic'|'full-road'|'custom';scale:number}
export type VirtualRoadLoad={canonicalGradient:number;effectiveGradient:number;roadFeelScale:number;rollingLoad:number;aerodynamicLoad:number;modelConfidence:'REFERENCE'}
export type ManualRoadFeelPrescription={bikeProfile:string;calibrationConfidence:CalibrationConfidence;canonicalGradient:number;effectiveGradient:number;manualResistanceTarget:number;calibrationPowerEstimate:number;powerCompatibleResistance:number}

export const PELOTON_MANUAL_PROFILE:ManualBikeProfile={
 id:'peloton-bike-manual-reference',manufacturer:'Peloton',model:'Bike — manual resistance',resistanceScaleMin:0,resistanceScaleMax:100,
 calibrationMethod:'Device-family reference road-load curve with low-confidence aggregate rider anchors',calibrationConfidence:'BASELINE',
 calibrationSamples:[
  {resistance:35,cadence:100,power:114,sourceType:'manual-calibration',confidence:'MEDIUM',aggregate:true},
  {resistance:39,cadence:97,power:146,sourceType:'manual-calibration',confidence:'MEDIUM',aggregate:true},
  {resistance:45,cadence:94,power:197,sourceType:'manual-calibration',confidence:'MEDIUM',aggregate:true},
  {resistance:54,cadence:76,power:215,sourceType:'manual-calibration',confidence:'MEDIUM',aggregate:true},
  {resistance:62,cadence:67,power:218,sourceType:'manual-calibration',confidence:'MEDIUM',aggregate:true},
 ],
 roadLoadCurve:[{gradient:-15,resistance:20},{gradient:-8,resistance:25},{gradient:-4,resistance:30},{gradient:-1,resistance:36},{gradient:0,resistance:39},{gradient:2,resistance:43},{gradient:4,resistance:47},{gradient:6,resistance:51},{gradient:9,resistance:57},{gradient:12,resistance:63},{gradient:15,resistance:69},{gradient:20,resistance:78}],
}
export const PELOTON_BASELINE_EQUIPMENT:EquipmentInstance={id:'peloton-baseline-bike',name:'Peloton manual bike',manufacturer:'Peloton',modelFamily:'Bike',resistanceControl:'manual',powerAvailable:true,cadenceAvailable:true,resistanceAvailable:true,calibrationProfileId:PELOTON_MANUAL_PROFILE.id,calibrationConfidence:'BASELINE'}
/** Anonymous approved aggregate seed. It is copied onto a rider's selected bike at onboarding/migration. */
export const INITIAL_PELOTON_EQUIPMENT_CALIBRATION:CalibrationSample[]=[{resistance:36,cadence:88,power:105,sourceType:'historical-average',confidence:'LOW',aggregate:true,equipmentId:'peloton-baseline-bike'}]
export const GENERIC_MANUAL_EQUIPMENT:EquipmentInstance={id:'generic-manual-bike',name:'Manual bike',manufacturer:'Other',modelFamily:'Uncalibrated',resistanceControl:'manual',powerAvailable:false,cadenceAvailable:true,resistanceAvailable:true,calibrationConfidence:'UNAVAILABLE'}
export const SMART_EQUIPMENT_FOUNDATION:EquipmentInstance={id:'smart-equipment',name:'Smart equipment',manufacturer:'Other',modelFamily:'Controllable foundation',resistanceControl:'controllable',powerAvailable:true,cadenceAvailable:true,resistanceAvailable:false,calibrationConfidence:'UNAVAILABLE'}
export function bikeProfileForEquipment(equipment:EquipmentInstance):ManualBikeProfile|null{if(equipment.calibrationProfileId!==PELOTON_MANUAL_PROFILE.id)return null;return equipment.calibrationSamples?.length?{...PELOTON_MANUAL_PROFILE,calibrationConfidence:'PERSONALIZED',calibrationSamples:[...PELOTON_MANUAL_PROFILE.calibrationSamples,...equipment.calibrationSamples]}:PELOTON_MANUAL_PROFILE}
export const FULL_ROAD:RoadFeelScale={id:'full-road',scale:1}
const clamp=(value:number,min:number,max:number)=>Math.min(max,Math.max(min,value))
const interpolate=(curve:ManualBikeProfile['roadLoadCurve'],gradient:number)=>{const sorted=[...curve].sort((a,b)=>a.gradient-b.gradient);if(gradient<=sorted[0].gradient)return sorted[0].resistance;if(gradient>=sorted.at(-1)!.gradient)return sorted.at(-1)!.resistance;const right=sorted.find(point=>point.gradient>=gradient)!;const left=sorted[sorted.indexOf(right)-1];return left.resistance+(right.resistance-left.resistance)*(gradient-left.gradient)/(right.gradient-left.gradient)}

/** Reference virtual load, not laboratory physics. Gradient remains canonical while road feel scales only felt load. */
export function resolveVirtualRoadLoad(canonicalGradient:number,roadFeel:RoadFeelScale=FULL_ROAD):VirtualRoadLoad{return {canonicalGradient,effectiveGradient:canonicalGradient*clamp(roadFeel.scale,0,1.25),roadFeelScale:clamp(roadFeel.scale,0,1.25),rollingLoad:1,aerodynamicLoad:0,modelConfidence:'REFERENCE'}}
/** Aggregate anchors approximate the local device response; they are never promoted to synchronized calibration. */
export function estimateBikePower(profile:ManualBikeProfile,resistance:number,cadence:number){
 const exponent=1.55
 const newest=Math.max(...profile.calibrationSamples.map(s=>Date.parse(s.observedAt??s.timestamp??'')||0))
 const raw=profile.calibrationSamples.map(s=>{const date=Date.parse(s.observedAt??s.timestamp??'')||0;const recency=newest&&date?Math.max(.6,1-(newest-date)/(1000*60*60*24*365)*.2):.7;return {resistance:s.resistance,power:s.power/Math.pow(s.cadence/90,exponent),weight:(s.aggregate?.45:1)*(s.confidence==='HIGH'?1:s.confidence==='MEDIUM'?.75:.5)*recency}})
 const points=[...new Set(raw.map(p=>p.resistance))].sort((a,b)=>a-b).map(resistance=>{const matches=raw.filter(p=>p.resistance===resistance),weight=matches.reduce((sum,p)=>sum+p.weight,0);return {resistance,power:matches.reduce((sum,p)=>sum+p.power*p.weight,0)/weight}})
 // Enforce a monotonic equipment curve while retaining additive future samples.
 for(let i=1;i<points.length;i++)points[i].power=Math.max(points[i].power,points[i-1].power)
 const interpolatePower=()=>{if(resistance<=points[0].resistance){const slope=(points[1].power-points[0].power)/(points[1].resistance-points[0].resistance);return Math.max(0,points[0].power+slope*(resistance-points[0].resistance))}if(resistance>=points.at(-1)!.resistance){const a=points.at(-2)!,b=points.at(-1)!;return b.power+(b.power-a.power)/(b.resistance-a.resistance)*(resistance-b.resistance)}const right=points.find(p=>p.resistance>=resistance)!;const left=points[points.indexOf(right)-1];return left.power+(right.power-left.power)*(resistance-left.resistance)/(right.resistance-left.resistance)}
 return Math.max(0,interpolatePower()*Math.pow(Math.max(1,cadence)/90,exponent))
}
export function inverseResistanceForPower(profile:ManualBikeProfile,targetPower:number,targetCadence:number){let best=profile.resistanceScaleMin,bestError=Infinity;for(let resistance=profile.resistanceScaleMin;resistance<=profile.resistanceScaleMax;resistance++){const error=Math.abs(estimateBikePower(profile,resistance,targetCadence)-targetPower);if(error<bestError){best=resistance;bestError=error}}return best}
/** Road load owns the knob target. Power inversion is diagnostic and informs cadence, never terrain. */
export function translateManualRoadFeel(profile:ManualBikeProfile,load:VirtualRoadLoad,targetPower:number,targetCadence:number):ManualRoadFeelPrescription{const manualResistanceTarget=Math.round(clamp(interpolate(profile.roadLoadCurve,load.effectiveGradient),profile.resistanceScaleMin,profile.resistanceScaleMax));return {bikeProfile:profile.id,calibrationConfidence:profile.calibrationConfidence,canonicalGradient:load.canonicalGradient,effectiveGradient:load.effectiveGradient,manualResistanceTarget,calibrationPowerEstimate:Math.round(estimateBikePower(profile,manualResistanceTarget,targetCadence)),powerCompatibleResistance:inverseResistanceForPower(profile,targetPower,targetCadence)}}

/** Reconciles physiology, terrain and device response in safety-first order. */
export function resolveManualBikeTarget(input:{powerRange:{min:number;max:number};cadenceRange:{min:number;max:number};gradient:number;equipment:EquipmentInstance;profile:ManualBikeProfile|null;preferences?:CadencePreferences}):ManualBikeTarget{
 const safeMin=input.preferences?.safeMinimumCadence??60,safeMax=input.preferences?.safeMaximumCadence??120
 const preferredCadence=input.gradient>2?input.preferences?.seatedClimbingCadence:input.preferences?.comfortableFlatCadence
 const width=input.cadenceRange.max-input.cadenceRange.min
 const proposed=preferredCadence===undefined?input.cadenceRange:{min:preferredCadence-width/2,max:preferredCadence+width/2}
 const cadence={min:Math.round(clamp(proposed.min,safeMin,safeMax)),max:Math.round(clamp(proposed.max,safeMin,safeMax))};if(cadence.max<cadence.min)cadence.max=cadence.min
 const cadenceAdjusted=cadence.min!==input.cadenceRange.min||cadence.max!==input.cadenceRange.max
 const unavailable={recommendedCadence:null,recommendedResistance:null,feasibleCombinations:[] as FeasiblePairing[],instructionalToleranceWatts:5,adjustmentGuidance:'Ride to power and cadence; manual resistance guidance is unavailable.'}
 if(!input.profile)return {targetPowerRange:input.powerRange,resolvedCadenceRange:cadence,resolvedExactResistance:null,resolvedResistanceRange:null,preferredRoadResistance:null,predictedPowerRange:null,feasibility:'UNAVAILABLE',calibrationConfidence:input.equipment.calibrationConfidence,cadenceAdjusted,resistanceAdjusted:false,adjustmentReason:'No compatible device calibration; resistance guidance unavailable.',...unavailable}
 const preferred=Math.round(clamp(interpolate(input.profile.roadLoadCurve,input.gradient),input.profile.resistanceScaleMin,input.profile.resistanceScaleMax))
 const predicted=(resistance:number)=>({min:Math.round(estimateBikePower(input.profile!,resistance,cadence.min)),max:Math.round(estimateBikePower(input.profile!,resistance,cadence.max))})
 let resistance=preferred,power=predicted(resistance)
 const overlaps=()=>power.max>=input.powerRange.min&&power.min<=input.powerRange.max
 const feasibleWindow=(start:number)=>{const feasible:number[]=[];for(let candidate=input.profile!.resistanceScaleMin;candidate<=input.profile!.resistanceScaleMax;candidate++){const range=predicted(candidate);if(range.max>=input.powerRange.min&&range.min<=input.powerRange.max)feasible.push(candidate)}if(!feasible.length)return null;const low=clamp(start-1,feasible[0],feasible.at(-1)!);return {min:Math.round(low),max:Math.round(Math.min(low+3,feasible.at(-1)!))}}
 const decorate=(window:{min:number;max:number},reason:string,feasibility:TargetFeasibility)=>{const midpoint=(input.powerRange.min+input.powerRange.max)/2,cadenceMidpoint=(cadence.min+cadence.max)/2;const candidates:FeasiblePairing[]=[];for(let c=cadence.min;c<=cadence.max;c++)for(let r=window.min;r<=window.max;r++){const estimatedPower=Math.round(estimateBikePower(input.profile!,r,c));if(estimatedPower>=input.powerRange.min-5&&estimatedPower<=input.powerRange.max+5)candidates.push({cadence:c,resistance:r,estimatedPower})}candidates.sort((a,b)=>Math.abs(a.cadence-cadenceMidpoint)-Math.abs(b.cadence-cadenceMidpoint)||b.cadence-a.cadence||a.resistance-b.resistance||Math.abs(a.estimatedPower-midpoint)-Math.abs(b.estimatedPower-midpoint));const recommended=candidates.find(p=>p.estimatedPower>=input.powerRange.min&&p.estimatedPower<=input.powerRange.max)??candidates[0]??{cadence:Math.round(cadenceMidpoint),resistance,estimatedPower:Math.round(estimateBikePower(input.profile!,resistance,cadenceMidpoint))};const atCadence=(value:number)=>candidates.filter(p=>p.cadence===value).sort((a,b)=>Math.abs(a.estimatedPower-midpoint)-Math.abs(b.estimatedPower-midpoint))[0];const combinations=[recommended,atCadence(cadence.min),atCadence(cadence.max)].filter((p,index,all):p is FeasiblePairing=>Boolean(p)&&all.findIndex(item=>item?.cadence===p?.cadence&&item?.resistance===p?.resistance)===index).slice(0,3);return {targetPowerRange:input.powerRange,resolvedCadenceRange:cadence,resolvedExactResistance:recommended.resistance,resolvedResistanceRange:window,recommendedCadence:recommended.cadence,recommendedResistance:recommended.resistance,feasibleCombinations:combinations,instructionalToleranceWatts:5,adjustmentGuidance:'LOW: +1 · HIGH: −1',preferredRoadResistance:preferred,predictedPowerRange:power,feasibility,calibrationConfidence:input.profile!.calibrationConfidence,cadenceAdjusted,resistanceAdjusted:recommended.resistance!==preferred,adjustmentReason:reason}}
 if(overlaps()){const window=feasibleWindow(resistance)!;resistance=Math.round(clamp(resistance,window.min,window.max));return decorate(window,cadenceAdjusted?'Cadence preference applied within safe limits.':'Recommended pairing matches the prescribed power.',cadenceAdjusted?'ADJUSTED':'EXACT')}
 const midpoint=(input.powerRange.min+input.powerRange.max)/2
 resistance=inverseResistanceForPower(input.profile,midpoint,(cadence.min+cadence.max)/2);power=predicted(resistance)
 const feasible=overlaps()
 const window=feasibleWindow(resistance)
 return decorate(window??{min:resistance,max:resistance},feasible?'Resistance adjusted to make cadence and power agree.':'Safe calibrated limits cannot fully overlap the power objective.',feasible?'ADJUSTED':'LIMITED')
}

/** A future telemetry adapter must observe a sustained excursion before prompting. */
export class PowerAdjustmentGate{private outsideSince:number|null=null;private readonly dwellSeconds:number;private readonly toleranceWatts:number;constructor(dwellSeconds=6,toleranceWatts=5){this.dwellSeconds=dwellSeconds;this.toleranceWatts=toleranceWatts}update(power:number,target:{min:number;max:number},elapsed:number){if(power>=target.min-this.toleranceWatts&&power<=target.max+this.toleranceWatts){this.outsideSince=null;return false}this.outsideSince??=elapsed;return elapsed-this.outsideSince>=this.dwellSeconds}}

export type StableTelemetryWindow={samples:Array<{resistance:number;cadence:number;power:number;timestamp:number}>;minimumDurationSeconds:number;maximumVariation:{resistance:number;cadence:number;power:number}}
export function calibrationSampleFromStableWindow(window:StableTelemetryWindow):CalibrationSample|null{if(window.samples.length<2)return null;const duration=(window.samples.at(-1)!.timestamp-window.samples[0].timestamp)/1000;const values=(key:'resistance'|'cadence'|'power')=>window.samples.map(sample=>sample[key]);const stable=(key:'resistance'|'cadence'|'power',limit:number)=>Math.max(...values(key))-Math.min(...values(key))<=limit;if(duration<window.minimumDurationSeconds||!stable('resistance',window.maximumVariation.resistance)||!stable('cadence',window.maximumVariation.cadence)||!stable('power',window.maximumVariation.power))return null;const average=(key:'resistance'|'cadence'|'power')=>values(key).reduce((sum,value)=>sum+value,0)/values(key).length;return {resistance:average('resistance'),cadence:average('cadence'),power:average('power'),sourceType:'live-telemetry',confidence:'HIGH',durationSeconds:duration,timestamp:new Date(window.samples.at(-1)!.timestamp).toISOString(),aggregate:false}}

/** Future Jean calls may use this deterministic threshold/cooldown gate; 4.0.18 keeps guidance visual. */
export class ManualResistanceAnnouncementGate{private lastTarget:number|null=null;private lastAt=-Infinity;private readonly minimumChange:number;private readonly cooldownSeconds:number;constructor(minimumChange=4,cooldownSeconds=45){this.minimumChange=minimumChange;this.cooldownSeconds=cooldownSeconds}shouldAnnounce(target:number,elapsedSeconds:number){const useful=this.lastTarget===null||Math.abs(target-this.lastTarget)>=this.minimumChange;const ready=elapsedSeconds-this.lastAt>=this.cooldownSeconds;if(!useful||!ready)return false;this.lastTarget=target;this.lastAt=elapsedSeconds;return true}reset(){this.lastTarget=null;this.lastAt=-Infinity}}
