import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { trainingRides } from '../data/raceLibrary.ts'
import { createStageTimeline } from './stageEngine.ts'
import { completeSessionTime, coordinatedDistance, effortLanguage, noFtpPresentation } from './release4024.ts'
import { PELOTON_BASELINE_EQUIPMENT } from './manualBike.ts'

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8')
const calibration=trainingRides.find(ride=>ride.id==='intro-calibration')!
test('ordinary Intro effort is language while calibration checkpoints retain numeric RPE capture',()=>{assert.equal(effortLanguage('RPE 1–2 / 10'),'VERY EASY');assert.equal(effortLanguage('RPE 2–3 / 10'),'EASY');assert.equal(effortLanguage('RPE 3–4 / 10'),'COMFORTABLE');assert.equal(effortLanguage('RPE 4–5 / 10'),'MODERATE');const ordinary=noFtpPresentation(calibration.stage.segments[0],PELOTON_BASELINE_EQUIPMENT);assert.equal(ordinary.effort,'VERY EASY');assert.equal(ordinary.rpe,'RPE 1–2');const checkpoints=calibration.stage.segments.filter(segment=>segment.zone==='RPE CHECK');assert.equal(checkpoints.length,2);assert.match(JSON.stringify(checkpoints),/How hard did that feel from 1–10/i);assert.match(read('../screens/RideScreen.tsx'),/recordIntroRpe\(value\)/)})
test('30-minute calibration includes 27 structured minutes and three-minute cooldown continuously',()=>{const timeline=createStageTimeline(calibration.stage.segments,calibration.stage.distanceKm);assert.equal(timeline.raceFinishTime,27*60);assert.equal(timeline.duration,30*60);for(const [at,expected] of [[0,1800],[1,1799],[1620,180],[1799,1],[1800,0]] as const){const view=completeSessionTime(timeline.duration,at);assert.equal(view.remaining,expected);assert.equal(view.elapsed,at)}for(const at of [600,1700,1800])assert.deepEqual(completeSessionTime(timeline.duration,at),structuredClone(completeSessionTime(timeline.duration,at)))})
test('training terminology and one expanded hide control coexist with race terminology',()=>{const ride=read('../screens/RideScreen.tsx');assert.match(ride,/stage\.isTraining\?'SESSION':'STAGE'/);assert.match(ride,/stage\.isTraining\?'Restart Ride':'Restart Stage'/);assert.equal((ride.match(/▲ Hide Ride Details/g)??[]).length,1);assert.match(ride,/WORKOUT COMPLETE/);assert.match(ride,/Restart Stage/)})
test('coordinated distance rounding never exceeds total and finishes exactly',()=>{let prior=Infinity;for(let step=0;step<=100;step++){const view=coordinatedDistance(29.9338,29.9338*step/100,true);assert.equal(view.traveledTenths+view.remainingTenths,view.totalTenths);assert.ok(view.remainingTenths<=prior);prior=view.remainingTenths}const finish=coordinatedDistance(29.9338,29.9338,true);assert.equal(finish.traveled,finish.total);assert.equal(finish.remaining,'0.0 mi');assert.deepEqual(finish,structuredClone(finish))})
test('dashboard names Intro to Cycling and handles unknown FTP without percentages or race recovery copy',()=>{const hq=read('../screens/TeamHQScreen.tsx');assert.match(hq,/FTP NOT SET/);assert.match(hq,/RPE-BASED TARGETS/);assert.match(hq,/Intro to Cycling/);assert.match(read('./alpha4025.ts'),/Ready for today’s session|Keep the effort comfortable/);assert.doesNotMatch(hq,/Intro Cycling/);assert.match(hq,/introOnly/)})
test('briefing guidance, persistent folder return, tracker type and safe areas are protected',()=>{const preview=read('../components/StageSectionPreview.tsx'),app=read('../App.tsx'),library=read('../screens/RaceLibraryScreen.tsx'),ride=read('../screens/RideScreen.tsx'),css=read('../App.css');assert.match(preview,/JEAN’S GUIDANCE:/);assert.match(preview,/training\?'JEAN’S GUIDANCE:'/);assert.match(library,/rtr-training-folder/);assert.match(app,/Back to Intro to Cycling/);assert.match(app,/Back to Recovery Rides/);assert.match(ride,/font-size:clamp\(\.68rem,2\.8vw,\.84rem\)/);assert.match(css,/safe-area-inset-top/);assert.match(css,/safe-area-inset-bottom/);assert.match(library,/activeTrainingFolder===null/);assert.match(library,/library!=='training'\|\|activeTrainingFolder===null/)})
test('safe no-FTP resistance remains nonzero',()=>{for(const segment of calibration.stage.segments){const target=noFtpPresentation(segment,PELOTON_BASELINE_EQUIPMENT);assert.doesNotMatch(`${target.resistance}`,/^0–/);assert.match(target.resistance,/%/)}})
