import assert from 'node:assert/strict'
import test from 'node:test'
import { readFileSync } from 'node:fs'
const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8')
test('iPhone viewport and bounded safe-area contract protect mobile pages',()=>{const html=read('../../index.html'),root=read('../index.css'),app=read('../App.css'),ride=read('../screens/RideScreen.tsx');assert.match(html,/viewport-fit=cover/);assert.match(root,/--safe-top:\s*max\(env\(safe-area-inset-top, 0px\), 12px\)/);assert.match(app,/onboarding-screen[^}]*var\(--safe-top\)/);assert.match(app,/race-briefing-screen[^}]*scroll-padding-top:var\(--safe-top\)/);assert.match(ride,/top: var\(--safe-top\)/);assert.match(ride,/padding: var\(--safe-top\) 10px/);assert.doesNotMatch(root,/--safe-top:[^;]*(?:40|50|60)px/)})
test('dark headings, connection structure, and floating clearance are explicit',()=>{const app=read('../App.css'),screen=read('../screens/OnboardingScreen.tsx');assert.match(app,/onboarding-header h1[^}]*color:#fff/);assert.match(app,/onboarding-card h2,.onboarding-card h3[^}]*color:#fff/);assert.match(screen,/connection-status/);assert.match(screen,/connection-description/);assert.match(screen,/status:'Available now'/);assert.match(app,/global-unit-toggle[^}]*right: max\(14px, var\(--safe-right\)\)/);assert.match(app,/global-unit-toggle \{ top: calc\(var\(--safe-top\) \+ 4px\); right: var\(--safe-right\)/)})
test('rider UI never exposes authored duration and distinguishes recommended from selected',()=>{for(const path of ['../screens/StageDetailScreen.tsx','../screens/TacticsScreen.tsx','../screens/RideScreen.tsx']){const source=read(path);assert.doesNotMatch(source,/AUTHORED BASE|indoorDurationMinutes/)}const detail=read('../screens/StageDetailScreen.tsx');assert.match(detail,/RECOMMENDED RIDE/);assert.match(detail,/SELECTED COURSE DURATION/);assert.match(detail,/customMinutes/);assert.match(read('../App.tsx'),/durationSelection=\{ride\?\.stageNumber===selectedStageNumber/)})
test('cockpit navigation and badges stay in flow with safe touch targets',()=>{const ride=read('../screens/RideScreen.tsx');assert.match(ride,/ride-topbar" aria-label="Cockpit navigation"/);assert.match(ride,/className="leave-cockpit"/);assert.match(ride,/leave-cockpit \{ min-width:44px; min-height:44px/);assert.match(ride,/cockpit-badges \{ justify-content:flex-start; width:100%/);assert.doesNotMatch(ride,/leave-cockpit[^}]*position:\s*(?:fixed|sticky|absolute)/)})
test('wake lock is requested, truthfully reported, released, and reacquired',()=>{const ride=read('../screens/RideScreen.tsx');assert.match(ride,/setWakeLockStatus\('requesting'\)[\s\S]*wakeLock\.request/);assert.match(ride,/activeRide\.resume\(\)\s*\n\s*void requestWakeLock\(\)/);assert.match(ride,/visibilityState === 'visible'[\s\S]*requestWakeLock/);assert.match(ride,/visibilityState!==\s*'visible'\)void releaseWakeLock/);assert.match(ride,/Wake lock unsupported · Keep Auto-Lock disabled/);assert.match(ride,/Wake lock unavailable · Keep Auto-Lock disabled/);assert.match(ride,/setWakeLockStatus\('released'\)/);assert.match(ride,/wakeLockStatus === 'active'[\s\S]*'Screen awake'/)})
test('mobile cockpit applies one effective full-Safari top offset',()=>{const root=read('../index.css'),app=read('../App.css'),ride=read('../screens/RideScreen.tsx');assert.match(root,/@media \(max-width: 700px\)[\s\S]*--safe-top: max\(env\(safe-area-inset-top, 0px\), 48px\)/);assert.match(app,/app:has\(\.ride-cockpit\)[^{]*\{[^}]*padding-top: 0/);assert.match(ride,/\.ride-cockpit \{[\s\S]*padding: var\(--safe-top\) 10px/);assert.match(ride,/leave-cockpit \{ min-width:44px; min-height:44px/);assert.doesNotMatch(ride,/\.ride-topbar[^}]*transform|\.ride-topbar[^}]*margin-top:\s*-/)})
