import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { generatePlan, HAL_GOALS, HAL_INPUT } from './alpha4025.ts'
import { validExecutableWorkout, workoutById, workoutSections } from './adaptiveTraining40251.ts'
import { getLibraryStage } from '../data/raceLibrary.ts'

test('all 12-week cycling assignments reference complete executable curated workouts',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),cycling=plan.weeks.flatMap(w=>w.assignments).filter(a=>a.type==='CYCLING'||a.type==='ASSESSMENT');assert.equal(cycling.length,24);for(const assignment of cycling){assert.ok(assignment.workoutId,`${assignment.id} lacks workoutId`);const workout=workoutById(assignment.workoutId!);assert.ok(workout,`${assignment.id} references missing ${assignment.workoutId}`);assert.equal(assignment.durationMinutes,workout!.durationMinutes,`${assignment.id} displayed duration differs`);assert.equal(validExecutableWorkout(workout!),true,`${workout!.id} sections are incomplete`);const sections=workoutSections(workout!);assert.equal(sections.reduce((n,s)=>n+s.durationSeconds,0),workout!.durationMinutes*60);for(const section of sections){assert.ok(section.zone&&section.rpe&&section.cadence&&section.resistance&&section.jean);if(workout!.ftpRange)assert.ok(section.ftpRange);assert.doesNotMatch(section.jean,/attack|peloton|KOM|race|sprint/i)}const stage=getLibraryStage('training',0,workout!.id);assert.ok(stage?.isTraining);assert.equal(stage!.segments.reduce((n,s)=>n+s.sec,0),workout!.durationMinutes*60)}})
test('quality assignment opens a complete briefing and existing cockpit execution path',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),quality=plan.weeks.flatMap(w=>w.assignments).find(a=>a.demandingCycling)!;assert.ok(quality.workoutId);const stage=getLibraryStage('training',0,quality.workoutId);assert.ok(stage?.segments.length);const offSeason=readFileSync(new URL('../screens/OffSeasonScreen.tsx',import.meta.url),'utf8'),briefing=readFileSync(new URL('../screens/TacticsScreen.tsx',import.meta.url),'utf8'),app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8'),ride=readFileSync(new URL('../screens/RideScreen.tsx',import.meta.url),'utf8');assert.match(offSeason,/Start Ride — Open Workout Briefing/);assert.match(briefing,/START RIDE/);assert.match(app,/setSelectedOffSeasonAssignment/);for(const token of ['CURRENT','UP NEXT','Pause','Resume'])assert.match(ride,new RegExp(token,'i'))})
test('today quality prescription is exact and fully timed',()=>{const plan=generatePlan(HAL_INPUT,HAL_GOALS),assignment=plan.weeks.flatMap(w=>w.assignments).find(a=>a.demandingCycling)!,workout=workoutById(assignment.workoutId!)!,sections=workoutSections(workout);assert.equal(workout.title,'Controlled Climbing Tempo');assert.equal(workout.durationMinutes,45);assert.deepEqual([workout.repetitions,workout.workIntervalMinutes,workout.recoveryIntervalMinutes],[3,8,4]);assert.deepEqual(workout.ftpRange,[.76,.86]);assert.equal(Math.round(206*.76),157);assert.equal(Math.round(206*.86),177);assert.equal(workout.fueling,'Quality');assert.equal(sections.reduce((n,s)=>n+s.durationSeconds,0),2700)})
test('execution wiring preserves assignment identity for completion and abandonment',()=>{const context=readFileSync(new URL('../state/CareerContext.tsx',import.meta.url),'utf8'),app=readFileSync(new URL('../App.tsx',import.meta.url),'utf8');assert.match(context,/recordOffSeasonAssignment/);assert.match(context,/status==='PARTIAL'/);assert.match(context,/original assignment preserved/);assert.match(context,/fourWeekPreview\(updated\)/);assert.match(app,/recordOffSeasonAssignment\(selectedOffSeasonAssignment/);assert.match(app,/'COMPLETED'/);assert.match(app,/'PARTIAL'/)})
test('authenticated Training Library exposes every enabled folder including Off-Season',()=>{const source=readFileSync(new URL('../screens/RaceLibraryScreen.tsx',import.meta.url),'utf8');for(const folder of ['Recovery Rides','Intro to Cycling','Classic Rides','Outdoor Ride Readiness','Off-Season Training'])assert.match(source,new RegExp(folder));assert.match(source,/onOpenOffSeason/);assert.doesNotMatch(source,/training-folder-row[^>]*disabled/)})
