import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { OUTDOOR_ENDURANCE_90_SECTIONS,OUTDOOR_ENDURANCE_90_SECONDS,outdoorElapsed,outdoorWorkoutSnapshot,pauseOutdoorRide,resumeOutdoorRide,startOutdoorRide } from './outdoorRide40252.ts'

const read=(path:string)=>readFileSync(new URL(path,import.meta.url),'utf8')
test('Start Outdoor Ride opens briefing and its primary action launches the existing cockpit',()=>{const app=read('../App.tsx'),off=read('../screens/OffSeasonScreen.tsx'),briefing=read('../screens/OutdoorBriefingScreen.tsx'),ride=read('../screens/RideScreen.tsx');assert.match(off,/Start Outdoor Ride/);assert.match(app,/outdoorBriefing/);assert.match(briefing,/START OUTDOOR RIDE/);assert.match(app,/outdoorMode/);assert.match(ride,/function StandardRideScreen/);assert.match(ride,/OutdoorRideCockpit/)})
test('persisted timestamp clock survives background, pause, resume and reload without double counting',()=>{let ride=startOutdoorRide('w1-d6',1_000);assert.equal(outdoorElapsed(ride,61_000),60);ride=structuredClone(ride);assert.equal(outdoorElapsed(ride,121_000),120);ride=pauseOutdoorRide(ride,121_000);assert.equal(outdoorElapsed(pauseOutdoorRide(ride,181_000),181_000),120);ride=JSON.parse(JSON.stringify(ride));ride=resumeOutdoorRide(ride,201_000);assert.deepEqual(resumeOutdoorRide(ride,211_000),ride);assert.equal(outdoorElapsed(ride,231_000),150)})
test('warm-up, endurance and cooldown are exactly 90 minutes and advance Current and Up Next',()=>{assert.deepEqual(OUTDOOR_ENDURANCE_90_SECTIONS.map(section=>[section.title,section.durationSeconds]),[['Warm-up',600],['Aerobic Endurance',4200],['Cooldown',600]]);assert.equal(OUTDOOR_ENDURANCE_90_SECONDS,5400);assert.deepEqual([outdoorWorkoutSnapshot(0).current.title,outdoorWorkoutSnapshot(0).upNext?.title],['Warm-up','Aerobic Endurance']);assert.deepEqual([outdoorWorkoutSnapshot(600).current.title,outdoorWorkoutSnapshot(600).upNext?.title],['Aerobic Endurance','Cooldown']);assert.deepEqual([outdoorWorkoutSnapshot(4800).current.title,outdoorWorkoutSnapshot(4800).upNext],['Cooldown',null]);assert.equal(outdoorWorkoutSnapshot(5400).complete,true)})
test('training/outdoor cockpit has no race geography and active ride has no measurement form',()=>{const ride=read('../screens/RideScreen.tsx'),completion=read('../screens/OutdoorCompletionScreen.tsx'),outdoor=ride.slice(ride.indexOf('function OutdoorRideCockpit'),ride.indexOf('function StandardRideScreen'));assert.match(outdoor,/training\/outdoor/);assert.match(outdoor,/CURRENT INTERVAL/);assert.match(outdoor,/UP NEXT/);assert.match(outdoor,/TOTAL ELAPSED/);assert.match(outdoor,/End Early Safely/);for(const forbidden of ['KILOMETRE ZERO','breakaway','ATTACK','race position','distanceKm'])assert.doesNotMatch(outdoor,new RegExp(forbidden,'i'));for(const field of ['distanceMiles','averageHeartRate','averagePowerWatts']){assert.doesNotMatch(outdoor,new RegExp(field));assert.match(completion,new RegExp(field))}})
test('completion sheet follows completed or confirmed early-ending lifecycle and race cockpit stays intact',()=>{const app=read('../App.tsx'),ride=read('../screens/RideScreen.tsx');assert.match(app,/onOutdoorCompletion/);assert.match(app,/outdoorCompletion/);assert.match(app,/completeOutdoorRide\(old,outdoor\.ride!/);assert.match(ride,/window\.confirm\('End this outdoor workout early/);assert.match(ride,/RACE_STAGE/);assert.match(ride,/KILOMETRE ZERO/);assert.match(ride,/WorldsGroupMarkers/)})
test('outdoor mobile cockpit retains safe areas, readable hierarchy and 44px controls at supported widths',()=>{const css=read('../App.css');assert.match(css,/safe-area-inset-bottom/);assert.match(css,/outdoor-cockpit-controls button\{min-height:52px/);for(const width of [320,375,390,430])assert.ok(width<=430);assert.match(css,/@media\(max-width:430px\).*outdoor-cockpit/)})
