import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { currentOutdoorJeanCue,nextOutdoorJeanCue,outdoorResumeMessage,OUTDOOR_EARLY_END_MESSAGE,OUTDOOR_JEAN_CUES,OUTDOOR_PAUSE_MESSAGE } from './outdoorJean40252.ts'
import { outdoorElapsed,pauseOutdoorRide,resumeOutdoorRide,startOutdoorRide } from './outdoorRide40252.ts'

test('coaching timeline contains every prescribed active-elapsed cue exactly once',()=>{assert.deepEqual(OUTDOOR_JEAN_CUES.map(cue=>cue.atSeconds),[0,300,600,1200,1800,2100,2700,3300,3900,4200,4800,5100,5400]);assert.equal(new Set(OUTDOOR_JEAN_CUES.map(cue=>cue.id)).size,OUTDOOR_JEAN_CUES.length);assert.match(currentOutdoorJeanCue(600).text,/Begin seventy minutes/);assert.match(currentOutdoorJeanCue(4800).text,/Begin ten minutes easy/)})
test('paused wall-clock time advances neither workout nor coaching',()=>{let ride=startOutdoorRide('w1-d6',1_000);ride=pauseOutdoorRide(ride,301_000);assert.equal(outdoorElapsed(ride,901_000),300);assert.equal(currentOutdoorJeanCue(outdoorElapsed(ride,901_000)).id,'warmup-check');ride=resumeOutdoorRide(ride,901_000);assert.equal(outdoorElapsed(ride,1_201_000),600);assert.equal(currentOutdoorJeanCue(outdoorElapsed(ride,1_201_000)).id,'begin-endurance')})
test('delivered cues survive reload and suspension consumes backlog but returns only latest',()=>{const atTen=nextOutdoorJeanCue(600,[]);assert.equal(atTen.cue?.id,'begin-endurance');assert.deepEqual(atTen.consumedIds,['start','warmup-check','begin-endurance']);assert.equal(nextOutdoorJeanCue(600,atTen.consumedIds).cue,null);const reloaded=JSON.parse(JSON.stringify({deliveredJeanCueIds:atTen.consumedIds}));assert.equal(nextOutdoorJeanCue(2200,reloaded.deliveredJeanCueIds).cue?.id,'fuel-35');assert.equal(nextOutdoorJeanCue(2200,reloaded.deliveredJeanCueIds).consumedIds.includes('technique'),true)})
test('pause resume and early-end coaching are safe and retain elapsed time',()=>{const ride=pauseOutdoorRide(startOutdoorRide('w1-d6',1_000),61_000),elapsed=outdoorElapsed(ride,500_000);assert.equal(elapsed,60);assert.match(OUTDOOR_PAUSE_MESSAGE,/safe/);assert.match(outdoorResumeMessage('Warm-up',5340,'RPE 2–3, Easy'),/Warm-up.*89 minutes.*RPE 2–3, Easy/);assert.match(OUTDOOR_EARLY_END_MESSAGE,/safely stopped/)})
test('mute and unsupported speech affect audio only while visual cue and timer remain independent',()=>{const screen=readFileSync(new URL('../screens/RideScreen.tsx',import.meta.url),'utf8'),voice=readFileSync(new URL('../services/jeanVoice.ts',import.meta.url),'utf8');assert.match(screen,/career\.settings\.jeanVoiceEnabled&&!ride\?\.jeanMuted/);assert.match(screen,/visualCue\.text/);assert.match(screen,/Mute Jean/);assert.match(voice,/unsupported/);assert.doesNotMatch(readFileSync(new URL('./outdoorJean40252.ts',import.meta.url),'utf8'),/latitude|longitude|speed|distance|weather|power/i)})
