import test from 'node:test'
import assert from 'node:assert/strict'
import { adaptSunday, generatePlan, HAL_GOALS, HAL_INPUT, projectReadiness, type ReadinessEntry } from './alpha4025.ts'
import { readFileSync } from 'node:fs'
const current:ReadinessEntry={date:'2026-09-19',updatedAt:'2026-09-19T23:30:00-07:00',source:'WHOOP manual entry',sleepHours:7.5,externalRecoveryScore:82,recentStrain:15.1,fatigue:'Low',soreness:'None',motivation:'High',hydrationConcern:false,illnessOrPain:false,recommendedAdjustment:''}
test('local calendar date keeps today current and exposes categorical status without composite',()=>{const view=projectReadiness(current,'2026-09-19','OFF_SEASON');assert.equal(view.stale,false);assert.equal(view.status,'Ready');assert.equal(view.adjustment,'Ready for planned training.');assert.equal('score'in view,false)})
test('one phase-aware projection never leaks race language',()=>{assert.equal(projectReadiness(current,'2026-09-19','INTRO').adjustment,'Ready for today’s session.');assert.equal(projectReadiness(current,'2026-09-19','RACING').adjustment,'Ready to race.');assert.doesNotMatch(projectReadiness({...current,fatigue:'Moderate'},'2026-09-19','OFF_SEASON').adjustment,/race/i)})
test('stale data is labeled and cannot adapt Sunday',()=>{const stale=projectReadiness(current,'2026-09-22','OFF_SEASON');assert.equal(stale.stale,true);assert.equal(stale.canAdaptTraining,false);assert.match(stale.adjustment,/3 days old/);const saturday=generatePlan(HAL_INPUT,HAL_GOALS).weeks[0].assignments[5];assert.equal(adaptSunday(saturday,current,'2026-09-22').level,'NO_CHANGE')})
test('Team HQ and Off-Season render the same authoritative projection and no legacy circle',()=>{const hq=readFileSync(new URL('../screens/TeamHQScreen.tsx',import.meta.url),'utf8'),off=readFileSync(new URL('../screens/OffSeasonScreen.tsx',import.meta.url),'utf8');assert.match(hq,/projectReadiness/);assert.match(off,/projectReadiness/);assert.doesNotMatch(hq,/readiness-ring|Race with discipline/);assert.match(hq,/No composite physiological score/);assert.match(off,/No composite physiological score/)})
test('owner transfer and readiness mobile contracts cover supported widths',()=>{const css=readFileSync(new URL('../App.css',import.meta.url),'utf8'),settings=readFileSync(new URL('../screens/SettingsScreen.tsx',import.meta.url),'utf8');for(const width of [320,375,390,430])assert.ok(width<=430&&css.includes('@media(max-width:430px)'));assert.match(settings,/CAREER DATA TRANSFER/);assert.match(css,/overflow-wrap:anywhere/);assert.match(css,/min-height:44px/)})
test('End Season is gated by genuine active season and active rides on rendered calendar',()=>{const calendar=readFileSync(new URL('../screens/SeasonCalendarScreen.tsx',import.meta.url),'utf8'),context=readFileSync(new URL('../state/CareerContext.tsx',import.meta.url),'utf8');assert.match(calendar,/career\.season\.active\?/);assert.match(calendar,/End Season is unavailable during an active ride/);assert.match(calendar,/stages are incomplete/);assert.match(context,/if\(!current\.season\.active\|\|current\.season\.closure\.status==='ENDED'\)return current/);assert.match(context,/offSeasonUnlocked:true/)})
