import test from 'node:test'
import assert from 'node:assert/strict'
import { trainingRides } from '../data/raceLibrary.ts'
import { adaptSegments } from './adaptiveRide.ts'
import { createRoadModel } from './roadModel.ts'
import { bikeProfileForEquipment, GENERIC_MANUAL_EQUIPMENT, PELOTON_BASELINE_EQUIPMENT, SMART_EQUIPMENT_FOUNDATION } from './manualBike.ts'
import { applyRideCorrection, coachingContext, cueAllowed, activeSeasonClosure, closeSeason, noFtpTarget, normalizeJeanCopy, originalTargetsAvailable, prescriptionSnapshot, wakeLockMessage } from './release4024.ts'
import { tacticalPrescription } from './alpha4021.ts'
import { getRaceStage } from '../data/raceStages.ts'
import { readFileSync } from 'node:fs'

const equipment=[PELOTON_BASELINE_EQUIPMENT,GENERIC_MANUAL_EQUIPMENT,SMART_EQUIPMENT_FOUNDATION]
test('authoritative preview snapshot becomes exact active snapshot for every equipment mode',()=>{for(const ride of [...trainingRides,getRaceStage(10) as never] as typeof trainingRides[number][]) {const stage='stage'in ride?ride.stage:ride;const segments=adaptSegments(stage.segments,206,'Balanced'),model=createRoadModel(stage.number,segments,stage.distanceKm);for(let index=0;index<segments.length-1;index++){for(const bike of equipment){const at=model.segmentStarts[index+1],preview=tacticalPrescription(model.roadSnapshot(at).livePrescription,1,bike,bikeProfileForEquipment(bike)),active=tacticalPrescription(model.roadSnapshot(at).livePrescription,1,bike,bikeProfileForEquipment(bike)),a=prescriptionSnapshot(index+1,segments[index+1],preview),b=prescriptionSnapshot(index+1,segments[index+1],active);assert.deepEqual({...a,reason:b.reason},b,`${stage.title}: ${segments[index+1].name}: ${bike.id}`)}}}})
test('named phone-evidence boundaries preserve power cadence resistance identity zone and duration',()=>{for(const name of ['Easy Endurance','Steady Recovery','Cadence Focus','Cadence Change','Easy Start']){const ride=trainingRides.find(item=>item.stage.segments.some(segment=>segment.name===name))!,index=ride.stage.segments.findIndex(segment=>segment.name===name),model=createRoadModel(ride.stage.number,adaptSegments(ride.stage.segments,206,'Balanced'),ride.stage.distanceKm),at=model.segmentStarts[index];const before=prescriptionSnapshot(index,ride.stage.segments[index],model.roadSnapshot(at).livePrescription),after=prescriptionSnapshot(index,ride.stage.segments[index],model.roadSnapshot(at+.001).livePrescription);assert.deepEqual(before,after)}})
test('no FTP never emits zero watts or zero-percent ordinary work',()=>{const segment=trainingRides.find(r=>r.id==='intro-foundations-30')!.stage.segments[0];const peloton=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT),manual=noFtpTarget(segment,GENERIC_MANUAL_EQUIPMENT),smart=noFtpTarget(segment,SMART_EQUIPMENT_FOUNDATION);for(const target of [peloton,manual,smart]){assert.doesNotMatch(`${target.power} ${target.resistance}`,/0–0 W|0–3%/);assert.match(target.rpe,/RPE/)}assert.equal(peloton.resistance,'25–30%');assert.equal(manual.resistance,'Light–Moderate load');assert.equal(smart.resistance,'Light load')})
test('Jean contexts reject race language and normalize only duplicate titles',()=>{for(const ride of trainingRides){const context=coachingContext('training',ride.id);assert.equal(cueAllowed(context,'Sprint done. Find the group and settle'),false);for(const segment of ride.stage.segments)assert.notEqual(normalizeJeanCopy(segment.name,`${segment.name}. ${segment.name}`),`${segment.name}. ${segment.name}`)}assert.equal(cueAllowed(coachingContext('tour-2026',undefined,true),'Find the group'),true);assert.equal(normalizeJeanCopy('Easy Endurance','Easy endurance is sustainable.'),'Easy endurance is sustainable.')})
test('season closure is confirmed upstream, immutable, idempotent and preserves snapshot',()=>{const active=activeSeasonClosure(),first=closeSeason(active,{now:'2026-09-15T00:00:00Z',finalStageCompleted:21,ownerEarlyEnd:false,results:{points:42}}),again=closeSeason(first,{now:'later',finalStageCompleted:0,ownerEarlyEnd:true,results:{}});assert.equal(first.status,'ENDED');assert.equal(first.handoffStatus,'READY_FOR_REVIEW');assert.equal(first.offSeasonFolderLocked,true);assert.deepEqual(again,first)})
test('wake lock copy is truthful for supported denied unavailable lost and restored states',()=>{assert.equal(wakeLockMessage('active'),'Screen will stay awake during your ride');for(const state of ['inactive','requesting','unsupported','blocked','released'] as const)assert.equal(wakeLockMessage(state),'Disable Auto-Lock to keep the cockpit visible')})

test('immutable original target snapshots survive current FTP and rule changes',()=>{const segment=trainingRides.find(r=>r.id==='recovery-30')!.stage.segments[0],model=createRoadModel(30,adaptSegments([segment],206,'Balanced'),1),resolved=tacticalPrescription(model.roadSnapshot(0).livePrescription,1,PELOTON_BASELINE_EQUIPMENT,bikeProfileForEquipment(PELOTON_BASELINE_EQUIPMENT)),stored={...prescriptionSnapshot(0,segment,resolved),sectionIndex:0,equipmentId:'peloton',equipmentMode:'PELOTON_COMPATIBLE',calibrationConfidence:'BASELINE',ftp:206,ftpProvenance:'RIDER_ENTERED' as const,tacticalModifier:1,ruleVersion:'alpha4024.2'};const current=createRoadModel(30,adaptSegments([segment],260,'Balanced'),1).roadSnapshot(0).livePrescription;assert.notEqual(current.power,stored.power);assert.equal(structuredClone(stored).power,stored.power);assert.equal(originalTargetsAvailable({targetSnapshots:[stored]}),true);assert.equal(originalTargetsAvailable({}),false)})

test('ride corrections preserve identity, immutable original and authored snapshots',()=>{const snapshot={authoredId:'section-0',resolvedId:'resolved',name:'Stage',duration:60,zone:'Z2',power:'100–120 W',cadence:'70–80 rpm',resistance:'25–30%',reason:'SECTION_BOUNDARY' as const,sectionIndex:0,equipmentId:'bike',equipmentMode:'PELOTON_COMPATIBLE',calibrationConfidence:'BASELINE',ftp:200,ftpProvenance:'RIDER_ENTERED' as const,tacticalModifier:1,ruleVersion:'alpha4024.2'},ride={id:'original',date:'2026-01-01',source:'Manual' as const,durationMinutes:60,distanceKm:100,averagePower:150,peakPower:300,averageHeartRate:140,maximumHeartRate:180,targetSnapshots:[snapshot]},edited=applyRideCorrection(ride,{durationMinutes:62,distanceKm:101,averagePower:155,peakPower:310,averageHeartRate:142,maximumHeartRate:181,rpe:6,notes:'corrected',equipmentId:'new-bike'},'2026-02-01');assert.equal(edited.id,'original');assert.equal(edited.durationMinutes,60);assert.equal(edited.correctedEntry?.durationMinutes,62);assert.equal(edited.originalUserEntry?.averagePower,150);assert.deepEqual(edited.targetSnapshots,ride.targetSnapshots);assert.throws(()=>applyRideCorrection(ride,{averagePower:400,peakPower:300},'now'))})

test('calibration baseline deterministically adjusts no-FTP targets without becoming FTP',()=>{const segment=trainingRides.find(r=>r.id==='intro-foundations-30')!.stage.segments[1],baseline=(rpe:number,steps=2)=>({rpe,cadence:70,load:'controlled',completedSteps:steps,recordedAt:'2026-01-01',ruleVersion:'alpha4024.2'});const before=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT),incomplete=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT,baseline(2,1)),high=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT,baseline(8)),appropriate=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT,baseline(5)),low=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT,baseline(2)),reloaded=noFtpTarget(segment,PELOTON_BASELINE_EQUIPMENT,structuredClone(baseline(2)));assert.equal(before.resistance,'25–30%');assert.equal(incomplete.resistance,before.resistance);assert.equal(high.resistance,'23–28%');assert.equal(appropriate.resistance,'25–30%');assert.equal(low.resistance,'27–32%');assert.deepEqual(reloaded,low);assert.equal(high.readyForNextRide,false);assert.equal(low.readyForNextRide,true);for(const bike of equipment)assert.doesNotMatch(JSON.stringify(noFtpTarget(segment,bike,baseline(8))),/0–0 W|0–3%/)})

test('current and past season result routes are explicit and replay cannot mutate closure snapshot',()=>{const stageDetail=readFileSync(new URL('../screens/StageDetailScreen.tsx',import.meta.url),'utf8'),bus=readFileSync(new URL('../screens/TeamBusScreen.tsx',import.meta.url),'utf8');assert.match(stageDetail,/Stage Results/);assert.match(bus,/Past Seasons/);assert.match(bus,/Stage Results/);const closure=closeSeason(activeSeasonClosure(),{now:'2026-01-01',finalStageCompleted:21,ownerEarlyEnd:false,results:{points:99}}),copy=structuredClone(closure);assert.deepEqual(closure,copy)})
