import assert from 'node:assert/strict'
import test from 'node:test'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { ChaseDecisionCard, layoutRaceMarkers, ProfileDetail4022, WorldsGroupMarkers, TacticalStatusStrip } from '../components/WorldsRaceLayer.ts'
import { chaseLifecycle, meaningfulTerrainChange, mergeTerrainBlocks, montrealRoadStory, nextMeaningfulBoundary } from './alpha4022.ts'
import { resolveTacticalTransition } from './tacticalActions.ts'
import { tacticalPrescription } from './alpha4021.ts'
import { PELOTON_BASELINE_EQUIPMENT, bikeProfileForEquipment } from './manualBike.ts'
import { worldsStage } from '../data/uciWorlds2026.ts'
import { createRoadModel } from './roadModel.ts'
import { raceIdentities } from '../data/raceLibrary.ts'

const chase=montrealRoadStory[2],preview={power:'187–205 W',cadence:'86–94 rpm',resistance:'45–48%',start:'START 46% @ 90 RPM'}
test('clustered race labels render bounded leader lanes at all iPhone checkpoints',()=>{for(const width of [320,375,390,430])for(const progress of [.01,.05,.09,.17,.25,.3,.35,.65,.98]){const markers=layoutRaceMarkers(chase,progress,width),html=renderToStaticMarkup(createElement(WorldsGroupMarkers,{event:chase,courseProgress:progress,pixelWidth:width}));for(const marker of markers){assert(marker.labelPx>=30&&marker.labelPx<=width-30);assert(marker.anchorPx>=8&&marker.anchorPx<=width-8)}assert.match(html,/group-label-compact/);assert.match(html,/<i><\/i>/);assert(markers.find(m=>m.id==='breakaway')!.position>markers.find(m=>m.id==='chase')!.position);assert(markers.find(m=>m.id==='chase')!.position>progress);assert(markers.find(m=>m.id==='peloton')!.position<progress)}})
test('terrain construction merges noise and caps mobile detail at five blocks',()=>{const merged=mergeTerrainBlocks(Array.from({length:12},(_,index)=>({start:index/12,end:(index+1)/12,gradient:index<6?index*.1:2+index*.2,name:`Road ${index}`})));assert(merged.length<=5);assert.equal(meaningfulTerrainChange(0,.1),false);assert.equal(meaningfulTerrainChange(0,.6),true)})
test('next meaningful boundary counts down and is not FINISH early',()=>{const blocks=[{start:0,end:2,gradient:0,name:'South Shore'},{start:2,end:4,gradient:1.2,name:'Bridge'},{start:4,end:6,gradient:3,name:'Mount Royal'}];const distances=[.2,.8,1.5,1.99].map(position=>nextMeaningfulBoundary(blocks,position,10));assert(distances.every(item=>item.name==='Bridge'&&!item.finish));assert(distances.every((item,index)=>!index||item.distance<distances[index-1].distance));assert.equal(nextMeaningfulBoundary(blocks,9.9,10).name,'FINISH')})
test('Detail stays a single overlay with at most five rendered terrain blocks',()=>{const state={mode:'DETAIL' as const,activeRangeId:'terrain',autoConsumedIds:[]};const blocks=mergeTerrainBlocks(Array.from({length:9},(_,i)=>({start:i/9,end:(i+1)/9,gradient:i,name:`B${i}`})));const html=renderToStaticMarkup(createElement(ProfileDetail4022,{state,progress:.4,gradientBlocks:blocks,gradientIndex:2,currentGradient:2,nextGradient:3,nextName:'Mount Royal',changeDistance:'0.4 mi',resistance:'45–48%'}));assert.equal((html.match(/flex-basis/g)??[]).length<=5,true);assert.match(html,/POSITION IN VIEW/);assert.doesNotMatch(html,/>RIDER /)})
test('response window and bounded effort duration are distinct',()=>{assert(chase.responseWindowSeconds>=15&&chase.responseWindowSeconds<=30);assert(chase.effortDurationSeconds>=30&&chase.effortDurationSeconds<=90);assert.notEqual(chase.responseWindowSeconds,chase.effortDurationSeconds)})
test('one resolved Chase prescription is harder, narrow and suitable for preview and cockpit',()=>{const stage=worldsStage('road'),road=createRoadModel(2,stage.segments,stage.distanceKm,raceIdentities['worlds-2026'],stage.profilePoints,stage.officialCourseMarkers,stage.raceId,208,PELOTON_BASELINE_EQUIPMENT),base=road.roadSnapshot(road.duration*.3).livePrescription,resolved=tacticalPrescription(base,chase.preview.powerMultiplier,PELOTON_BASELINE_EQUIPMENT,bikeProfileForEquipment(PELOTON_BASELINE_EQUIPMENT));assert(resolved.powerRange.min>=base.powerRange.min);assert(resolved.powerRange.max>base.powerRange.max);assert(resolved.resistanceRange.max-resolved.resistanceRange.min<=3);const visible={power:resolved.power,cadence:resolved.cadence,resistance:resolved.resistance.replace(/ · Start \d+%/,''),start:`START ${resolved.manualTarget.recommendedResistance}% @ ${resolved.manualTarget.recommendedCadence} RPM`};const html=renderToStaticMarkup(createElement(ChaseDecisionCard,{event:chase,responseRemaining:20,preview:visible,onAccept:()=>{},onHold:()=>{}}));for(const value of Object.values(visible))assert.match(html,new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')))})
test('offered and active tactical presentations cannot coexist',()=>{const offered=renderToStaticMarkup(createElement(ChaseDecisionCard,{event:chase,responseRemaining:18,preview,onAccept:()=>{},onHold:()=>{}})),active=renderToStaticMarkup(createElement(TacticalStatusStrip,{state:'ACTIVE',remaining:51})),returning=renderToStaticMarkup(createElement(TacticalStatusStrip,{state:'RETURNING',remaining:32}));assert.match(offered,/CHASE<\/button>/);assert.doesNotMatch(active,/button|HOLD POSITION/);assert.doesNotMatch(returning,/button|CHASE ACTIVE/)})
test('Chase lifecycle covers decline, reload, return and completion without reopening',()=>{assert.equal(chaseLifecycle({effortDurationSeconds:60,elapsed:0}),'OFFERED');assert.equal(chaseLifecycle({decision:'declined',effortDurationSeconds:60,elapsed:0}),'DECLINED');assert.equal(chaseLifecycle({decision:'accepted',activeStartedAt:100,effortDurationSeconds:60,elapsed:130}),'ACTIVE');assert.equal(chaseLifecycle({decision:'accepted',activeStartedAt:100,effortDurationSeconds:60,returnStartedAt:160,elapsed:180}),'RETURNING');assert.equal(chaseLifecycle({decision:'accepted',activeStartedAt:100,effortDurationSeconds:60,returnStartedAt:160,elapsed:205}),'COMPLETE')})
test('Return reaches the exact current baseline at zero',()=>{const state=resolveTacticalTransition('RETURNING_TO_PELOTON',{startedAt:100,durationSeconds:45,from:'CHASING',progress:0},145);assert.equal(state.state,'PELOTON');assert.equal(state.effortMultiplier,1);assert.equal(state.transition,null)})
