/* eslint-disable react-hooks/set-state-in-effect -- watcher lifecycle intentionally updates acquisition state. */
import { useEffect,useRef,useState } from 'react'
import { loadGoogleMaps,locationErrorStatus,locationFixAgeSeconds,verifiedLocationFix,type GeolocationLike,type LocationStatus,type VerifiedLocationFix } from '../services/outdoorLocation.ts'

type GoogleMap={setCenter:(point:{lat:number;lng:number})=>void}
type GoogleMapsApi={Map:new(element:HTMLElement,options:Record<string,unknown>)=>GoogleMap;Marker:new(options:Record<string,unknown>)=>{setPosition:(point:{lat:number;lng:number})=>void};Circle:new(options:Record<string,unknown>)=>{setCenter:(point:{lat:number;lng:number})=>void;setRadius:(radius:number)=>void}}
const apiKey=((import.meta as ImportMeta&{env?:{VITE_GOOGLE_MAPS_API_KEY?:string}}).env?.VITE_GOOGLE_MAPS_API_KEY??'').trim()

export default function OutdoorLocationMap({enabled,onEnable,onDisable}:{enabled:boolean;onEnable:()=>void;onDisable:()=>void}){
 const [status,setStatus]=useState<LocationStatus>(enabled?'Stale':'Disabled'),[fix,setFix]=useState<VerifiedLocationFix|null>(null),[now,setNow]=useState(0),[mapError,setMapError]=useState('')
 const mapElement=useRef<HTMLDivElement|null>(null),map=useRef<GoogleMap|null>(null),marker=useRef<{setPosition:(point:{lat:number;lng:number})=>void}|null>(null),circle=useRef<{setCenter:(point:{lat:number;lng:number})=>void;setRadius:(radius:number)=>void}|null>(null)
 useEffect(()=>{if(!enabled){setStatus('Disabled');setFix(null);return}setStatus(current=>current==='Disabled'?'Acquiring':'Stale');if(!window.isSecureContext||!navigator.geolocation){setStatus('Unavailable');return}const geolocation=navigator.geolocation as GeolocationLike,id=geolocation.watchPosition(position=>{setFix(verifiedLocationFix(position));setStatus('Active')},error=>setStatus(locationErrorStatus(error.code)),{enableHighAccuracy:true,maximumAge:0,timeout:20000});return()=>geolocation.clearWatch(id)},[enabled])
 useEffect(()=>{if(!enabled)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[enabled])
 useEffect(()=>{if(!enabled||!fix||!mapElement.current)return;if(!apiKey){setMapError('Map unavailable — workout timer continues');return}let active=true;loadGoogleMaps(apiKey).then(()=>{if(!active||!mapElement.current)return;const maps=(globalThis as typeof globalThis&{google:{maps:GoogleMapsApi}}).google.maps,point={lat:fix.latitude,lng:fix.longitude};if(!map.current){map.current=new maps.Map(mapElement.current,{center:point,zoom:16,disableDefaultUI:true,zoomControl:true});marker.current=new maps.Marker({map:map.current,position:point,title:'Verified rider location'});if(fix.accuracy!==null)circle.current=new maps.Circle({map:map.current,center:point,radius:fix.accuracy,fillColor:'#4285f4',fillOpacity:.14,strokeColor:'#4285f4',strokeOpacity:.7,strokeWeight:1})}else{marker.current?.setPosition(point);if(fix.accuracy!==null&&!circle.current)circle.current=new maps.Circle({map:map.current,center:point,radius:fix.accuracy,fillColor:'#4285f4',fillOpacity:.14,strokeColor:'#4285f4',strokeOpacity:.7,strokeWeight:1});circle.current?.setCenter(point);if(fix.accuracy!==null)circle.current?.setRadius(fix.accuracy)}}).catch(()=>active&&setMapError('Map unavailable — workout timer continues'));return()=>{active=false}},[enabled,fix])
 const age=locationFixAgeSeconds(fix,now),displayedStatus:LocationStatus=status==='Active'&&age!==null&&age>30?'Stale':status,recenter=()=>{if(fix)map.current?.setCenter({lat:fix.latitude,lng:fix.longitude})}
 return <section className="outdoor-map-card" aria-label="Live rider location"><header><div><p className="eyebrow">LIVE LOCATION · {displayedStatus.toUpperCase()}</p><small>{age===null?'No verified location fix':`Latest verified fix: ${age}s ago`}</small></div>{enabled?<button type="button" onClick={onDisable}>Disable Live Location</button>:<button type="button" onClick={onEnable}>Enable Live Location</button>}</header>{enabled&&<details open className="outdoor-map-collapse"><summary>Google Map</summary><div className="outdoor-map" ref={mapElement}/>{(!apiKey||mapError)&&<p className="map-fallback" role="status">Map unavailable — workout timer continues</p>}{fix&&apiKey&&!mapError&&<button type="button" onClick={recenter}>Recenter on Me</button>}<small>Location is held in active memory only. No route, turns, distance, speed or elevation are recorded. Background GPS continuity is not guaranteed.</small></details>}</section>
}
