import { createElement as h } from 'react'
import type { RaceSituation, ProfileViewState } from '../engine/alpha4022.ts'
import type { GradientSection } from '../engine/gradientRoad.ts'

export type GroupMarker={id:'breakaway'|'chase'|'peloton';label:string;position:number;gap:string}
export function situationGroups(event:RaceSituation,courseProgress:number):GroupMarker[]{const hasBreak=/BREAKAWAY|FAVORITES/.test(event.groupState),hasChase=/CHASE/.test(event.groupState);return [...(hasBreak?[{id:'breakaway' as const,label:/FAVORITES/.test(event.groupState)?'FAVORITES':'BREAKAWAY',position:Math.min(.985,courseProgress+.045),gap:event.simulatedGap}]:[]),...(hasChase?[{id:'chase' as const,label:'CHASE GROUP',position:Math.min(.97,courseProgress+.022),gap:'AUTHORED'}]:[]),{id:'peloton' as const,label:/REDUCED|SELECTED/.test(event.groupState)?'REDUCED PELOTON':'PELOTON',position:Math.max(.015,courseProgress-.035),gap:'SIMULATED'}]}
const tag=(name:string,value:string)=>h('span',null,h('small',null,name),h('strong',null,value))
export function WorldsGroupMarkers({event,courseProgress,viewStart=0,viewWidth=100}:{event:RaceSituation;courseProgress:number;viewStart?:number;viewWidth?:number}){return h('div',{className:'worlds-group-layer','aria-label':'Authored race-position groups'},...situationGroups(event,courseProgress).map(group=>h('span',{key:group.id,className:`worlds-group-marker ${group.id}`,style:{left:`${((group.position*100-viewStart)/viewWidth)*100}%`}},h('b',null,group.label),h('i'),h('small',null,group.gap))))}
export function ProfileViewControl({state,onToggle}:{state:ProfileViewState;onToggle:()=>void}){return h('button',{type:'button',className:'profile-view-control','aria-label':`Switch profile to ${state.mode==='DETAIL'?'Overview':'Detail'} view`,onClick:onToggle},state.mode==='DETAIL'?'OVERVIEW':'DETAIL')}
export function ProfileDetail4022(props:{state:ProfileViewState;event?:RaceSituation;progress:number;gradientBlocks:GradientSection[];gradientIndex:number;currentGradient:number;nextGradient:number|null;distanceToTransition:number;resistance:string}){
 const {state,event,progress,gradientBlocks,gradientIndex,currentGradient,nextGradient,distanceToTransition,resistance}=props
 if(state.mode!=='DETAIL')return null
 const phase=event?.id.replace('mtl-','').replaceAll('-',' ').toUpperCase()??'TERRAIN DETAIL'
 const blocks=gradientBlocks.map((block,index)=>h('div',{key:index,className:index===gradientIndex?'active':index<gradientIndex?'complete':'',style:{flexBasis:`${Math.max(8,(block.end-block.start)*100)}%`}},h('small',null,`${Math.round(block.start*100)}–${Math.round(block.end*100)}%`),h('strong',null,`${block.gradient}%`),index===gradientIndex?h('i',{style:{left:`${Math.max(0,Math.min(100,((progress-block.start)/Math.max(.001,block.end-block.start))*100))}%`}},'▲'):null))
 return h('section',{className:'profile-detail-4022','aria-label':'Contextual profile Detail'},h('header',null,h('div',null,h('small',null,`DETAIL · ${state.activeRangeId??'MANUAL'}`),h('strong',null,phase)),h('span',null,event?'TACTICAL EFFORT':'CANONICAL TERRAIN')),h('div',{className:'detail-gradient-summary'},tag('CURRENT',`${currentGradient.toFixed(1)}% ${currentGradient>.3?'UPHILL':currentGradient<-.3?'DOWNHILL':'FLAT'}`),tag('NEXT',nextGradient===null?'FINISH':`${nextGradient.toFixed(1)}%`),tag('TRANSITION',`${distanceToTransition.toFixed(2)} km`),tag('RESISTANCE',resistance)),h('div',{className:'detail-gradient-blocks','aria-label':'Ordered canonical gradient boundaries'},...blocks),h('footer',null,h('strong',null,`RIDER COORDINATE ${(progress*100).toFixed(1)}%`),h('span',null,`NEXT: ${nextGradient===null?'FINISH':`${nextGradient.toFixed(1)}% gradient`}`)))
}
export function ChaseDecisionCard({event,active,preview,onAccept,onHold}:{event:RaceSituation;active:boolean;preview?:{power:string;cadence:string;resistance:string;start:string};onAccept:()=>void;onHold:()=>void}){if(!event.actions.includes('CHASE'))return null;return h('aside',{className:`chase-decision-card${active?' active':''}`,'aria-label':active?'Active Chase prescription':'Chase preview'},h('p',{className:'eyebrow'},active?'CHASE ACTIVE':'CHASE OPPORTUNITY'),h('h3',null,event.caption),h('div',null,tag('POWER',preview?.power??`BASE × ${event.preview.powerMultiplier.toFixed(2)}`),tag('CADENCE',preview?.cadence??`${event.preview.cadence} RPM`),tag('DURATION',`${event.preview.durationSeconds}s`),tag('RESISTANCE',preview?.resistance??'ACTIVE PELOTON PROFILE')),preview?.start?h('p',null,preview.start):null,active?h('p',null,h('strong',null,'TACTICAL EFFORT · targets changed')):h('footer',null,h('button',{type:'button',onClick:onAccept},'CHASE'),h('button',{type:'button',onClick:onHold},'HOLD POSITION')))}
