import { createElement as h } from 'react'
import type { RaceSituation, ProfileViewState } from '../engine/alpha4022.ts'

export type GroupMarker={id:'breakaway'|'chase'|'peloton';label:string;position:number;gap:string}
export function situationGroups(event:RaceSituation,courseProgress:number):GroupMarker[]{const hasBreak=/BREAKAWAY|FAVORITES/.test(event.groupState),hasChase=/CHASE/.test(event.groupState);return [...(hasBreak?[{id:'breakaway' as const,label:/FAVORITES/.test(event.groupState)?'FAVORITES':'BREAKAWAY',position:Math.min(.998,courseProgress+.045),gap:event.simulatedGap}]:[]),...(hasChase?[{id:'chase' as const,label:'CHASE GROUP',position:Math.min(.99,courseProgress+.022),gap:'AUTHORED'}]:[]),{id:'peloton' as const,label:/REDUCED|SELECTED/.test(event.groupState)?'REDUCED PELOTON':'PELOTON',position:Math.max(.002,courseProgress-.035),gap:'SIMULATED'}]}
const tag=(name:string,value:string)=>h('span',null,h('small',null,name),h('strong',null,value))
export function layoutRaceMarkers(event:RaceSituation,courseProgress:number,width:number){return situationGroups(event,courseProgress).map((group,index)=>{const anchorPx=Math.max(8,Math.min(width-8,group.position*width));return {...group,anchorPx,labelPx:Math.max(30,Math.min(width-30,anchorPx+(index%2?-18:18))),lane:index}})}
export function WorldsGroupMarkers({event,courseProgress,viewStart=0,viewWidth=100,pixelWidth=375}:{event:RaceSituation;courseProgress:number;viewStart?:number;viewWidth?:number;pixelWidth?:number}){const groups=layoutRaceMarkers(event,courseProgress,pixelWidth);return h('div',{className:'worlds-group-layer','aria-label':'Race groups'},...groups.map(group=>{const anchor=Math.max(2,Math.min(98,((group.position*100-viewStart)/viewWidth)*100)),short=group.id==='breakaway'?'B':group.id==='peloton'?'P':'C';return h('span',{key:group.id,className:`worlds-group-marker ${group.id}`,style:{left:`${anchor}%`},'aria-label':group.label},h('b',{style:{transform:`translateX(calc(-50% + ${group.labelPx-group.anchorPx}px))`}},short),h('i'))}))}
export function ProfileViewControl({state,onToggle}:{state:ProfileViewState;onToggle:()=>void}){return h('button',{type:'button',className:'profile-view-control','aria-label':`Switch profile to ${state.mode==='DETAIL'?'Overview':'Detail'} view`,'aria-pressed':state.mode==='DETAIL',onClick:onToggle},state.mode==='DETAIL'?'SHOW OVERVIEW':'SHOW DETAIL')}
export function WorldsOverviewLabels(){return h('div',{className:'worlds-overview-labels','aria-label':'Road Race overview'},h('strong',null,'12× MOUNT ROYAL'))}
export function CalibrationHelper({resistance,cadence}:{resistance:number;cadence:number;guidance?:string}){return h('div',{className:'next-line calibration-helper'},h('strong',null,`START ${resistance}% @ ${cadence} RPM`))}
export function LiveTrackerLabel({worlds,training=false}:{worlds:boolean;training?:boolean}){return h('p',{className:'eyebrow'},training?'LIVE WORKOUT TRACKER':worlds?'LIVE RACE TRACKER':'LIVE STAGE TRACKER')}
export function LiveTrackerHeader4023({worlds,training=false,section,zone}:{worlds:boolean;training?:boolean;section:string;zone:string}){return h('header',{className:'live-tracker-4023','aria-label':'Live tracker'},h('strong',null,training?'LIVE WORKOUT TRACKER':worlds?'LIVE RACE TRACKER':'LIVE STAGE TRACKER'),h('span',null,section),h('b',null,zone))}
export function formatChampionshipDate(iso:string){return new Intl.DateTimeFormat('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'}).format(new Date(`${iso}T00:00:00Z`)).toUpperCase()}
export function WorldsHeroTitle({children}:{children:string}){return h('h1',{className:'worlds-hero-title',style:{color:'#fff'}},children)}
export function ProfileStatusHeader({worlds,training=false,completion,remaining,completionText}:{worlds:boolean;training?:boolean;completion:number;remaining:string;completionText?:string}){return h('div',{className:'live-profile-head profile-status-regions'},h(LiveTrackerLabel,{worlds,training}),h('div',{className:'profile-progress-row'},h('strong',{className:'profile-completion'},completionText??`${Math.round(completion)}% COMPLETE`),h('strong',{className:'profile-remaining'},`${remaining} left`)))}
export function mobileProfileRegions(width:number){const padding=22,gap=12,finishWidth=58,remainingWidth=Math.min(104,Math.floor(width*.3));return {completion:{left:padding,right:width-padding-gap-remainingWidth,top:0,bottom:34},remaining:{left:width-padding-remainingWidth,right:width-padding,top:0,bottom:34},finish:{left:width-padding-finishWidth,right:width-padding,top:44,bottom:88}}}
export function ProfileDetail4022(props:{state:ProfileViewState;event?:RaceSituation;progress:number;gradientBlocks:Array<{start:number;end:number;gradient:number}>;gradientIndex:number;currentGradient:number;nextGradient:number|null;nextName?:string;changeDistance:string|null;resistance:string;context?:string}){
 const {state,progress,currentGradient,nextGradient,nextName='ROAD AHEAD',changeDistance,resistance,context='COURSE'}=props
 if(state.mode!=='DETAIL')return null
 return h('section',{className:'profile-detail-4022','aria-label':'Profile Detail'},h('div',{className:'detail-gradient-summary'},tag('CURRENT',`${currentGradient.toFixed(1)}% ${currentGradient>.3?'UP':currentGradient<-.3?'DOWN':'FLAT'}`),tag('NEXT',`${nextName}${nextGradient===null?'':` · ${nextGradient.toFixed(1)}%`}`),changeDistance===null?null:tag(changeDistance==='CHANGE NOW'?'CHANGE':'CHANGE IN',changeDistance==='CHANGE NOW'?'NOW':changeDistance),tag('RESISTANCE',resistance),tag('POSITION',context)),h('span',{className:'sr-only'},`POSITION IN VIEW ${(progress*100).toFixed(1)}%`))
}
export function ChaseDecisionCard({event,responseRemaining,preview,onAccept,onHold,actionLabel='CHASE'}:{event:RaceSituation;responseRemaining:number;preview:{power:string;cadence:string;resistance:string;start:string};onAccept:()=>void;onHold:()=>void;actionLabel?:'CHASE'|'ATTACK'}){return h('aside',{className:'chase-decision-card','aria-label':`${actionLabel} preview`},h('p',{className:'eyebrow'},`${actionLabel} · DECIDE 0:${String(Math.max(0,Math.ceil(responseRemaining))).padStart(2,'0')}`),h('h3',null,event.caption),h('div',null,tag('POWER',preview.power),tag('CADENCE',preview.cadence),tag('RESISTANCE',preview.resistance),tag('EFFORT',`${event.effortDurationSeconds}s`)),h('footer',null,h('button',{type:'button',onClick:onAccept},actionLabel),h('button',{type:'button',onClick:onHold},'HOLD POSITION')))}
export function TacticalStatusStrip({state,remaining}:{state:'ACTIVE'|'RETURNING';remaining:number}){return h('div',{className:'tactical-status-strip',role:'status'},`${state==='ACTIVE'?'CHASE ACTIVE':'RETURNING TO PELOTON'} · ${Math.max(0,Math.ceil(remaining))}s`)}
