import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { emptyAlpha4025, ensureHalOffSeasonPlan, generatePlan, HAL_BASELINE, HAL_GOALS, HAL_SEPT23_PELOTON, HAL_INPUT } from '../src/engine/alpha4025.ts'
const first=ensureHalOffSeasonPlan(emptyAlpha4025()),second=ensureHalOffSeasonPlan(first)
assert.equal(first.offSeasonUnlocked,false);assert.equal(first.trainingPlan?.weeks.length,12);assert.deepEqual(second,first);assert.equal(first.outdoorActivities.filter(x=>x.id===HAL_BASELINE.id).length,1);assert.equal(first.externalCyclingCompletions.filter(x=>x.id===HAL_SEPT23_PELOTON.id).length,1);assert.equal(first.trainingPlan?.weeks[0].assignments[2].status,'COMPLETED');assert.equal(first.adaptive.difficultyEvaluations.find(x=>x.assignmentId==='w1-d3')?.label,'On Target')
const hq=readFileSync(new URL('../src/screens/TeamHQScreen.tsx',import.meta.url),'utf8'),bus=readFileSync(new URL('../src/screens/TeamBusScreen.tsx',import.meta.url),'utf8'),offseason=readFileSync(new URL('../src/screens/OffSeasonScreen.tsx',import.meta.url),'utf8'),app=readFileSync(new URL('../src/App.tsx',import.meta.url),'utf8'),card=readFileSync(new URL('../src/components/OffSeasonPreviewButton.ts',import.meta.url),'utf8')
for(const source of [hq,bus,offseason,app])assert.match(source,/isAuthenticated/);for(const token of ['PREVIEW ACCESS','Start date:','Plan length:','Open Off-Season Plan'])assert.match(card,new RegExp(token));assert.doesNotMatch(card,/🔒/);assert.match(app,/screen==='offseason'&&!isAuthenticated/)
const executable=generatePlan(HAL_INPUT,HAL_GOALS).weeks.flatMap(w=>w.assignments).filter(a=>a.type==='CYCLING'||a.type==='ASSESSMENT');assert.equal(executable.length,24);assert.ok(executable.every(a=>a.workoutId));const weekOne=generatePlan(HAL_INPUT,HAL_GOALS).weeks[0];assert.equal(weekOne.assignments.filter(a=>a.durationMinutes>0).length,4);assert.equal(weekOne.assignments.reduce((n,a)=>n+a.durationMinutes,0),240);assert.equal(weekOne.assignments[2].workoutId,'tempo-climb-45')
const adaptive=readFileSync(new URL('../src/engine/adaptiveTraining40251.ts',import.meta.url),'utf8');for(const token of ['SELECTION_WEIGHTS','purposeMatch:40','Unknown — insufficient evidence','Recovery recommended','fourWeekPreview','replaceWithAlternative','No curated workout'])assert.match(adaptive,new RegExp(token));assert.doesNotMatch(adaptive,/machine learning|artificial intelligence|predicted FTP gain/i)
console.log('Alpha 4.0.25.1 audit passed: authenticated-session preview route, rendered labels, non-mutating lifecycle and idempotent Hal plan.')
