import assert from 'node:assert/strict'
import { createElement } from 'react'
import { renderToStaticMarkup } from 'react-dom/server'
import { getLibraryStage } from '../src/data/raceLibrary.ts'
import { adaptSegments } from '../src/engine/adaptiveRide.ts'
import { applyDurationSelection, durationSelectionForStage } from '../src/engine/durationEngine.ts'
import { createRoadModel } from '../src/engine/roadModel.ts'
import { canonicalCoursePosition } from '../src/engine/alpha4023.ts'
import { createPreRacePlan, preRaceSnapshot } from '../src/engine/preRaceLifecycle.ts'
import { ClimbProfile4023 } from '../src/components/ClimbProfile4023.ts'
import { LiveTrackerHeader4023, ProfileDetail4022, TacticalStatusStrip, WorldsGroupMarkers, WorldsOverviewLabels } from '../src/components/WorldsRaceLayer.ts'
import { CourseFinishMarker4023 } from '../src/components/CourseEndpointMarkers4023.ts'
import { RiderMarker4023 } from '../src/components/RiderMarker4023.ts'
import { targetPreview4023 } from '../src/engine/targetPreview4023.ts'
import { completionLabel, lifecycleJeanMessage, lifecycleProfileContext, resolveDetailGuidance4023 } from '../src/engine/cockpitPresentation4023.ts'
const stage=getLibraryStage('vuelta-2026',9)!
for(const minutes of [90,112]){const timed=applyDurationSelection(adaptSegments(stage.segments,206,'Balanced'),durationSelectionForStage(stage,{mode:minutes===90?'CUSTOM':'RECOMMENDED',customMinutes:minutes})).segments;const plan=createPreRacePlan(timed,minutes);assert.equal(preRaceSnapshot(plan,plan.warmupSeconds).phase,'KILOMETRE_ZERO');assert.equal(preRaceSnapshot(plan,plan.warmupSeconds).officialElapsed,0);const road=createRoadModel(9,plan.officialSegments,stage.distanceKm,undefined,stage.profilePoints,stage.officialCourseMarkers,stage.raceId,206);const before=canonicalCoursePosition(road,road.raceFinishTime-.01),finish=canonicalCoursePosition(road,road.raceFinishTime);assert(before.completion<100&&before.remainingDistance>0);assert.equal(finish.completion,100);assert.equal(finish.remainingDistance,0);const climb=road.climbs.at(-1)!;const position=canonicalCoursePosition(road,road.elapsedAtCourseDistance((climb.startDistance+climb.summitDistance)/2));const html=renderToStaticMarkup(createElement(ClimbProfile4023,{model:road,position,currentResistance:'resolver',nextResistance:'resolver',formatDistance:String,formatTime:String}));assert.match(html,/Continuous colored climb mountain/);assert.match(html,/data-direction="right"/);assert.doesNotMatch(html,/gradient-block/);const preview=targetPreview4023(position.currentSector,1,position.currentTargets);assert.equal(preview.power,position.currentTargets.power);assert.equal(preview.cadence,position.currentTargets.cadence);assert.equal(preview.openingResistance,position.currentTargets.manualTarget.recommendedResistance)}
const hub=renderToStaticMarkup(createElement(WorldsOverviewLabels));assert.equal((hub.match(/12× MOUNT ROYAL/g)??[]).length,1);assert.doesNotMatch(hub,/SOUTH SHORE|BRIDGE|AVENUE DU PARC/)
const rider=renderToStaticMarkup(createElement(RiderMarker4023,{kind:'profile',left:50,top:50,coordinate:.5}));assert.match(rider,/data-direction="right"/)
const detail=renderToStaticMarkup(createElement(ProfileDetail4022,{state:{mode:'DETAIL',activeRangeId:null,autoConsumedIds:[]},gradientBlocks:[],gradientIndex:0,currentGradient:-1.6,nextGradient:2.8,changeDistance:'0.3 mi',resistance:'45–48%',context:'Opening Mountain Approach'}));assert.match(detail,/Opening Mountain Approach/);assert.doesNotMatch(detail,/detail-gradient-blocks|POSITION IN VIEW/)
const tracker=renderToStaticMarkup(createElement(LiveTrackerHeader4023,{worlds:false,section:'Opening Mountain',zone:'Z3–Z4'}));assert.match(tracker,/LIVE STAGE TRACKER/);assert.equal((tracker.match(/<header/g)??[]).length,1)
const worldsMarkers=renderToStaticMarkup(createElement(WorldsGroupMarkers,{event:{id:'audit',trigger:0,expiry:1,caption:'Breakaway forms.',groupState:'BREAKAWAY',simulatedGap:'0:35',actions:[],responseWindowSeconds:20,effortDurationSeconds:60,preview:{powerMultiplier:1,cadence:90},accepted:{powerMultiplier:1,caption:''},decline:'BASE_PRESCRIPTION',resolutionCaption:'',detailRangeId:'audit'},courseProgress:.1}));assert.match(worldsMarkers,/>B<\/b>/);assert.match(worldsMarkers,/>P<\/b>/)
const finishMarker=renderToStaticMarkup(createElement('svg',null,createElement(CourseFinishMarker4023,{y:37.5})));assert.match(finishMarker,/data-endpoint-x="100"/);assert.match(finishMarker,/data-endpoint-y="37.500"/)
assert.match(finishMarker,/<rect[^>]*fill="rgba\(5,5,5,\.78\)"/);const finishText=finishMarker.match(/<text[^>]*>/)?.[0]??'';assert.match(finishText,/fill="#ffffff"/);assert.doesNotMatch(finishText,/stroke|paint-order/)
const attack=renderToStaticMarkup(createElement(TacticalStatusStrip,{state:'ACTIVE',action:'ATTACK',remaining:60}));assert.match(attack,/ATTACK ACTIVE/);assert.doesNotMatch(attack,/CHASE ACTIVE/)
const bounded=resolveDetailGuidance4023(null,null,false);const noBoundary=renderToStaticMarkup(createElement(ProfileDetail4022,{state:{mode:'DETAIL',activeRangeId:null,autoConsumedIds:[]},gradientBlocks:[],gradientIndex:0,currentGradient:0,nextGradient:bounded.gradient,nextName:bounded.name,changeDistance:null,resistance:'38–41%',context:'Brossard Rollout'}));assert.match(noBoundary,/NO UPCOMING GRADIENT CHANGE/);assert.doesNotMatch(noBoundary,/FINISH|CHANGE IN|POSITION IN VIEW/)
assert.equal(lifecycleProfileContext(true,'PRE_RACE_WARMUP','Opening Mountain'),'PRE-RACE STAGING');assert.equal(lifecycleProfileContext(true,'KILOMETRE_ZERO','Opening Mountain'),'KILOMETRE ZERO');assert.doesNotMatch(lifecycleJeanMessage(true,'PRE_RACE_WARMUP','stale'),/Press Start/);assert.equal(completionLabel(.4,.5),'<1% COMPLETE')
console.log('Alpha 4.0.23 audit passed: compact tracker/profile geometry, Detail-only gradients, one start gate/Jean banner, attack identity, B/P markers, source-elevation Finish, exact previews, and connected Climb View at 90/112 minutes.')
