import {writeFileSync} from 'node:fs'
import {toRaceStage,vuelta2026} from '../src/data/professionalRaces.ts'
import {adaptSegments} from '../src/engine/adaptiveRide.ts'
import {applyDurationSelection,durationSelectionForStage} from '../src/engine/durationEngine.ts'
import {createRoadModel} from '../src/engine/roadModel.ts'
const stage=toRaceStage(vuelta2026,vuelta2026.stages[5]),ftp=208,adapted=adaptSegments(stage.segments,ftp,'Balanced')
const summits=stage.profilePoints.flatMap((point,index,points)=>index>0&&index<points.length-1&&point.elevationM>points[index-1].elevationM&&point.elevationM>points[index+1].elevationM?[{summit:point.distanceKm,descentEnd:points[index+1].distanceKm}]:[])
const audits=['STANDARD','RECOMMENDED'].map(mode=>{const selection=durationSelectionForStage(stage,{mode:mode as 'STANDARD'|'RECOMMENDED'});const timed=applyDurationSelection(adapted,selection);const road=createRoadModel(stage.number,timed.segments,stage.distanceKm,undefined,stage.profilePoints,stage.officialCourseMarkers,stage.raceId,ftp);const positions=summits.flatMap(({summit,descentEnd},index)=>[{label:`summit-${index+1}-before`,km:summit-.001},{label:`summit-${index+1}`,km:summit},{label:`summit-${index+1}-after`,km:summit+.001},{label:`descent-${index+1}-midpoint`,km:(summit+descentEnd)/2},{label:`climb-${index+2}-entry`,km:descentEnd}]);return {mode,durationSeconds:road.duration,frames:positions.map(({label,km})=>{const state=road.roadSnapshot(road.elapsedAtCourseDistance(km)),live=state.livePrescription;return {label,officialElapsed:state.elapsed,courseDistance:state.courseDistance,elevation:state.elevation,sector:state.segment.name,canonicalGradient:state.gradient,effectiveGradient:live.manualRoadFeel.effectiveGradient,activeClimbId:state.activeClimbId,climbProgress:state.climbProgress,distanceToSummit:state.distanceToSummit,bikeProfile:live.manualRoadFeel.bikeProfile,calibrationConfidence:live.manualRoadFeel.calibrationConfidence,manualResistanceTarget:live.manualResistanceTarget,cadenceRange:live.cadenceRange,powerRange:live.powerRange}})}})
const output={race:'La Vuelta 2026',stage:6,route:stage.route,ftp,strategy:'Balanced',roadFeel:'full-road',audits};writeFileSync(new URL('../docs/alpha-4.0.18-stage6-manual-road-feel-audit.json',import.meta.url),JSON.stringify(output,null,2)+'\n');console.log(JSON.stringify(output,null,2))
